<%--
  Created by IntelliJ IDEA.
  User: elmirabajgulova
  Date: 31.10.2021
  Time: 00:19
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <link rel="stylesheet" href="css/styleZodiacSignsPages.css">
    <link rel="stylesheet" href="css/styleHome.css">


</head>
<body>
<section class="sub-header">
    <%@include file="/WEB-INF/top_nav.jsp" %>
    <h1>Aquarius</h1>
</section>


<div class="grid__content">
    <div class="editorial-article__feed">
        <h2>Aquarius Traits &amp; Overview</h2>
        <div class="zs-meta border-grey border-rad-4 grid-1c grid-sm-2c grid-lg-3c grid-c-gap-3 p-2 mb-3">
            <div class="meta-item"><span class="tag">Aquarius Dates: </span><span class="tag--bold white">January 21 – February 18</span></div>
            <div class="meta-item"><span class="tag">Symbol: </span><span class="tag--bold white">The Water-Bearer</span></div>
            <div class="meta-item"><span class="tag">Mode + Element: </span><span class="tag--bold white">Fixed Air</span></div>
            <div class="meta-item"><span class="tag">Ruling Planet: </span><span class="tag--bold white">Saturn &amp; Uranus</span></div>
            <div class="meta-item"><span class="tag">House:</span><span class="tag--bold white"> Eleventh</span></div>
            <div class="meta-item"><span class="tag">Mantra: </span><span class="tag--bold white">I Know</span></div>
            <div class="meta-item"><span class="tag">Body Parts: </span><span class="tag--bold white">The Shins</span></div>
            <div class="meta-item"><span class="tag">Colors: </span><span class="tag--bold white">Silver &amp; Blue</span></div>
            <div class="meta-item"><span class="tag">Tarot Card: </span><span class="tag--bold white">The Star</span></div>
        </div>
        <p>Aquarius is the eleventh sign of the zodiac, and Aquarians are the perfect representatives for the Age of Aquarius. Those born under this horoscope sign have the social conscience needed to carry us into the new millennium. Those of the Aquarius zodiac sign are humanitarian, philanthropic, and keenly interested in making the world a better place. Along those lines, they’d like to make the world work better, which is why they focus much of their energy on our social institutions and how they work (or don’t work).</p>
        <p>Aquarians are visionaries, progressive souls who love to spend time thinking about how things can be better. They are also quick to engage others in this process, which is why they have so many friends and acquaintances. Making the world a better place is a collaborative effort for Aquarians.</p>
        <h2>Aquarius Symbolism + Myth</h2>
        <p>The constellation of Aquarius, the Water-Bearer, is one of the oldest of our current zodiac. Harking back to Babylonian times, the Aquarius constellation was associated with the protective god Ea, who carried an overflowing vase of water.</p>
        <p>The Egyptians associated Aquarius with the flooding of the Nile, which was believed to occur when the Water-Bearer dipped his pitcher into the great river. The swelling of the Nile then corresponded to the commencement of Spring, a fertile time of growth after the flood of water to the region.<br>In Greek mythology, Aquarius was connected to the mythological youth Ganymede, who was the son of Tros, the Trojan king. Ganymede’s claim to fame came when Zeus transported him to Mount Olympus, to be the cupbearer of the gods.</p>
        <h2>Aquarius Element, Mode, and Season</h2>
        <h3>Winter</h3>
        <p>In the western tropical zodiac, Aquarius season begins on January 21, commencing the middle and heart of Winter in the Northern Hemisphere. This is the time of year when the sun, Leo’s planetary ruler, is at its lowest strength, heat, and light. This may lend cool and remote qualities to the Aquarian archetype, which tends to be more thoughtful and inventive during the cold, insular season.</p>
        <h3>Fixed Mode</h3>
        <p>Aquarius is the last of the four fixed signs of the zodiac, who all hold an elemental energy of endurance and stability in the middle phase of the four seasons. Aquarius begins the middle of winter, when the season is most “fixed” and established, lending to the tenacious, immovable, and somewhat stubborn tendencies of the formidable Aquarian intellect.</p>
        <h3>Air Element</h3>
        <p>Aquarius’ element is air, a light, dispersive element, thought by ancient astrologers to be an expression of matter that represents formlessness and dissolution. Aquarius’ affinity for innovation, invention, and intellectual focus is akin to the active, flowing air element.<br><br></p>
        <p></p>
        <h2>Aquarius Planetary Rulership</h2>
        <h3>Domicile of Saturn</h3>
        <p>In classical astrology, Saturn was assigned rulership of both Aquarius and Capricorn. Aquarius was thought to be the diurnal/day home of Saturn, an intellectual air sign that allows Saturn to be as scrutinizing, discerning, and objective of a planetary force as it likes to be when placed there.<br>Those born with Saturn in Aquarius will potentially have tremendous powers of intellectual discipline that they can apply well to study, administration, or in taking roles of social and judicial authority. When it comes to Saturinan matters of objectivity, perseverance, and patience, those born with the stern teacher in its diurnal domicile may take to these qualities naturally.</p>
        <h3>Detriment of the sun</h3>
        <p>Aquarius is in polarity with the fixed fire sign Leo. Ruled by the sun, Leo likes to radiate, conquer, and perform, where Aquarius, classically ruled by Saturn, likes to test, judge, and set boundaries. The sun, when in the opposite sign of his preferred home, is said to be in detriment, or at a sort of disadvantage in the cool and remote sign of Aquarius. Imagine the sun, the luminary of expression and confidence, tempered and contained in the world of time, trials, and discipline.</p>
        <p>Aquarius tends to be focused on rationality and objectivity, qualities that are developed with wisdom, restraint, and eldership, when the sun may more easily shine in the world of drama, pride, and passion. This proud, vital star would have to make do in Aquarius and compensate, presenting in those born with the sun in the Water-Bearer’s sign as having a more detached, and somewhat aloof presence. They may use their vitality and attention for more intellectual pursuits, and though may be unique and innovative, they may not seek a performative life in the theatrical sense.</p>
        <h3>Modern Ruler: Uranus</h3>
        <p>Uranus was discovered in 1781 by William Herchel, an astronomer who built his own telescope. This quality of discovery and inventiveness in Uranus’ founder lends itself to the Aquarian attributes of innovation, adaptation, and unconventionality.</p>
        <p>It is also interesting to note that at the time of Uranus’ discovery, the American Revolution was being waged, and the French Revolution would ensue within the years to come. These synchronicities inspired modern astrologers to give Uranus revolutionary characteristics since it appeared during these new political and societal upheavals. To the astrologers of the early modern period, this history of Uranus’ discovery felt akin to Aquarius’ nature, and so Uranus was assigned as the eccentric sub-ruler to the objective Water-Bearer.</p>
        <h2>Aquarius House Rulership</h2>
        <h3>The eleventh house</h3>
        <p>In the modern astrology system of the Twelve Letter Alphabet, each zodiac sign rules one of the twelve houses in the birth chart. This innovation was created by psychological astrologers to match sign affinities to related house topics.</p>
        <p>Aquarius was assigned the eleventh house of friends, alliances, and gifts since Aquarius’ social and intellectual pursuits are aligned with the concerns of this house. Since Uranus had been named a modern sub-ruler for Aquarius, it invites an offbeat Uranian sub-signature to the eleventh house.</p>
        <h3>The twelfth house</h3>
        <p>In classical astrology, Aquarius’ planetary ruler Saturn, was said to find its “joy” in the twelfth house of solitude, confinement, and isolation in the birth chart. The twelfth house was also called the house of “bad spirit” by classical astrologers, meaning it was connected to anxieties and shadowy themes that cause us some degree of mental anguish. This is related to Saturn classically being the planet responsible for our greatest tests and trials, that come about through feeling burdened with heavy responsibilities and concerns.</p>
        <p>As a result, Saturn is able to “joyfully” express its more limiting and uncomfortable offerings when placed here. The good news about this placement in the birth chart is that it can be connected with a theme of overcoming one’s enemies, and though difficult, can give the native great powers of perseverance through life’s hardest passages in the end.</p>
        <h2>Aquarius Characteristics</h2>
        <h3>Personality</h3>
        <p>Aquarius’ archetypal traits are derived from its active, masculine, or yang qualities, making this sign oriented toward engagement with the outer world. Alive in both an Aquarian woman or Aquarian man, those born with the Water-Bearer as their rising, sun, or moon sign have a clear objective, yet intelligent and inventive energy in their core personality, like the icy heart of winter.</p>
        <p>As a fixed sign, The Water-Bearer holds the qualities of being a sustainer, making those with Aquarius prominent in their charts great at dedicating themselves to projects, and tenaciously sticking to their social principals. Ruled by Saturn, Aquarians can be thought of as the “reformers” of the zodiac that challenge and test the societal conventions we have built to see if they are still relevant and inclusive.</p>
        <h3>Strengths</h3>
        <p>The primary Aquarian strengths can be found in their intelligence and their ability to not be mired in subjectivity that could potentially block maintaining a fresh perspective. Those under this sign have an affinity for abstract thought that allows them to examine problems and innovate new solutions. Though they are conversational and social, they can operate in their communities in an observant and impartial way, making them typically good judges of character, and dependable when rationality is needed.</p>
        <p>Aquarians are known for their cleverness and dry wit, which may be surprising in spite of their cool and collected exterior. The sign of the Water-Bearer produces naturally curious and inquisitive people who love to take apart objects, as well as personalities, to see what makes them tick. Perhaps a product of sober and determined Saturn, their planetary ruler, Aquarians are often not afraid to take intellectual, or creative risks, or to speak the sober but unpopular opinion. “Nothing lost, nothing gained” could be another Water-Bearer motto.</p>
        <p>The Aquarian archetype is naturally radical, and those with this sign prominent in their charts often feel they don’t fit in with mainstream society, and often, they don’t want to anyway! Usually, the world finds out later that their offbeat views and inventions were merely ahead of their time. It’s the rest of us who may need to try and keep up with our Aquarian inventors and thought leaders. Very often, they see the new frontier on the horizon, long before anyone else has a clue.</p>
        <h3>Weaknesses</h3>
        <p>Some sources of weakness for Aquarius are rooted in their great strengths. Their strong mental capacities can lead them to be overly intellectual in life, making them seem cold, distant, or unfeeling. They may encounter situations that they can’t think their way out of, which could be perplexing for them.</p>
        <p>The Water-Bearer’s capacity for abstract thought may have them reducing life to a series of puzzles to be solved, becoming so theoretical in their ideas that they become hard to relate to. Though typically good judges of character, this is a strength that can get taken too far when these folks get so stuck on the principle of another’s mistake that they judge them too harshly; sometimes even losing sight of their humanity.<br>Aquarians can become so “fixed” on their principles, that they hold others to higher standards than they could possibly attain. This may lead them to set many strict social boundaries and even holding grudges, possibly alienating others and isolating themselves.</p>
        <p>Clever, witty, and psychologically focused, Aquarians may use humor to toy with others they deem to be intellectually inferior to them. Though curious, this sign should guard against becoming nosy, and similar to their Gemini counterparts, may need to curb a habit of being gossipy. Though Aquarius may be cool and measured in their own feelings, they could forget what could be hurtful to others.</p>
        <p>Lastly, the Aquarian “contrarian” nature is best channeled into important and useful causes to guard against a habit of being rebellious and disruptive just for the sake of it. This can be hurtful and divisive if not well-considered.</p>
        <p>Aquarian children may grow up with a wounding around being an outsider. They will be well-nurtured by being accepted and embraced for their different nature, as well as allowed to experiment and express themselves in their own unique way.</p>
        <p></p>
        <p></p>
        <h2>Aquarius Life Purpose and Career</h2>
        <h3>Mantra and Purpose</h3>
        <p>The voice of invention, revolution, and abstraction comes forward in the Aquarius mantra: <strong>I know.</strong> The Water-Bearer’s sense of purpose is all about exploring new social, political, and technological frontiers. Aquarians are the “reformers,” challenging conventions and inspiring change in our world.</p>
        <p>We all have Aquarius somewhere in our birth chart, so we can look to the house that the Water-Bearer rules to find the specific area of our life we approach in an offbeat, intellectual, and even radical way; or where we need to call in the Water-Bearer’s inquisitive energy for mastery.</p>
        <p>Aquarian people tend to be drawn to any pursuit where they can do both—deconstruct and reconstruct—new systems of thought, social justice, and awareness. The worlds of science, research, education, and even psychology provide appropriate outlets for the Aquarian mind.</p>
        <h3>Aquarius at Work</h3>
        <p>Aquarius’ observant and inquisitive nature makes them uniquely suited for professions where they are able to explore, experiment, and innovate, following their theories and ideas toward breakthroughs. Their careers need to have some dynamic of invention and discovery to be fulfilling.<br>Their mind will likely be their strong suit, so jobs, where their intellect is not challenged or is underutilized, would not only be boring to them but a waste of their potential. This could manifest in many professions, but likely will not be found in salesmen or service-type roles, where they may have to project a persona that they are not feeling.</p>
        <p>Any job that has outdated, arbitrary rules will feel like a prison, so an ideal Aquarian career needs to be progressive in some way. Like all the air signs, Aquarius needs novelty, activity, movement, and space, and will not be content for long in the same location, unless of course, that location is a laboratory of some kind with much to study and discover!</p>
        <p>Aquarius’ classical ruler Saturn may lead Aquarians toward careers in social reform and justice. They may make excellent social workers, not only on the front line but in administrative roles as well. Those of this sign may, however, try to change the system and may not be content to work with a social system that does not serve everyone.</p>
        <p>With a great love for knowledge, and a sociable, talkative nature, those born under the Water-Bearer’s sign would make excellent teachers and educators. Being keenly interested in the evolution of humanity, they may be drawn to degrees in political science, gender studies, and even history.<br>The Water-Bearer’s keen powers of concentration could make them suited for research in a field that they find progressive and engaging. Fulfilling and fascinating to them, it would give them staying power to see a long-term project through, and may even champion an unusual study when others may not yet see its value.</p>
        <p>Science, with its many facets, suits Aquarians of all kinds. With their affinity for abstract thought, those under this sign may pursue physics, where they can explore quantum theories, and the very nature of the universe, to their endless delight.</p>
        <p>The scientific route may lead the Aquarian to the ultimate expression for their “out there” characters, into careers in space exploration. In addition to being an astronaut, work in the space sector requires engineering skills of all kinds, which could potentially be suited to our Water-Bearer friends. Aerospace, chemical, computer, electrical, mechanical and software engineering could all appeal to the math and analysis-inclined Aquarian.<br>Naturally inquisitive, and interested in exploring the powers of the mind, Aquarians can be well suited to psychology. Their clear and rational characters may be helpful in calmly exploring mental and emotional constructs with those that are in need of support.</p>
        <p>Aquarius’ radical, rebellious, and inventive nature must not be overlooked when we consider the art and entertainment world. The Water-Bearer’s offbeat and forward-thinking character could make them suited for sound design, as well as sound engineering. They may be found among our greatest electronic and “techno” musicians and performers.</p>
        <h2>Aquarius Compatibility</h2>
        <p>When exploring overall compatibility in astrology, it’s important to take more than the sun sign into consideration, as the rising sign, moon, and other planetary cross-connections will tell the whole story in relationships. That being said, Aquarius natives will tend to blend best with fire signs and air signs; and may need to work harder on relationships with water signs and earth signs.</p>
        <h3>Fire signs</h3>
        <p>Aquarius will typically find great affinity with fire signs, as they will understand each other’s active, spontaneous nature. Aries and Sagittarius are individualistic enough to not be put off by Aquarius’ cool and remote nature.</p>
        <p>Sagittarius, especially, will enjoy Aquarius’ socially challenging and radical ways, and they will stoke each other’s tendencies to be unconventional.<br>Aquarius brings discernment, thoughtfulness, and objectivity to proud solar-ruled Leo, and they potentially have an opposites attract connection together that can be either magnetic or polarizing.</p>
        <h3>Air signs</h3>
        <p>>Air signs are a natural fit for Aquarius, as they share the same elemental expression. Aquarius and Gemini will enjoy conversing endlessly, sharing ideas in a harmonious, although largely intellectual relationship.<br>Aquarius and Libra will enjoy sharing ideas on issues of social justice and progressive thought. Due to its Saturnian influence, Aquarius may at times be more cool and remote and will have to remember to show affection to romantic Libra.</p>
        <p>Aquarius with Aquarius could be a good match, in that they may feel they have finally met someone from their own galaxy, so to speak. They will enjoy debating, and innovating together, and may have an unconventional partnership.</p>
        <h3>Water Signs</h3>
        <p>Water signs&nbsp;bring vulnerability and emotional intelligence to help curious and abstract Aquarius to tap into their deeper wells of feeling.<br>Cancer will be very good at nurturing Aquarius, which they will likely need, but Cancer’s need for emotive connection and expression may feel foreign and overwhelming to rational Aquarius.</p>
        <p>Pisces broadens Aquarius’ receptive capacities by bringing spiritual and philosophical awareness to their lives. Pisces, however, may be too private and sensitive to fully appreciate Aquarius’ radical and contrarian nature.<br>Mars-ruled Scorpio can bring sexual magnetism to a relationship with Aquarius, but the two may share very little in common in the end. Scorpio’s jealous tendencies are as deeply rooted as Aquarius’ judgmental ones, and so they may stubbornly hold their own elemental ground and have conflicts often.</p>
        <h3>Earth signs</h3>
        <p>Though earth signs can potentially stabilize and ground Aquarius’ dispersive and unusual energies, they may be the hardest for those born under the sign of the Water-Bearer to relate to.</p>
        <p>Capricorn, the authoritative cardinal earth sign, shares Saturnian rulership with Aquarius, so there may be some common ground. Capricorn, however, tends to be practical and honors tradition, where Aquarius is innately unconventional, driving them to disagree on their basic values.<br>Taurus, although dependable and loving, may be a bit too rooted to roll with Aquarius’ “out there” ways. Both are in fixed signs, and much like the dynamic between Aquarius and Scorpio, there will be stubborn stand-offs between the Water-Bearer and the Bull.</p>
        <p>Aquarius and Virgo may blend with their analytical natures; however, Aquarius may be surrounded by gadgets and clutter, which would confound and annoy practical Virgo. Virgo likes to be useful, but Aquarius always questions practicality, making this too much of an odd pairing to make it last.</p>
        <h2>Aquarius Health</h2>
        <h3>Constitution</h3>
        <p>In classical astrological medicine, there were four temperaments that were connected to four vital fluids and four essential constitution types. Being ruled by Saturn, Aquarius is associated with the sanguine temperament, which was thought to be hot and moist and connected to the blood.<br>The sanguine constitution was considered to be naturally healthy and resilient, being connected to the youthful phase of life, and the spring season. Sanguine folks typically have a cheery disposition, lean body shapes, and are naturally energetic. With Saturn’s influence here, however, Water-Bearer may need to guard against a tendency towards melancholy and will need to care for their bones and joints.</p>
        <p>Apart from Aquarian-type imbalances related to dehydration, or depleted energy from overwork, this constitution type may not experience many health challenges until their later years. At this time, issues related to blood pressure or blood stagnation may arise when the naturally high sanguine metabolism starts to slow down.</p>
        <h3>Body Parts</h3>
        <p>In classical astrological medicine, the entire zodiac was mapped out on the human body, with Aquarius ruling over the shins, calves, and ankles. As a result, those born with Aquarius prominent in their birth charts may have long legs, narrow shins, and ankles that are prone to rolling or sprains.<br>Those native to this sign will need to stay hydrated and keep their bodies warm and circulating. Being born in the heart of winter may cool their sanguine temperaments down somewhat, making them prone to stiffness and chilliness.</p>
        <h2>Herbal Allies</h2>
        <p><strong>Comfrey</strong>, also known as “boneset” or “knit bone,” grows in damp, grassy places. It is rich in vitamin C and calcium, has anti-inflammatory properties, and is a traditional herbal remedy used to treat bruises, sprains, and bone fractures.</p>
        <p>Its mineral-rich qualities can internally “knit” bones and connective tissues back together. It contains allantoin, which when used topically can help heal wounds. An ointment or compress made from comfrey can also soothe joint and arthritis pain; and can be an asset to the sensitive shins and ankles of Water-Bearers.</p>
        <p><strong>Horsetail</strong>&nbsp;is a prime Saturnian plant rich in minerals and vitamins, including vitamins B, C, E, K, potassium, calcium, magnesium, iron, zinc, copper, and silica. As a result, it is excellent for building strong bones, teeth, hair, nails, and skin.</p>
        <p>Horsetail tea can help improve bone density in those suffering from osteoporosis and can clear water retention, urinary tract infections, and kidney and bladder stones. Horsetail itself is so strong and fibrous, it was used to polish metal in ancient times.</p>
        <p><strong>Rosemary&nbsp;</strong>is a remedial plant for Aquarius, with its solar properties offering the medicine of “antipathy” for the effects of the sun being in its detriment or exile. It is moderately hot and dry and grows in dry sunny environments that would be the opposite condition to Aquarius’ winter realm.</p>
        <p>Rosemary brings heat and warmth to the head, and its stimulating herbal fragrance helps to improve mental clarity and memory retention for intellectually active Aquarians. It is astringent and a known carminative, meaning it helps to relieve gasses and promote digestion. Rosemary oil—when diluted in a light carrier oil—is excellent for massage. Its relaxing solar warmth is very soothing to tight, tired Aquarian calves and shins.</p>
        <h2>Esoteric Aquarius</h2>
        <h3>The Three Decans of Aquarius</h3>
        <p>Each of the twelve zodiac signs represents a thirty-degree slice of a 360-degree band of constellations, circling the earth. The thirty degrees of each sign can be further subdivided into three ten-degree decans, or faces, each with its own planetary sub-ruler placed around the zodiac in Chaldean order.</p>
        <p>These faces can be used for timing magical rituals when seeking to evoke and harness Saturn’s planetary power. In studying the Aquarius personality, we can use the faces of Aquarius to fine-tune the flavor and nuance of planets or points placed within these decanic degrees.</p>
        <h3>First Decan of Aquarius: Venus</h3>
        <p>Degrees 0 through 9 of Aquarius are ruled by Venus, making those with planets in the first decan potentially more artistic and relational than the typical cool Aquarian archetype. Those born with planets or points here may be more creative, romantic, and performative of all the Water-Bearers.</p>
        <h3>Second Decan of Aquarius: Mercury</h3>
        <p>Degrees 10 through 19 of Aquarius are ruled by Mercury. This face indicates very strong analytical and intellectual tendencies in those with prominent placements here. We may see the scientists, inventors, and engineers among these natives. We also may see those with more active literary and conversational leanings.</p>
        <h3>Third Decan of Aquarius: Moon</h3>
        <p>Degrees 20 through 29 of Aquarius are ruled by the nurturing and mysterious moon. The moon’s influence here amplifies the emotions somewhat, making these folks more sensitive, receptive, and even psychic. It could even take form in those born with placements in the third decan as being more remote and protective of their emotions.</p>
        <h2>Aquarius Tarot Cards</h2>
        <h3>Major Arcana: The Star</h3>
        <p>The Tarot card that correlates to Aquarius is number 17: The Star. This card depicts an angelic Water-Bearer pouring out their cisterns below a starry night sky. The Water-Bearer has one foot in the water, representing intuition, while one foot is planted on the earth, rooting the figure to the material realm. One cistern empties into a mysterious sparkling pool, with the other quenching the dry soil.</p>
        <p>This duality is a balance between manifestation, and the well of the soul, all under the guidance of the divine realm. The figure represents the querent after a time of upheaval, finding their essence of expression and at last understanding what form it needs to take to be alive in the world. It helps us to meditate on our unique gifts and creative forces that need to come from the depths of knowing within us all before they can be “poured out” in the most nourishing and balanced way.</p>
        <h2>Minor Arcana</h2>
        <p><strong>5,6, and 7 of Swords</strong><br>In the Minor Arcana of the Tarot,the Suit of Swords is associated with the element of air. Here, we see the three decans of Aquarius assigned to the 5, 6, and 7 of Swords, cards associated with the awareness that comes with cultivating and sustaining intellectual clarity. These cards may speak to times of mental wounding and overcoming self-doubt in the midst of intense spiritual and energetic evolution.</p>
        <p><strong>5 of Swords: Venus in Aquarius</strong><br>The 5 of Swords corresponds to the first decan or face of Aquarius. It carries the sub-signature of Venus and was referred to in the Book of Thoth as the card of “Defeat.” This card appears when we may have achieved an intellectual or mental victory, but we ourselves are somewhat defeated, having lost our ability to be emotional and relational.<br>The “Defeat” card also warns that “treachery also may be implied.” (Book of Thoth)</p>
        <p><strong>6 of Swords: Mercury in Aquarius</strong><br>The 6 of Swords corresponds to the second decan or face of Aquarius. It carries the sub-signature of Mercury and was referred to in the Book of Thoth as the card of “Science.” This card appears when we are about to embark on a passage to escape old patterns of thought, but the somber mood of the characters depicted hints that anxiety and uncertainty lingers.<br>The “Science” card shows the “perfect balance of all mental and moral faculties, hardly won, and almost impossible to hold in an ever-changing world.” (Book of Thoth)</p>
        <p><strong>7 of Swords: Moon in Aquarius</strong><br>The 7 of Swords corresponds to the third decan or face of Aquarius. It carries the sub-signature of the moon and was referred to in the Book of Thoth as the card of “Futility.” This dynamic card appears when we have taken on more than we can mentally and energetically handle. It shows some trickery, or underhandedness, perhaps acting on impulse with a lack of emotional balance.</p>
        <p>The “Futility” card represents “intellectual wreckage” and warns the “results may be more disastrous than ever.” (Book of Thoth)</p>
        <p></p>
    </div>
</div>

</body>
</html>
