<%--
  Created by IntelliJ IDEA.
  User: elmirabajgulova
  Date: 31.10.2021
  Time: 00:19
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <meta name="viewport" content="with=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/styleHome.css">
    <link rel="stylesheet" href="css/styleZodiacSignsPages.css">
</head>
<body>
<section class="sub-header">
    <%@include file="/WEB-INF/top_nav.jsp" %>
    <h1>Cancer</h1>

</section>
<div class="grid__content">
    <h1>Cancer</h1>

    <div class="editorial-article__feed">
        <h2>Cancer Traits &amp; Overview</h2>
        <div class="zs-meta border-grey border-rad-4 grid-1c grid-sm-2c grid-lg-3c grid-c-gap-3 p-2 mb-3">
            <div class="meta-item"><span class="tag">Cancer Dates: </span> <span class="tag--bold white">June 21 – July 22</span></div>
            <div class="meta-item"><span class="tag">Symbol: </span> <span class="tag--bold white">The Crab</span></div>
            <div class="meta-item"><span class="tag">Mode + Element: </span> <span class="tag--bold white">Cardinal Water</span></div>
            <div class="meta-item"><span class="tag">Ruling Planet: </span> <span class="tag--bold white">Moon</span></div>
            <div class="meta-item"><span class="tag">House:</span> <span class="tag--bold white"> Fourth</span></div>
            <div class="meta-item"><span class="tag">Mantra: </span> <span class="tag--bold white">I Feel</span></div>
            <div class="meta-item"><span class="tag">Body Parts: </span> <span class="tag--bold white">The Stomach, Brain, &amp; Breasts</span></div>
            <div class="meta-item"><span class="tag">Colors: </span> <span class="tag--bold white">Silver &amp; White</span></div>
            <div class="meta-item"><span class="tag">Tarot Card: </span> <span class="tag--bold white">The Chariot</span></div>
        </div>
        <p>Cancer, the fourth sign of the zodiac, is all about home. Those born under this horoscope sign are ‘roots’ kinds of people, and take great pleasure in the comforts of home and family.</p>
        <p>Cancers are maternal, domestic, and love to nurture others. More than likely, their family will be large, too—the more, the merrier! Cancers will certainly be merry if their home life is serene and harmonious.</p>
        <p>Traditions are upheld with great zest in a Cancer’s household, since, as the rulers of the fourth house of home and memory, this zodiac sign prizes family history and loves communal activities. They also tend to be patriotic, waving the flag whenever possible. A Cancer’s good memory is the basis for stories told around the dinner table, and don’t be surprised if these folks get emotional about things. Those born under this sign wear their heart on their sleeve, which is just fine by them.</p>
        <h2>Cancer Symbolism + Myth</h2>
        <p>The constellation known as Cancer has its roots in many ancient civilizations, where it has been identified as various hard-shelled mythological creatures. In Egyptian belief, it was associated with the scarab, the symbol of immortality. The connection with the afterlife continues into Babylonian culture, where Cancer was thought to be the god that was the guide to the passage through the underworld and death.</p>
        <p>The Crab makes an appearance in Greek legend, with its notable part in the tale of Hercules battling the Hydra. Karkinos, the Crab, was sent by the goddess Hera, who was not a fan of Hercules, to distract him and give the Hydra an advantage. When Karkinos bites Hercules on the foot, he kills him by cracking his shell. As a reward for risking his life to do Hera’s bidding, Karkinos is placed in the heavens, to shine for eternity.</p>
        <h2>Cancer Element, Mode, and Season</h2>
        <h3>&nbsp;Summer Solstice</h3>
        <p>In the western tropical zodiac, Cancer season begins on June 21, commencing the Summer Solstice in the Northern Hemisphere. This is the time of year when the sun’s heat and light are at its peak, with daylight outweighing the night hours. From this point, the days slowly begin to decrease toward the Autumn Equinox, representing the second seasonal pivot of the year.</p>
        <p>Cancer’s connection with nurturance, sustenance, and rejuvenation is mirrored in the bounty of energy and resources in the Summer months.</p>
        <h3>Cardinal Mode</h3>
        <p>Cancer is the second of the four cardinal signs of the zodiac, who all hold elemental energy of initiation and leadership at the beginning of the four seasons. Cancer season is the beginning of Summer, where the light and energy are in abundance. This definitive, nourishing seasonal quality is the root of Cancer’s strong cardinal authority and nature as an archetype.</p>
        <h3>Water Element</h3>
        <p>Ruled by the moon,Cancer’s element is water, the second heaviest element, thought by ancient astrologers to be the fluid, adaptive, yet a tangible form of matter. Water represents the moistening and cohering principle that binds and connects all forms of nature.</p>
        <p>Without it, nothing that takes a material form could “stick” together. Water fertilizes earth so that nature and creativity can incubate and bloom. Cancer’s affinity for nurturance, protection, and leadership in melding people into family units are all akin to the consolidating connectivity of the water element.<br></p>
        <p></p>
        <h2>Cancer Planetary Rulership</h2>
        <h3>&nbsp;Domicile of the moon</h3>
        <p class="has-text-align-left">In classical astrology, the moon was assigned rulership of Cancer exclusively. The moon is the luminary of the night, a receptacle and reflector of the sun’s vital rays, guiding us in the darkness. Classically, the moon was thought to be the protector of the earth, interceding between us and the bold, active, and divine rays of the other powerful planets.</p>
        <p>Like a mother bird breaking down food into a more palpable form, the moon filters the intensive cosmic rays for all life in her “sublunary realm” so that we are not overwhelmed or destroyed by their powers.<br>One wonders if the ancients saw the moon’s craters as evidence that she was shielding us from potential cosmic hits. These are where some of the maternal qualities of the moon were observed to be at work, giving the moon in Cancer a special potency and divinity while at home in the Crab’s sign.</p>
        <p>In the watery and protective sign of cancer, the moon can be as nurturing, emotive, and as intuitive of a force on the psyche and in the cosmos, as she likes to be. Regardless of the gender they identify with, those with the moon in Cancer will have a strong maternal, protective, emotive, and psychic energy in their core nature.</p>
        <h3>Detriment of Saturn</h3>
        <p>Ruled by the moon, Cancer is in polarity with the cardinal earth sign Capricorn. Ruled by Saturn, Capricorn is cool, reserved, and strongly pragmatic. Being innately practical, at times stern, and mistrustful of vulnerability, Saturn-ruled Capricorn is a contrast to moon-ruled Cancer, whose insular and emotive instincts wire this archetype to be innately maternal and intuitive.</p>
        <p>Imagine a stern and unyielding Saturn in Cancer’s soft, sentimental, and somewhat dreamy world. Saturn in the moon’s sign would have to somewhat compensate for this “detriment,” being somewhat out of their element in this fluid environment.</p>
        <p>This may simply mean that natives born with this placement may either tend to have protective barriers around their emotions, or they may blend Saturn’s judgement with Cancer’s emotiveness, to be inordinately defensive and self-protective. It can have a Saturnian effect on the moods of these natives, making them prone to bouts of sadness and depression.</p>
        <p>This placement could also cause the native to place many rules and restrictions around themselves when it comes to their emotional engagements with others, and they may be prone to holding long grudges if they are hurt or crossed. Saturn compensating in Cancer may also present a strong instinct to protect others who are vulnerable, in their communities, or their societies at large.</p>
        <h3>Exaltation of Jupiter</h3>
        <p>Jupiter, the planet of belief, benevolence, and opportunity, has a specially exalted place in Cancer. Here, the Jupiterian powers of mentorship and affirmation blend uniquely well with Cancer’s nurturing and protective qualities.</p>
        <p>This placement can combine to produce great teachers, parents, spiritual guides, and may amplify the Cancerian psychic abilities. Depending on how or where Jupiter in the moon’s sign is placed in a person’s birth chart it can be a very lucky placement that offers prosperity and privileges to the native, that in their generosity they will no doubt share with others.</p>
        <h3>Fall of Mars</h3>
        <p>Mars was said to be exalted in Capricorn by classical astrologers, where he can uniquely and constructively express his tenacious martial powers.<br>When in the opposite sign of Cancer, Mars was said to be in his fall, which may not pose as strong of an adaptive challenge as a detriment might, yet still puts the planetary force somewhat out of its comfort zone. It points to ways that Mars’ typically aggressive and divisive energies present as somewhat volatile, in that they often vacillate between being over or underutilized in the life of the native.</p>
        <p>As a sign, Cancer promotes soothing, nurturing, and healing, where Mars promotes inflaming, confronting, and competing, so the watery influence of Cancer may squelch the abilities to be assertive and take initiative.<br>In the interest of not hurting others, Mars in Cancer natives may suppress, or deny their anger, causing it to fester and come out in untimely ways. The insight that natives with this placement gain in melding these very different energies are found in how they create balance and set appropriate boundaries when dealing with anger. They may have to find activities to vent their frustrations so that they do not become inordinately defensive, or overly protective of those that they love.</p>
        <p>This placement can also be seen as the use of martial talents in Cancerian ways. For example, Mars’ affinity with fire and sharp knives blended with Cancer’s love of nurturing, could produce passionate cooks and chefs.</p>
        <h2>Cancer House Rulership</h2>
        <h3>&nbsp;The Fourth House</h3>
        <p>In the modern astrology system of the Twelve Letter Alphabet, each zodiac sign rules one of the twelve houses in the birth chart. This innovation was created by psychological astrologers to match sign affinities to related house topics.</p>
        <p>Cancer was assigned the fourth house of ancestry, roots, and home since Cancer’s watery, emotive, and protective expressions are aligned with the concerns of this house. Since Cancer is ruled by the receptive and reflective moon, it invites a nurturing sub-signature to the fourth house.</p>
        <h3>The Third House</h3>
        <p>In classical astrology, Cancer’s planetary ruler of the moon was said to find her “joy” in the third house of siblings, neighbors, and short-term travel in the birth chart. The third house was also called the house of “the goddess” by classical astrologers, meaning it was connected to the nocturnal passage into the mysteries of sleep, dreaming, and regeneration that the moon ruled over.</p>
        <p>The third house is in polarity with the ninth, where the sun was said to find its joy, being connected to longer, yearly solar perambulations and travels. By contrast, the moon, with its swift movement around the zodiac every month, was associated with shorter, more local travel, around one’s village or neighborhood. The moon, as a result, has some special potency or “dignity” in the third house of the birth chart.</p>
        <h2>Cancer Characteristics</h2>
        <h3><strong>&nbsp;</strong>Personality</h3>
        <p class="has-text-align-left">Ruled by the moon, Cancer’s archetypal traits are derived from its receptive, feminine, or yin qualities, making this sign oriented toward contemplation, and engagement with inner awareness. Alive in both a Cancer woman or Cancer man, those born with the Crab as their rising, sun, or moon sign have a sensitive, intuitive, and protective awareness in the core of their personality; an echo of the life-supporting and sustaining energies of the Summer season.</p>
        <p>As a cardinal sign, Cancer takes leadership in the roles of being a nurturer, host, protector, and caretaker. Those born with the sign of the Crab prominent in their charts are focused on forming and maintaining family ties. They are naturally empathic, sentimental, and home-loving by nature.</p>
        <h3>Strengths</h3>
        <p>The primary Cancer strengths can be found in their kind, giving, and sympathetic natures. Always ready to host, and set a table, they can be counted on to feed and care for friends, family, and any weary traveler that stays in their home. With strong empathic powers and talents for healing, Cancer natives can sense what others need, often long before they have articulated it themselves.</p>
        <p>The famous sideways walk of the Crab can be observed in the cautious way a Cancer native enters a space or social gathering. They tend to come in quietly, carefully surveying their surroundings, before they open and reveal their whole selves. This protective instinct makes Cancerians good at reading the emotional tone in a room, helping them anticipate danger or crisis early.</p>
        <p>There is always something familiar about those born under the sign of the Crab, and those with this sign rising, especially, give people the uncanny feeling they have met them before. This quality has roots in this archetype’s connection to nurturing and building a home, often making people instantly feel at home with them.</p>
        <p>The ease, familiarity, and trust they inspire allow those who meet them to open up in quickly, saying to the Cancerian “I feel like I could tell anything” or “It’s like I’ve known you my whole life.” This uncanny quality serves the Crab natives well in their roles and professions, which usually have some healing or nurturing aspect to them. Cancer natives are usually steadfast and loyal, and once you have been accepted into their hearts, and inner circle, they will be your friend for life.</p>
        <p>No matter what gender Cancerians identify with, they often have a strong matriarchal presence in their homes, communities, and workplaces. Cancer natives have great sympathy for the underdog and the downtrodden, and though usually quiet and peaceable, their claws come out when protecting the vulnerable. They are also vigilant about protecting themselves, learning the importance of strong emotional and energetic boundaries from a young age.</p>
        <h3>Weaknesses</h3>
        <p>Some potential weaknesses in the Cancer archetype are rooted in their great strengths. Though they love creating a comfortable home, they can become so emotionally and sentimentally connected to their space and their belongings, that it’s hard to let go and make changes when needed. Their natural giving tendencies, if unbalanced, can cause natives from this sign to over-identify with being needed. They could be vulnerable to projecting their neediness onto others, by enabling codependent relationships.</p>
        <p>Cancerian emotional instincts can be protective, and helpful, but can also become overactive if they are not feeling healthy and grounded. This could lead them to become fearful, reclusive, and hyper-vigilant when exploring the outer world. Gentle Cancer naturally inspires trust in others; however, this can be taken advantage of, causing those born under the sign of the Crab to get caught doing too much emotional labor, and stuck holding other’s emotional baggage.</p>
        <p>Like all water signs, Cancer is vulnerable to absorbing toxic energies, so if they are in healing or counseling work of some kind, they need to have cleansing practices. Breathing exercises, saunas, smudging, and protective aura visualizations are all ways the Cancer native can maintain a “psychic shell” to keep their energy clear.</p>
        <p>Family, be that chosen or biological, are all important to Cancer, yet these natives need to beware of a tendency to be clannish, exclusive, and slow to trust outsiders. There may be good reasons for this caution, but it is still important for Cancer natives to keep this reflex in check so that they don’t hurt, reject, or alienate anyone who is feeling vulnerable.</p>
        <p>The strong matriarchal tendencies of this archetype are a powerful asset but can be overdone, showing up in bossy, smothering, and even manipulative tendencies if the Cancer native is trying too hard to control their environment.</p>
        <p>With the moon’s connection to the brain, Cancerians are famous for their long memories, making them prone to holding grudges. Others will feel the pinch of reactive, and sometimes hurtful words if they cross the Crab.<br>Shy and sensitive Cancer children will be well-nurtured if they are allowed to come out of their shells on their own time.<br></p>
        <p></p>
        <h2>Cancer Life Purpose and Career</h2>
        <h3>&nbsp;Mantra and Purpose</h3>
        <p>The voice of empathy, intuition, and sensitivity comes forward in the Cancer mantra: <strong>I feel.</strong> The Crab’s sense of purpose is all about facilitating and nurturing emotional understanding, expression, and awareness. With strong cardinal leadership skills, these natives will be fulfilled by taking prominent roles as heads of families, households, communities, and are often involved in supporting the emotional well-being of those in their workplaces.</p>
        <p>We all have Cancer somewhere in our birth chart, so we can look to the house that the Crab rules to find the specific area of our life we approach in a nurturing and intuitive way, or where we need to call in an empathic Cancerian sensibility for material mastery.</p>
        <h3>Cancer at Work</h3>
        <p>Cancer’s caring and comforting nature makes them uniquely suited for professions where they are needed to use their protective and healing instincts. This could take form in many professions and roles, but will likely not be found in jobs that are high risk, stressful, or move at an accelerated pace. Some exceptions could be found in health care, where their attentiveness and vigilance in a crisis may be an asset, or when cooking in high energy kitchens.</p>
        <p>Otherwise, Cancers will enjoy peace, solitude, and intimate environments in which to do their work. They love belonging to a group but may prefer the one-to-one dynamic, where they can create a protected container and apply their undivided attention. It is very likely that by using their nesting instincts, these natives will find a way to work from home, or will have work that is connected to home visits.</p>
        <p>Should they work in an office or modern building, they will add cozy elements to their workspace to make it feel “homier.” Their section of the staff room, or office refrigerator, will be brimming with snacks, teas, and their favorite flatware so that they feel nourished and prepared for their day.</p>
        <p>Cancer’s connection to home has them overseeing many styles of accommodations and abodes in their professions. You may find them managing hotels, bed and breakfasts, or working as landlords, property managers, home inspectors, or realtors.</p>
        <p>The Cancerian maternal instincts also make these natives suited to all kinds of caretaker, and childcare roles. They may work in nursing homes, daycares, as nannies, and will likely find satisfaction in housekeeping and homemaking.</p>
        <p>The Crab’s strong healing and caring tendencies make them suited for the many facets of our health care system. We could easily see them working as family doctors, pediatricians, and nurses.</p>
        <p>Cancer’s connection with nurturing and protecting the young will likely lead many of these natives to teach children. They may do this through art and music in preschools and elementary schools. They may also use their creativity and storytelling powers as children’s authors and illustrators.<br>Social welfare and mental health are likely to be of interest to Cancer natives, as they can be suited to work that supports emotional well-being. We could see this expression take form in social work, and also in roles as therapists and counselors.</p>
        <p>The Crab’s mystic side can emerge in the role of the local psychic, or medium, as they offer insight and comfort to spiritual seekers.<br>Those born under the sign of the Crab delight in setting a table and creating a comfortable dining atmosphere. Food and everything to do with it is a natural vocation path for the Cancer native. They may enjoy keeping this passion on an intimate, home-based level, or it could take form in roles as fine food merchants, restaurateurs, chefs, caterers, bakers, or even as servers or hosts.</p>
        <p>All signs have their creative side, and this can take many forms for the Cancerian. We may find it alive in talents for interior design, as well as home decorating.</p>
        <p>These natives may also be drawn to water sports like swimming and surfing, and they would make dependable protective lifeguards.</p>
        <h2>Cancer Compatibility</h2>
        <p>When exploring overall compatibility, it’s important to consider more than the sun sign, as the rising sign, moon and other planetary connections will tell the whole story. That being said, Cancer natives will tend to blend best with water signs and earth signs; and may need to work harder on relationships with fire signs and air signs.</p>
        <h3>Fire signs</h3>
        <p>Of all zodiac signs, sensitive Cancer may find the volatile and impulsive fire signs the trickiest to relate to.</p>
        <p>Although Cancer’s shy and cautious nature may benefit from collaborating with fiery warmth and enthusiasm, Mars-ruled Aries, especially, may be too brash and headstrong to relax and settle down with Cancer. Both are cardinal signs, so they may wrestle for leadership and control of their shared environment. Aries may have impatient and harsh words at the moment, but Cancer will never forget the burn.</p>
        <p>Sagittarius and Cancer share nothing modally or elementally in common. This pairing is unusual and may have many challenges set against it to truly work. Cancer is sentimental and home-based, where Sagittarius is restless and roving, so they may disagree on how to spend their time together. Sincere and sensitive Cancer will not care for Sagittarius’ brand of brutal honesty, and many misunderstandings will ensue.</p>
        <p>Leo and Cancer also have nothing elementally or modally in common, being in adjacent signs of the zodiac, so they may have a hard time relating and connecting romantically long-term. Leo is ruled by the outgoing sun, and Cancer is ruled by the insular moon, possibly creating an “opposites attract” connection. This polarity is more likely to keep them forever as divided as the day is from the night.</p>
        <h3>Air signs</h3>
        <p>Air signs are speedy, swift, and social, which could be a breath of fresh air in Cancer’s reflective and somewhat moody world, but intimately Cancer may find the air signs a bit too breezy and changeable to truly depend on.<br>Gemini and Cancer do not share much in common, with the Twins being intensely social, and Cancer being intensely private. The Crab may often find they are soothing Gemini’s frayed nerves and may have a hard time keeping up with their mental chatter. But the two may tire of this dynamic after a while and will need to respect each other’s different rhythms to last long-term.</p>
        <p>Libra and Cancer can work well together, with Venusian and lunar natures blending more easily than with other air signs. Libra’s social and artistic world doesn’t seem to overlap much with Cancer’s private life, but they could come together as co-hosts of beautiful and intimate dinner parties. Eventually, Cancer will need to withdraw and will seem moodier than upbeat Libra. They would need to learn how to navigate these emotional differences.</p>
        <p>Aquarius with Cancer is potentially a challenging match. Cancer is ruled by the nurturing moon, and Aquarius is ruled by stern and remote Saturn. Though Aquarius may benefit from Cancer’s attention and care, it may not be natural for them to reciprocate what Cancer truly needs to feel secure. They are perhaps too different on an emotional level to achieve lasting intimacy without conscious, intentional work.</p>
        <h3>Water Signs</h3>
        <p>Water signs match Cancer’s vulnerability and emotional intelligence with the greatest affinity. There seems to be a psychic, intuitive current running between them that transcends words.</p>
        <p>Cancer with Cancer is a natural, peas in a pod type of fit, where they share many similar values and needs. They easily make a home together and agree on feeling out major life decisions. A potential pitfall presents if they are too much alike and struggle for control, or if they are having an intense mood at the same time. They will likely have enough caring and empathy between them to work it out.</p>
        <p>Pisces broadens Cancer’s receptive capacities by bringing spiritual and philosophical ideas to the relationship. This is a complementary pairing that is innately intuitive, mystical, and otherworldly. They will enjoy their privacy and solitude together and may collaborate easily on creative projects.</p>
        <p>Mars-ruled Scorpio can bring sexual magnetism to a relationship with Cancer, helping them open up to sensuality and exploration. This is a magnetic match, with both signs able to explore potent themes of power and mystery together. Cancer, being a quite intense sign, is not intimidated by Scorpio’s deep and moody nature. The Scorpion may be at times a little too taboo for shy Cancer, but this may be what they are attracted to, to help broaden their horizons.</p>
        <h3>Earth signs</h3>
        <p>Earth signs bring a complementary, elemental affinity to a relationship with Cancer since practical earth and emotive water blend well.</p>
        <p>Cancer is Capricorn’s polar opposite, bringing care and nurturing to Capricorn that they will sorely need. The two have an opposites attract connection, that may either complete the whole picture, or be too polarizing. Cancer enjoys creating a warm home, where Capricorn is often married to their work, so if they can blend each other’s strengths, they can help balance each other out.</p>
        <p>Cancer and Virgo together are a potentially strong match. They will appreciate each other’s conscientious, sensitive, and thoughtful natures and may collaborate well on a shared business in health or nutrition. Virgo adds detail and structure to Cancer’s nurturing and generous life. Their lives and approaches mesh well, and they make natural companions.</p>
        <p>Cancer and Taurus share many affinities and may especially connect over their enjoyment of fine food, wine, and sensual pleasures. Venus-ruled Taurus draws the romantic lover out of moon ruled homebody Cancer, and the Crab appreciates Taurus’ supportive, dependable nature. They are sure to have a lot of fun together and will enjoy decorating their home to create a nurturing ambiance.</p>
        <h2>Cancer Health</h2>
        <h3><strong>&nbsp;</strong>Constitution</h3>
        <p>In classical astrological medicine, four temperaments were connected to four vital fluids and 4 essential constitution types. Cancer is a water sign, and so is associated with the phlegmatic temperament, which was understood to be cold and moist.</p>
        <p>The phlegmatic temperament was thought to be connected to moisture and fats in the body, and the production of phlegm, which lubricates tissues and protects these from infection. Phlegm however can be the source of imbalance for the phlegmatic constitution, often being overproduced when Cancers fall ill, or if they become inactive or overly nourished. This represents a tendency for the phlegmatic constitution to become somewhat chilled and stagnant, physically and emotionally.</p>
        <p>Because of their tendency to mood swings, Cancer natives can become too clingy, sentimental, and overly retentive of water and other fluids in their bodies. Their tissues can become boggy, lax, and clogged with toxic emotional substances, building up too much and not being adequately cleaned out.</p>
        <p>Cancers, in particular, tend to be doubly phlegmatic, as their planetary ruler, the moon, adds another cold and moist layer to their constitution. As a result, it is important for Cancers to stay warm and active, and to guard against emotional eating that can cause them to feel sluggish. They may, however, have good powers of recuperation and regeneration, and will need lots of sleep to recharge.</p>
        <h3>Body Parts</h3>
        <p>In classical astrological medicine, the entire zodiac was mapped out on the human body, with Cancer ruling over the stomach, brain tissue, and breasts. Being phlegmatic, and under the moon’s rule, all moist and fatty tissues are connected to Cancer, as are organs that provide or absorb nourishment. This is why the stomach and the mammary tissue are connected to this maternal and nurturing sign.</p>
        <p>In medical astrology, both Mercury and the moon rule over the brain. Where Mercury is connected to the intellect, and nervous system responses of the brain, the moon is connected to what was called “the bulk” of the brain; the soft fatty tissue that forms the brain’s mass.<br>This is where Cancer’s retentive powers and long memory were observed and understood according to this classical system. As a result, Cancers should focus on eating whole, unprocessed foods, and keep their bodies and lymphatic systems circulating toxins out of their fats and glands.</p>
        <h2>Herbal Allies</h2>
        <p><strong>Marshmallow root</strong> is a truly lunar plant. It has a somewhat sweet, nourishing flavor, and has a lubricating, repairing, and protective effect on the body and tissues. It grows in what would be considered lunar conditions, in damp, cool mashes, where there is abundant moisture. If one were to be suffering from inflammation, irritation, or dehydration, this lunar plant contains moistening mucilage, a gel that cools and lubricates the respiratory and digestive tract.</p>
        <p><strong>White willow bark</strong> has been regarded as a lunar plant since ancient times. Its dry, astringent qualities are constrictive, reducing swelling and excess moisture. This is an important antidote to lunar dampness, bogginess, and fluid build-up.</p>
        <p>White willow bark can be chewed to relieve toothache and general pain and is known to contain salicin, an ingredient in Aspirin. Willow bark also contains flavonoids that help with the reduction of fever and inflammation. It is a known cramp and pain reliever for the moon-cycle, which can be potent for moon-ruled Cancerians.</p>
        <p><strong>Mullein</strong> is traditionally a Saturnian plant that offers the medicine of antipathy to the damp, congested conditions that Cancer can suffer from. Its dry hairy leaves hint at its affinity for the cilia of the respiratory tract, that can become clogged with mucus in the phlegmatic constitution in illnesses that produce excess phlegm. Mullein tea and tinctures have been used to treat all manner of respiratory infections, including tuberculosis, asthma, and dry chronic coughs. It also contains soothing, mucilage ingredients that help make coughs more productive.</p>
        <h2>Esoteric Cancer</h2>
        <h3>&nbsp;The Three Decans of Cancer</h3>
        <p>Each of the twelve zodiac signs represents a thirty-degree slice of a 360-degree band of constellations, circling the earth. The thirty degrees of each sign can be further subdivided into three ten-degree decans or faces, each with its planetary sub-ruler placed around the zodiac in Chaldean order.<br>These faces can be used for timing magical rituals when seeking to evoke and harness the moon’s planetary power. In studying the Cancer personality, we can use the faces of the Crab to fine-tune the flavor and nuance of planets or points placed within these decanic degrees.</p>
        <h3>First Decan of Cancer: Venus</h3>
        <p>Degrees 0 through 9 of Cancer are ruled by Venus, amplifying the romantic and creative potential of the Cancer archetype for those with planets in the first decan. There may be a tendency to seek comfort and security in romantic relationships; with love and attraction taking on a soulful, healing, and spiritual importance to those with planets or points in this decan.</p>
        <h3>Second Decan of Cancer: Mercury</h3>
        <p>Degrees 10 through 19 of Cancer are ruled by Mercury. This may heighten and intensify the mental and intellectual activity of those born with planets or placements in this decan. In the degrees, we may see some of the more literary Cancers emerge. Their communication style may be soothing and comforting, which makes them inclined toward counselling or therapist work.</p>
        <h3>Third Decan of Cancer: The moon</h3>
        <p>Degrees 20 through 29 of Cancer are ruled by the cool and receptive moon. This is the lunar domicile, enlightening the psychic and intuitive abilities of those born with planets or placements in this decan. We may see spiritual advisors, clairvoyants, but also great nurturers and matriarch emerge from this potent face of Cancer, which is an auspicious placement for lunar magic rituals.</p>
        <h2>Cancer Tarot Cards</h2>
        <h3>Major Arcana: The Chariot</h3>
        <p>The Tarot card that correlates to Cancer is number 7: The Chariot. This card depicts a balanced and benevolent warrior, riding off on a journey or battle, with poise and calm. This is the card of the peaceful warrior, who is emotive, intuitive, but also a powerful protector and defender of the weak and vulnerable.</p>
        <p>This card appears when this archetype may need to be cultivated within us, or when we are about to embark on a new trip or project. The driver is depicted as harnessing and steering the horses of initiative, and receptivity. Upright, it is an encouraging card, that bodes well for acts of determination, courage, and emotional strength.</p>
        <p>The Chariot has echoes of the other four cardinal cards in the major arcana. It mirrors the love and emotional balance of the Lover’s card, the clear judgement of the Justice card, and also hints at all of these qualities combined in the Chariot helping us triumph over the material vices of the polar opposite, the Devil card.</p>
        <h3>Minor Arcana</h3>
        <p><strong>2, 3, and 4 of Cups</strong><br>In the Minor Arcana of the Tarot, the Suit of Cups is associated with the element of water. Here, we see the three decans of Cancer assigned to the 2,3, and 4 of Cups, cards associated with the beginning of an intuitive and relational cycle. These Cup cards help us focus on developing our receptive and reflective capacities, so that we may feel our way toward better self-understanding and emotional mastery.</p>
        <p><strong>2 of Cups: Venus in Cancer</strong><br>The 2 of Cups corresponds to the first decan or face of Cancer. It carries the affectionate and benevolent sub-signature of Venus and was referred to in the Book of Thoth as the card of “Love.”</p>
        <p>Depicting two partners raising their cups in love and celebration, this card often appears to herald a new partnership between lovers, friends, or business collaborators. It hints at the emotional support and reciprocation needed to foster emotional trust and intimacy, and can symbolize marriage or the inception of a new business.</p>
        <p>The “Love” card shows “the harmony of the male and the female: interpreted in the largest sense. It is perfect and placid harmony, radiating an intensity of joy and ecstasy…” (Book of Thoth)</p>
        <p><strong>3 of Cups: Mercury in Cancer</strong><br>The 3 of Cups corresponds to the second decan or face of Cancer. It carries the swift and communicative sub-signature of Mercury and was referred to in the Book of Thoth as the card of “Abundance.” This card depicts three friends, dancing in celebration and camaraderie. It is a very social and creative card, that hints at a new level of collaboration in a harmonious, yet dynamic group.</p>
        <p>The “Abundance” card depicts “the fulfillment of the Will of Love in abounding joy. It is the spiritual basis of fertility.” (Book of Thoth)</p>
        <p><strong>4 of Cups: Moon in Cancer</strong><br>The 4 of Cups card corresponds to the third decan or face of Cancer. It carries the intuitive and receptive sub-signature of the moon and was referred to in the Book of Thoth as the card of “Luxury.” The number four is a stable number that suggests a time of withdrawing.</p>
        <p>The figure is depicted turning their emotional awareness inward, in order to disconnect from the outer world to recharge before moving forward. It can hint at boredom and stagnancy that can come from feeling emotionally dull, or unmotivated.</p>
        <p>The “Luxury” card implies “a certain weakness, an abandonment to desire.” (Book of Thoth</p>
    </div>
</div>
</body>
</html>
