<%--
  Created by IntelliJ IDEA.
  User: elmirabajgulova
  Date: 31.10.2021
  Time: 00:20
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <meta name="viewport" content="with=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/styleHome.css">
    <link rel="stylesheet" href="css/styleZodiacSignsPages.css">
</head>
<body>
<section class="sub-header">
    <%@include file="/WEB-INF/top_nav.jsp" %>
    <h1>Capricorn</h1>

</section>
<h1>Capricorn</h1>
<div class="grid__content">
    <div class="editorial-article__feed">
        <h2>&nbsp;Capricorn&nbsp;Traits &amp; Overview</h2>
        <div class="zs-meta border-grey border-rad-4 grid-1c grid-sm-2c grid-lg-3c grid-c-gap-3 p-2 mb-3">
            <div class="meta-item"><span class="tag">Capricorn Dates: </span><span class="tag--bold white">December 21 – January 20</span></div>
            <div class="meta-item"><span class="tag">Symbol: </span><span class="tag--bold white">The Sea-Goat</span></div>
            <div class="meta-item"><span class="tag">Mode + Element: </span><span class="tag--bold white">Cardinal&nbsp;Earth</span></div>
            <div class="meta-item"><span class="tag">Ruling Planet: </span><span class="tag--bold white">Saturn</span></div>
            <div class="meta-item"><span class="tag">House:</span><span class="tag--bold white"> Tenth</span></div>
            <div class="meta-item"><span class="tag">Mantra: </span><span class="tag--bold white">I Use</span></div>
            <div class="meta-item"><span class="tag">Body Parts: </span><span class="tag--bold white">The Knees</span></div>
            <div class="meta-item"><span class="tag">Colors:</span><span class="tag--bold white"> Brown &amp; Khaki</span></div>
            <div class="meta-item"><span class="tag">Tarot Card: </span><span class="tag--bold white">The Devil</span></div>
        </div>
        <p>Capricorn, the tenth sign and mountain goat of the zodiac, is all about hard work. Those born under this sign are more than happy to put in a full day at the office, realizing that it will likely take a lot of those days to get to the top. That’s no problem, since Capricorns are both ambitious and determined: they will get there. Life is one big project for these folks, and they adapt to this by adopting a businesslike approach to most everything they do.</p>
        <p>Capricorns are practical as well, taking things one step at a time and being as realistic and pragmatic as possible. Those with a Capricorn zodiac sign are extremely dedicated to their goals, almost to the point of stubbornness. Those victories sure smell sweet, though, and that thought alone will keep Capricorns going.</p>
        <h2>Capricorn Symbolism + Myth</h2>
        <p>The stellar constellation of Capricorn represents the Sea-Goat, whose mythology extends back to the middle of the Bronze Age. The Babylonians called the Sea-Goat Ea, who was the protective god of water, knowledge, and creation. In Greek mythology, the Sea-Goat has other connections, one being the goat Amalthea who nursed baby Zeus after he escaped being eaten by his father, Cronos. In a later tale, Amalthea’s broken horn was transformed into the “cornucopia” full of earthly bounties.</p>
        <p>Capricorn is also associated with Pricus, the father of a race of intelligent and honorable Sea-Goats. Piscus tried to protect his children, who lost their ability to speak and think when they ventured onto dry land, by trying to turn back time to avoid this loss.</p>
        <p>He eventually had to surrender to losing all of his children to the wild and was given an immortal home in the heavens as the constellation of Capricorn. This lonely tale may be where some of the melancholy and sadness of the Capricorn archetype originated.</p>
        <h2>Capricorn Element, Mode, and Season</h2>
        <h3>Winter Solstice</h3>
        <p>In the western tropical zodiac, Capricorn season begins on December 21, commencing the Winter Solstice in the Northern Hemisphere. This is the time of year when the sun’s heat and light are at their lowest, with the night outweighing the day. From this point, the days slowly begin to lengthen toward the Spring Equinox, representing the fourth and last seasonal pivot of the year. Capricorn’s affinity for resourcefulness and preparedness is mirrored in the activities of the Winter, where we enter a hibernation and conservation mode.</p>
        <h3>Cardinal Mode</h3>
        <p>Capricorn is the last of the four cardinal signs of the zodiac, who all hold an elemental energy of initiation and leadership at the beginning of the four seasons. Capricorn season is the beginning of Winter, where the light and energy are at a premium. This definitive seasonal quality is the root of Capricorn’s strong cardinal authority and nature as an archetype.</p>
        <h3>Earth Element</h3>
        <p>Capricorn’s element is earth, the heaviest and most solid element, thought by ancient astrologers to be the densest form of matter. Earth represents the very structure that all of nature is built with, and upon, and without it, nothing could take a material form. Capricorn’s affinity for leadership, administration, and welding material power are all akin to the structure and tangibility of the earth element.</p>
        <p></p>
        <p></p>
        <h2>Capricorn Planetary Rulership</h2>
        <h3>Domicile of Saturn</h3>
        <p>In classical astrology, Saturn was assigned rulership of both Aquarius and Capricorn. Capricorn was thought to be the nocturnal/night home of Saturn, an ambitious and disciplined earth sign that allows Saturn to express and enact its most stern and authoritative functions. Among these are strong practical, productive, and organizational abilities.</p>
        <p>Those born with Saturn in Capricorn will likely find that many of these abilities come naturally and easily to them. Saturn in Capricorn folks typically have an innate sense of duty and responsibility that they apply to restructure and reorder their world. They are often born with a keen awareness of the adversity surrounding them and know, on a deep level, they were made to weather hard times.</p>
        <h3>Detriment of the moon</h3>
        <p>Capricorn is in polarity with the cardinal water sign Cancer. Ruled by the moon, Cancer is sensitive, protective, and emotionally nurturing. Being innately intuitive and comfortable with vulnerability, moon-ruled Cancer is a contrast to Saturn-ruled Capricorn, whose strong work ethic has them wired for public achievement and stern authority. Imagine the emotive moon in Capricorn’s dry, spartan, and serious world.</p>
        <p>The moon in Saturn’s sign would have to compensate for this “detriment”, being somewhat out of her element in this reserved environment. This may simply mean that natives born with this placement may tend to have protective barriers around their emotions and take a long while to open up and allow themselves to be vulnerable.</p>
        <p>This placement can have a Saturnian effect on the moods of these natives, making them prone to bouts of sadness and depression. They may also have to work through themes of cynicism if they have been emotionally wounded in the past, which will make it hard for them to trust again. It may take a long time for the moon in Capricorn folks to admit that they need emotional support, as the stoic Goat prides itself on independence and self-reliance.</p>
        <h3>Exaltation of Mars</h3>
        <p>Mars, the planet of drive, war, and combat has a specially exalted place in Capricorn. Here, the Mars power and propulsion blend uniquely well with Capricorn’s steady, single-minded work ethic.</p>
        <p>This placement can combine to produce great athletes, martial artists, or folks with strong tactical and strategic minds. They use their strength and endurance to work toward their goals in an orderly, cumulative way. This placement for Mars tempers its rash qualities, and stabilizes its energy, giving these natives great powers to endure and persevere.</p>
        <h3>Fall of Jupiter</h3>
        <p>Jupiter was said to be exalted in Cancer by classical astrologers, where he can uniquely and auspiciously express his greatest gifts of benevolence, knowledge, and expansion. When in the opposite sign of Capricorn, Jupiter was said to be in his fall, which may not pose as strong of an adaptive challenge as a detriment might, yet still puts the planetary force somewhat out of its comfort zone.</p>
        <p>Jupiter wants to open up opportunities and promote faith and optimism, but Capricorn, being a cool and dry earth sign, may be too cautious and reserved as an archetype to allow Jupiter’s energy to flow freely.</p>
        <p>This could present in these natives as a form of cautious optimism, where they are never able to fully trust their good fortune or the sense that the universe is operating on their side. However, Jupiter’s enthusiastic and ebullient qualities may shine through just the same and appear as either dark or dry in these natives as a way to survive the adversities they sometimes face.</p>
        <h2>Capricorn House Rulership</h2>
        <h3>The Tenth House</h3>
        <p>In the modern astrology system of the Twelve Letter Alphabet, each zodiac sign rules one of the twelve houses in the birth chart. This innovation was created by psychological astrologers to match sign affinities to related house topics. Capricorn was assigned the tenth house of public status and career, since Capricorn’s earthy and ambitious pursuits are aligned with the concerns of this house. Since Capricorn is ruled by the planet of time and patience, it invites an analytical Saturnian sub-signature to the tenth house.</p>
        <h3>The Twelfth House</h3>
        <p>In traditional astrology, Capricorn’s planetary ruler,Saturn, was said to find its “joy” in the twelfth house of solitude, confinement, and isolation in the birth chart. The twelfth house was also called the house of “bad spirit” by classical astrologers, meaning it was connected to anxieties and shadowy themes that cause us some degree of mental anguish. This is related to Saturn being the planet responsible for our greatest tests and trials that come about through feeling burdened with heavy responsibilities and concerns.</p>
        <p>As a result, Saturn can “joyfully” express its more limiting and uncomfortable offerings here. The good news about this placement in the birth chart is that it can be connected with a theme of overcoming one’s enemies, and though difficult, can give the native great powers of perseverance through life’s hardest passages in the end.</p>
        <h2>Capricorn Characteristics</h2>
        <h3>Personality</h3>
        <p>Capricorn’s personality traits are derived from its receptive, feminine, or yin qualities, making this sign oriented toward contemplation and engagement with inner awareness. Alive in both a Capricorn woman or Capricorn man, those born with the Sea-Goat as their rising, sun, or moon sign have a discipline, masterful, and determined energy in the core of their personality; an echo of the resilience and resourcefulness needed to survive the cold season of their birth.</p>
        <p>As a cardinal sign, Capricorn holds the qualities of being an achiever, a builder, and a climber, able to set and conquer the loftiest goals one step at a time. Those born with the sign of the Sea-Goat prominent in their charts are great at being determined, consistent, and reliable. They often over-deliver on their promises and take their honor and public reputation very seriously.</p>
        <h3>Strengths</h3>
        <p>Ruled by Saturn, the primary Capricorn strengths can be found in their perseverance, longevity, and focused self-mastery. Coolheaded and down to earth, they have strong powers of discernment. They are often good Saturnian judges of character and can be approached for pragmatic advice and a fair verdict.</p>
        <p>Ruled by Saturn, the Sea-Goat does not shy away from commitment, but rather requires it of their friends, business partners, and lovers before they can fully trust. As a result, your Sea-Goat friend may be one of your most loyal allies, unless of course, you cross them in a business deal.<br>Capricorns may not be seeking fame or glamour in the obvious sense, yet are known for their enduring beauty and classic elegance. Those born under the Sea-Goat are old souls who traditionally are understood to age in reverse. They usually begin life with the weight of the world on their shoulders that they gradually learn to let go of over the years. Humor is one of Capricorn’s most underrated strengths, which is an important source of their resiliency.</p>
        <p>Natives from this sign see the world with a pragmatic and sober eye, so have long ago made their peace with the shadows of mortality and human frailty. It is this shadow and frailty that they seek to laugh with, developing a dark, rueful humor to help them survive and endure.</p>
        <p>Capricorn has an instinct for surveying the peaks and valleys of life’s opportunities and tracks an efficient course to the top of whatever profession they pursue. While others may peak early, or flash in and out of the public eye with gimmicks and hot takes, Capricorn will stay the course and out lap their contemporaries by building a legacy.</p>
        <p>They often achieve fame and accolades later in life, coming into their own after years of dedication. Once they age, they become our wise Saturnian elders, with a twinkle in their eye.</p>
        <h3>Weaknesses</h3>
        <p>Some potential weaknesses in the Capricorn archetype are rooted in their great strengths. Though diligent and determined, they can succumb to being myopically focused on their goals, becoming stubborn and relentless. They may hold everyone else to the strong work ethic that drives them, not understanding that others have different rhythms, values, and needs.</p>
        <p>The Sea-Goat is known for its discerning and judicial nature, yet this can easily slip into being judgmental, and unforgiving of other’s mistakes, or life choices. Though Capricorn does have a mystical and intuitive side, they can also be traditionalists and may have a conservative streak that does not allow for flexibility in how they or others live their lives.</p>
        <p>The Sea-Goat is no doubt honorable and committed when in balance with themselves and their needs, however, if they are feeling insecure, they can default to a radical self-reliance that cuts people out of their lives if they fall short of what they promise. This may be an important self-care instinct that can protect the surprisingly sensitive Goat from being used, however, if this is done reactively too often, they may end up isolating themselves.</p>
        <p>Capricorn needs to let their walls down and allow themselves to be interdependent with others. These folks are known for their resourcefulness and business acumen, but if money becomes too important, they can become overly ambitious, materialistic, and even miserly.<br>They may have some trauma around lack, perhaps coming from humble upbringings, that tricks them into thinking they will never have enough resources to get them through the winter of life. This may or may not be true, but must be examined with the same realism that usually helps them stay grounded.</p>
        <p>Friends of the Sea-Goat need to be aware that their companion may hide pain or depression behind a mask of self-sufficiency and dry humor. Capricorns often have shame around reaching out for help, so it’s important to offer support in a way that is not disempowering in order to let them know you have their backs.</p>
        <p>Capricorn children will be well-nurtured if they are not saddled with too much responsibility and expectation at a tender age. Though they seem mature beyond their years, they still need their time to play and be carefree.</p>
        <p></p>
        <p></p>
        <h2>Capricorn Life Purpose and Career</h2>
        <h3>Mantra and Purpose</h3>
        <p>The voice of discipline, responsibility, and resourcefulness comes forward in the Capricorn mantra:&nbsp;<strong>I use.</strong>&nbsp;The Goat’s sense of purpose is all about rising to great heights and achieving material and self-mastery in life. With strong cardinal leadership skills, they will be fulfilled by building, organizing, and administering systems and communities that work hard toward a collective goal.</p>
        <p>Ruled by Saturn, the Sea-Goat is here to build a legacy and invests time, energy, and resources into constructing and upholding a great enduring work that may last the test of time and history. While others may have talents for envisioning, it’s Capricorn that can take these visions and harness them into a usable, material form.</p>
        <p>We all have Capricorn somewhere in our birth chart, so we can look to the house that the Sea-Goat rules to find the specific area of our life we approach in an authoritative, constructive, and disciplined way, or where we need to call in a Capricornian sensibility for material mastery.</p>
        <h3>Capricorn at Work</h3>
        <p>Capricorn’s cool and diligent nature makes them uniquely suited for professions where they are needed to organize and manage material and human resources. As a cardinal sign, they do need to take the lead in some capacity for their work to be challenging and fulfilling. They are disciplined and independent enough to be entrepreneurs or solo workers, but their discerning and judicial qualities lend themselves well to helping draw the latent potential out of people.</p>
        <p>Time conscious and efficient, Capricorns need to manage their schedule to some extent, so they may not enjoy subordinate roles for too long. For this reason, many under this sign build their own businesses, where they can call the shots and set new standards of excellence in their fields.<br>They naturally set their personal goals and hold themselves to the same high standard, so any work they take on, they do it with pride. It may be obvious at this point to state that this sign loves to work. Period. This is where you will usually find your local Sea-Goat, industriously chipping away at their duties.</p>
        <p>Administrative and organizational roles of all kinds are natural Capricorn domains. They make natural business managers, overseeing everything from construction, to manufacturing, and land development.</p>
        <p>With strong leadership skills and Saturnian tendencies, Capricorns often take roles in government and finance. They can be very active in law and politics, as leaders, officials, and judges. Banking, accounting, and economist roles are also classically Capricornian.</p>
        <p>Saturn, the ruler of Capricorn, has ties to the twelfth house of isolation, and institutions, which connect these natives for administrative roles in hospitals, schools, and prison facilities. The Capricornian archetype lends itself well to being principals, wardens, and heads of health and medical staff.</p>
        <p>The Sea-Goat does have a creative side, that can come out in many art and craft forms that are constructive and dimensional. Some examples are graphic designers, architects, woodworkers, and builders.</p>
        <p>These natives may have an innate sense of space and order, with a disciplined, technical mind. This could be expressed well in jobs as civic and industrial designers, and in various roles as city planners.<br>In their innately sensual earthiness and connection to their bodies, Capricorns have a side to them that would enjoy pursuing healing professions. They could make great massage practitioners and lifestyle consultants, and with a Saturnian affinity for bones, they may also enjoy being chiropractors and osteopaths.</p>
        <p>The Sea-Goat’s life of hard knocks and survival may mold them into great storytellers, comedians, and entertainers. They should not be overlooked as artists, as some of the greatest actors, singers, writers, and painters have Capricorn prominent in their birth charts.</p>
        <h2>Capricorn Compatibility</h2>
        <p>When it comes to exploring the overall compatibility in astrology, it’s important to consider many planetary elements other than the sun sign, as well as the rising sign and moon sign to tell the whole story. That being said, Capricorn natives will tend to blend best with water signs and earth signs; and may need to work harder on relationships with fire signs and air signs.</p>
        <h3>Fire signs</h3>
        <p>Capricorn, with their love for realism and grounding, may find the volatile and impulsive fire signs the trickiest to relate to.</p>
        <p>Though Capricorn’s cool and reserved nature may benefit from collaborating with fiery warmth and enthusiasm, Mars-ruled Aries, especially, may be too brash and headstrong to harmonize with Capricorn’s master plan. Both are cardinal signs, which might make them wrestle for leadership and control. They will, however, respect each other’s strength and independence, but may have to do so at a distance.</p>
        <p>Sagittarius and Capricorn are adjacent signs, meaning they share nothing modally or elementally in common. This pairing is like joining the guru with the president; they may collaborate on the same vision but will have very different roles and values. They each have a little something that the other needs, but will never admit it.</p>
        <p>Capricorn and Leo also have nothing elementally or modally in common, and so may have a hard time relating and connecting romantically long term. Leo may be the star, and Capricorn may be the talent manager. They appreciate each other’s different natures but may evolve into business colleagues in the end.</p>
        <h3>Air signs</h3>
        <p>Air signs are speedy and social, which is a great match in Capricorn’s business networking world, but Capricorn may find the air signs a bit too breezy and changeable to truly depend on.</p>
        <p>Gemini and Capricorn do not share much in common, with the Sea-Goat often taking the role of grounding and organizing Gemini’s frenetic energy. The two may tire of this dynamic after a while and will need to respect each other’s different rhythms to last long term.</p>
        <p>Libra and Capricorn can work well together, both being cardinal signs. Libra’s social and artistic world can interestingly overlap with Capricorn’s business circles. They may have a very busy public relationship, but eventually, Capricorn will need to withdraw to recharge in solitude. They may also have very different moods at different times that they would need to learn how to navigate.</p>
        <p>Capricorn and Aquarius could work, in that they share a Saturn rulership over both of their signs. This would connect them on a serious level, where they converse and debate intently together. Capricorn may be too much of a realist and traditionalist to appreciate and trust Aquarius abstract views, and they both may be too dry and reserved to let romantic sparks truly fly.</p>
        <h3>Water Signs</h3>
        <p>Water signs bring vulnerability and emotional intelligence to a relationship with serious and industrious Capricorn, which is naturally fruitful and complementary.</p>
        <p>Cancer is Capricorn’s polar opposite, bringing care and nurturing to Capricorn that they will sorely need. The two have an opposite’s attract connection that may either complete the whole picture or be too polarizing. Cancer enjoys creating a warm home, where Capricorn is often married to their work, so if they can blend each other’s strengths, they can help balance each other out.</p>
        <p>Pisces broadens Capricorn’s receptive capacities by bringing spiritual and philosophical awareness to their lives. This is a complementary relationship that reminds the Sea-Goat of their mystic hybrid nature. Capricorn brings structure, security, and support to dreamy Pisces, and Pisces helps Capricorn get back in touch with their soul. It’s a good match if Capricorn can forgive Pisces’ habit of losing track of time.</p>
        <p>Mars-ruledScorpio can bring sexual magnetism to a relationship with Capricorn, helping them open up to sensuality and exploration. This is a magnetic match, with both signs able to explore potent themes of power and mystery together. Capricorn is one of the few signs to truly “get” and appreciate Scorpio, as they are not intimidated by their deep and moody nature.</p>
        <h3>Earth signs</h3>
        <p>Earth signs, Taurus and Virgo, have the greatest elemental affinity with Capricorn, sharing themes of stability, practicality, and efficiency between them.</p>
        <p>Capricorn with Capricorn can meld together easily, working together to build an empire, and conquer the world, one step at a time. They also will enjoy being reclusive and private together. The only warning is that if they are too much alike, they may have power struggles or be too independent to make time for intimacy.</p>
        <p>Capricorn and Virgo together make a potentially strong match. They will appreciate each other’s grounded and earthy sensibilities and will enjoy laughter and offbeat humor together. Their lives and approaches mesh well, and they make natural companions.</p>
        <p>Capricorn and Taurus share many affinities and may especially connect over their enjoyment of fine food, wine, and sensual pleasures. Taurus draws the romantic lover out of cool Capricorn, and the Sea-Goat appreciates Taurus’ supportive, dependable nature. They are sure to have a lot of fun together, which Capricorn needs to stay balanced.</p>
        <h2>Capricorn Health</h2>
        <h3>Constitution</h3>
        <p>In classical astrological medicine, four temperaments were connected to four vital fluids and four essential constitution types. Being an earth sign, Capricorn is associated with the melancholic temperament, which was understood to be cold and dry.</p>
        <p>The melancholic temperament was thought to be connected to the spleen, which filters blood and supports immunity. The melancholic constitution was also considered to be connected to a metaphorical substance in the body that ancient physicians called “black bile.”</p>
        <p>This represented a tendency for the melancholic constitution to become cold and stagnant, where toxic substances were able to build up too much and not be adequately cleaned out. This lends itself to the medical astrology idea that Capricorn’s mood and constitution can become too chilled, blocked, and tense if it is not balanced by movement, circulation, and cleansing hydration.</p>
        <p>This constitution had another layer to it by this ancient medical system, and that comes from cold and dry Saturn’s rulership over the Sea-Goat’s sign. This was said to add another melancholic layer to Capricornian health as well, making this constitution doubly prone to depression, skin and connective tissue dryness, tension, and constriction.</p>
        <p>Though Capricorns tend to be sturdy, and often enjoy longevity, they shouldn’t take this for granted. They may be too tough for their own good and push themselves into exhaustion and imbalance.</p>
        <p>Similar to Virgo, Capricorn needs grounding nourishment, heart, and nerve protecting Omega 3’s, hydration, and relaxation routines to keep them in optimal health. Capricorn does have a disciplined side and may be very good about tending to their bodily routines, even if it is only to improve their productivity. Whatever works!</p>
        <h3>Body Parts</h3>
        <p>In classical astrological medicine, the entire zodiac was mapped out on the human body, with Capricorn ruling over the knees, skin, and connective tissue. Being under Saturn’s rule, all firm and bony structures of the body need to be fortified and supported with minerals and supplements.<br>Their bodies, in general, may be prone to stiffness, dehydration, and inflexibility, so these vulnerabilities need to be cared for with herbal and nutritional remedies. Sea-Goat natives may need to take preemptive measures to avoid developing porous bones and should protect their sensitive knees from injury</p>
        <h2>Herbal Allies</h2>
        <p><strong>Horsetail</strong>&nbsp;is a prime Saturnian plant, and is very rich in minerals and vitamins, including vitamins B, C, E, K, and also potassium, calcium, magnesium, iron, zinc, copper, and silica.</p>
        <p>As a result, it is excellent for building strong bones, teeth, hair, nails, and skin. Horsetail tea can help improve bone density in those suffering from osteoporosis, which Capricorn can be prone to. It also clears calcified kidney and bladder stones. Horsetail itself is so strong and fibrous, it was used to polish metal in ancient times.</p>
        <p><strong>Rosemary&nbsp;</strong>is a remedial remedy for cool Capricorn, with its solar properties offering the medicine of “antipathy” for the effects of being born in the winter. Rosemary is a prime solar plant, is moderately hot and dry, and grows in dry sunny environments that would be the opposite condition to Capricorn’s winter realm.</p>
        <p>Rosemary brings heat and warmth to the head, and its stimulating herbal fragrance helps to improve mental clarity and memory retention for hard-working Capricorns. Its aromatic oils can also be uplifting to the Sea-Goat’s often sad or pensive mood. Rosemary oil—when diluted in a light carrier oil—is excellent for massage, as its relaxing solar warmth is very soothing to aching Capricorn knees and joints.</p>
        <p><strong>St. John’s Wort&nbsp;</strong>is another remedial remedy for Capricorn, with its sunny yellow flowers coming into full bloom in the height of Summer. Its properties are known for helping sore and aching joints and muscles when it is made into a balm, and as a tea or tincture, it helps fight low mood and depression.</p>
        <h2>Esoteric Capricorn</h2>
        <h3>The Three Decans of Capricorn</h3>
        <p>Each of the twelve zodiac signs represents a thirty-degree slice of a 360-degree band of constellations circling the earth. The thirty degrees of each sign can be further subdivided into three ten-degree decans, or faces, each with its own planetary sub-ruler placed around the zodiac in Chaldean order.</p>
        <p>These decans can be used for timing magical rituals when seeking to evoke and harness Saturn’s planetary power. In studying the Capricorn personality, we can use the faces of the Sea-Goat to fine-tune the flavor and nuance of planets or points placed within these decanic degrees.</p>
        <h3>First Decan of Capricorn: Jupiter</h3>
        <p>Degrees 0 through 9 of Capricorn are ruled by the Jupiter,making those with planets in the first decan potentially more jovial and friendly than what we might expect of Saturn’s serious earth sign. There may be an extra signature of optimism and luck for those born with planets or points in this decan, with a strong part of their character presenting surprisingly buoyant Jupiterian qualities. They may also be more spiritually inclined than the other faces of the Goat.</p>
        <h3>Second Decan of&nbsp; Capricorn: Mars</h3>
        <p>Degrees 10 through 19 of Capricorn are ruled by Mars. This is the exaltation of Mars, where the planet of war and conquest is powerfully placed. Those born with placements here may have an extra layer of drive and fortitude at their disposal. Here, the powers of endurance and drive are heightened to more ambitious proportions than seen in the other decans.</p>
        <h3>Third Decan of Capricorn: The sun</h3>
        <p>Degrees 20 through 29 of Capricorn are ruled by the warm and assured sun. This brings a heightened solar and confident quality to the ego expression of those born with planets or points in this decan. Here, we see the more social Capricorns that have strong leadership and management skills. They may also be among the more performative and fame-seeking Sea-Goats.</p>
        <h2>Capricorn Tarot Cards</h2>
        <h3>Major Arcana: The Devil</h3>
        <p>The Tarot card that correlates to Capricorn is number 15: The Devil. This symbolism has its roots in Capricorn’s esoteric past, where goats were used as ritual sacrifices to atone for human sins before the gods.</p>
        <p>As the goat’s magical association became misunderstood over the years, Capricorn became associated with darkness and evil, but unfairly so. The more nuanced connection the goat has to our shadow or dark side is found in our human tendency to fall into vices, indulgences, and materialism, where we lose our freedom and become spiritually enslaved.</p>
        <p>The Devil card appears to remind us of this tendency, so that we may check in on what we have become attached to in an imbalanced way. This card draws awareness to what is in our shadow that is controlling our habits and perceptions. Sometimes we think we have this under control, but we need to be honest, courageous, and dig deeper to heal what has been neglected.</p>
        <h3>Minor Arcana</h3>
        <p><strong>2, 3, and 4 of Pentacles</strong><br>In the Minor Arcana of the Tarot, the Suit of Pentacles, also known as Coins or Disks, is associated with the element of earth. Here, we see the three decans of Capricorn assigned to the 2,3, and 4 of Pentacles, cards associated with the beginning material cycle. These Pentacle cards help us focus on developing and attaining our earthly needs in tangible forms of health, wealth, and creativity.</p>
        <p><strong>2 of Pentacles: Jupiter in Capricorn&nbsp;</strong><br>The 2 of Pentacles corresponds to the first decan or face of Capricorn. It carries the buoyant sub-signature of Jupiter and was referred to in the Book of Thoth as the card of “Change.”</p>
        <p>This card depicts an infinity symbol, as the figure balances two coins. This hints to discovering that perpetual resources can be grown and generated from skillfully applying the seeds of wealth that we have. The juggler also reminds us to balance our priorities and values when deciding where to invest our resources and awareness.</p>
        <p>The “Change” card represents “the harmonious interplay of the four elements in constant movement” and that the card is “the picture of the complete manifested universe, in respect of its dynamics…” (Book of Thoth)</p>
        <p><strong>3 of Pentacles: Mars in Capricorn</strong><br>The 3 of Pentacles corresponds to the second decan or face of Capricorn. It carries the potent and driven sub-signature of Mars and was referred to in the Book of Thoth as the card of “Work.” This card depicts a scene where one is beginning to implement new plans, skills, and resources. There is also a collaborative element in this card, which is depicted by the figures, reminding us that this is integral to us achieving our goals.</p>
        <p>The “Work” card depicts “the material establishment of the idea of the universe, the determination of its basic form” and shows Mars’ drive harnessed in the way “his energy is constructive, like that of the builder or engineer…” (Book of Thoth)</p>
        <p><strong>4 of Pentacles: Sun in Capricorn</strong><br>The 4 of Pentacles corresponds to the third decan or face of Capricorn. It carries the radiant sub signature of the sun and was referred to in the Book of Thoth as the card of “Power.” The number 4 is a stable number that represents consolidation but warns of stagnancy. Currency needs to keep flowing to keep generating, but the figure in the card is starting to get attached and is beginning to contemplate not letting his growing resources go.</p>
        <p>This card helps us examine our relationship with materiality and guides us into the balance between not holding too tightly to wealth, but at the same time, not spending it recklessly.</p>
        <p>The “Power” card depicts the “generating idea… exhibited in its full material sense.” (Book of Thoth)</p>
    </div>
</div>

</body>
</html>
