<%--
  Created by IntelliJ IDEA.
  User: elmirabajgulova
  Date: 31.10.2021
  Time: 00:20
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <meta name="viewport" content="with=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/styleHome.css">
    <link rel="stylesheet" href="css/styleZodiacSignsPages.css">
</head>
<body>
<section class="sub-header">
    <%@include file="/WEB-INF/top_nav.jsp" %>
    <h1>Gemini</h1>

</section>
<h1>Gemini</h1>
<div class="grid__content">
    <div class="editorial-article__feed">
        <h2>Gemini Traits &amp; Overview</h2>
        <div class="zs-meta border-grey border-rad-4 grid-1c grid-sm-2c grid-lg-3c grid-c-gap-3 p-2 mb-3">
            <div class="meta-item"><span class="tag">Gemini Dates: </span> <span class="tag--bold white">May 22 – June 21</span></div>
            <div class="meta-item"><span class="tag">Symbol: </span> <span class="tag--bold white">The Twins</span></div>
            <div class="meta-item"><span class="tag">Mode + Element: </span> <span class="tag--bold white">Mutable Air</span></div>
            <div class="meta-item"><span class="tag">Ruling Planet: </span> <span class="tag--bold white">Mercury</span></div>
            <div class="meta-item"><span class="tag">House:</span> <span class="tag--bold white"> Third</span></div>
            <div class="meta-item"><span class="tag">Mantra: </span> <span class="tag--bold white">I Think</span></div>
            <div class="meta-item"><span class="tag">Body Parts: </span> <span class="tag--bold white">Arms, Hands, &amp; Lungs</span></div>
            <div class="meta-item"><span class="tag">Colors:</span> <span class="tag--bold white"> Yellow &amp; Blue</span></div>
            <div class="meta-item"><span class="tag">Tarot Card: </span> <span class="tag--bold white">The Lovers</span></div>
        </div>
        <p>Gemini is the third sign of the zodiac, and those born under this sign will be quick to tell you all about it. That’s because they love to talk! It’s not just idle chatter with these folks, either. The driving force behind a Gemini zodiac sign’s conversation is their mind. Ruling the third house, the Gemini-born are intellectually inclined, forever probing people and places in search of information.</p>
        <p>The more information a Gemini collects, the better. Sharing that information later on with those they love is also a lot of fun, for Geminis are supremely interested in developing their relationships. Dalliances with those of this astrology sign are always enjoyable, since Geminis are bright, quick-witted, and the proverbial life of the party. Even though their intellectual minds can rationalize forever and a day, Geminis also have a surplus of imagination waiting to be tapped. Can a Gemini be boring? Never!</p>
        <h2>Gemini Symbolism + Myth</h2>
        <p>The Gemini zodiac symbol of the Twins is based on the half brothers Castor and Pollux from Greek mythology. These legendary brothers, also known as the Dioscuri, were the children of Leda, who was seduced by Zeus in the form of a swan. Leda laid two eggs as a result of this union, and Castor and Pollux were said to have hatched from each of these along with their twin sisters, Helen and Clytemnestra.</p>
        <p>Castor and Pollux are present in many Greek and Roman stories and were known for their mastery of horses. The Dioscuri bonded eternally, with Pollux; a half-god as the progeny of Zeus, sharing his immortality with Castor. The two were then placed in the heavens as the enduring Gemini-Twins constellation, immortalizing the myth that adds to the magical and mysterious duality of this sign’s archetype.</p>
        <h2>Gemini Element, Mode, and Season</h2>
        <p>In the western tropical zodiac, Gemini season begins on May 22, commencing at the end of spring in the Northern Hemisphere. It’s a time of year when the days are getting longer toward the summer solstice, where the proportion of daylight outweighs the duration of the night. There is a feeling of change in the air as the spring season heats up, and the hints of the oncoming hot, active summer season are beginning to take hold of the weather.</p>
        <h3>Mutable Mode</h3>
        <p>Gemini is the first of the four mutable signs of the zodiac, who all hold an elemental energy of change and adaptation at the transitional end of the four seasons. Gemini’s airy and mutable presence appears to clear the stage for the next seasonal performance and helps describe this sign’s restless, change-seeking, and curious role in the zodiac.</p>
        <h3>Air Element</h3>
        <p>Gemini’s element is air, a light and dispersive element thought by ancient astrologers to be an expression of matter that represents formlessness and dissolution. The Twins’ affinity for gathering information, making social connections, and exploring the world with childlike curiosity—and at times mischief—are all activities akin to the active, flowing air element.<br><br></p>
        <p></p>
        <h2>Gemini Planetary Rulership</h2>
        <h3>Domicile of Mercury</h3>
        <p>In classical astrology, Mercury was assigned rulership of both Gemini and Virgo. Gemini was thought to be the diurnal/day home of Mercury, an adaptive air sign that allows Mercury to be as fluid, curious, and analytical as it likes to be when placed there. After the moon, Mercury is the fastest planet in our solar system and goes retrograde most often, giving it the reputation for being erratic, changeable, and unpredictable.</p>
        <p>Those born with Mercury in Gemini may be known for their mental restlessness, swift intellect, and wit. This placement often bestows the native with the ability to learn quickly and assimilate large volumes of information easily. When it comes to Mercurial matters in life, those born with Mercury in its domicile seem to have an advantage when it comes to adaptability and communications and language in general.</p>
        <h3>Detriment of Jupiter</h3>
        <p>Gemini is in polarity to the mutable fire sign Sagittarius. Ruled by Mercury, Gemini loves to analyze, preferring to focus on gathering small, fascinating details, sometimes using mischief to tease, prod, and disrupt. Sagittarius, however, is ruled by Jupiter and likes to affirm, expand, and explore universal truths.</p>
        <p>As a result, Jupiter and its expansive ways are traditionally thought to be in detriment or at a disadvantage when placed opposite from its home in Gemini’s detail-focused world. It’s a placement that the planet of benevolence and belief would have to compensate for to be in, finding creative ways to open big-picture opportunities without getting lost in the minutiae.</p>
        <p>This combination could also present Jupiter’s energy of abundance being put into overdrive, by wanting to endlessly collect details and facts, as though there could never be enough. Those born with Jupiter in Gemini may at times feel challenged to hold a perception of multiplicity in balance with a sense of wholeness.</p>
        <h2>Gemini House Rulership</h2>
        <h3>The Third House</h3>
        <p>In the modern astrology system of the Twelve Letter Alphabet, each zodiac sign rules one of the twelve houses in the birth chart. This innovation was created by psychological astrologers to match sign affinities to related house topics.</p>
        <p>Gemini was assigned the third house of short-distance travel, communication, and siblings, since it’s restless, changeable, and curious nature has an affinity for these topics. Since Gemini is ruled by Mercury, this modern astrology system invites a curious and lively sub-signature to the significance of the third house.</p>
        <h3>The First House</h3>
        <p>In classical astrology, Gemini’s planetary ruler, Mercury, was said to find its “joy” in the first house of self and identity in the birth chart. Associated with our bodies and sense of purpose, this house symbolizes a merging of spirit and matter to form a unique being in the world.</p>
        <p>In traditional astrology, the degree of the rising sign was found inside the first whole sign house, dividing it into a portion that was above the horizon, and a portion that was below it at the moment of our birth.</p>
        <p>This is connected to the Hermetic alchemical axiom “as above, so below,” a phenomenon that is observed and practiced in the magical arts. Magic and its mysteries are given to us by the god Hermes, who is associated with Mercury, making it able to wield special potency as a bridge between the heavens and earth from the first house.</p>
        <h2>Gemini Characteristics</h2>
        <h3>Personality</h3>
        <p>Gemini’s archetypal traits are derived from its active, masculine, or yang qualities, making this sign oriented toward assertive engagement with the outer world. Alive in both a Gemini woman&nbsp;or Gemini man, those born with the Twins as their rising, sun, or moon sign have a curious energy in their core personality, like swift, adaptive Mercury within themselves.</p>
        <p>As a mutable sign, Gemini holds the power to be a change-maker, giving those with prominent Gemini in their charts a natural affinity for adaptation, exploring ideas, languages, and information, as well as socializing and communicating to form new pathways of awareness. Natives from this sign can be thought of as the “pollinators” of the zodiac, as they like to swiftly graze from person to person or topic to topic to weave together endless new connections.</p>
        <h3>Strengths</h3>
        <p>The primary strength of the sign of the Twins is their intelligence and keen, articulate communication skills. Being born with a curious and playful disposition, these folks usually find it easy to feel engaged with the world around them. Being influenced by Mercury’s swift and analytical nature, they rarely succumb to boredom and are usually able to propel themselves outward in life with an insatiable zeal for discovering new treasures of information.</p>
        <p>The Gemini native has a unique “shape-shifting” ability, as the Twins’ symbolic duality hints at this sign’s affinity for adaptability in utilizing their multidimensional talents. They are able to blend into any environment easily, taking on the customs of local culture and language.</p>
        <p>Folks born under the sign of the Twins tend to be fun-loving, social, and lighthearted. They excel at connecting people to the right people, so that resources, skills, and information can be disseminated in their communities effectively. A Gemini may have you sized up immediately, with a keen instinct for what buttons to push when trying to elicit a reaction from you. With this skill, this sign reminds us that life is a play and that we shouldn’t take ourselves too seriously.</p>
        <h3>Weaknesses</h3>
        <p>Some sources of weakness or potential blind spots for Gemini are rooted in their great strengths. These folks are known for their facile mind and intelligence, but this can lead them into a tendency to be overly intellectual. They may lean too much on encyclopedic knowledge and need to learn how to process, assimilate, and apply this information in a tangible, embodied, and useful way. With keen, curious minds, they may have a short attention span, wanting to dance on the shiny surface of discovery, rather than committing to learning one subject with depth.</p>
        <p>Being a mutable air sign, shape-shifting and change feel natural for them, but it may leave others with an uncanny feeling that they never know who the Gemini native really is. This can give this sign the reputation for being non-committal, flaky, or even untrustworthy. These folks are typically fun-loving, lighthearted, and sociable, but this can lead them to be emotionally evasive, using humor to distract or deflect from their deeper feelings.<br>The Mercurial tendencies of these folks to be social connectors can become imbalanced if the native is not caring for themselves, causing them to feel spun-out, anxious, spread thin, and devitalized. Gemini’s witty and mischievous talent for button-pushing can become annoying, relentless, and even cruel if not measured with a healthy sense of social boundaries, respect, and compassion.</p>
        <p>Children born under this sign will be nurtured and well-resourced if they are guided to breathe deeply, have patience, and concentrate on one task at a time as much as they can, before dashing off to the next attraction.<br></p>
        <p></p>
        <h2>Gemini Life Purpose and Career</h2>
        <h3>Gemini Mantra and Purpose</h3>
        <p>The clever voice of curiosity, inventiveness, and thirst for knowledge comes forward in the Gemini mantra: <strong>I think.</strong> This mantra could even be extended into <strong>“I think, therefore, I am,”</strong> highlighting this sign’s sense of purpose being bent toward discovery and expanding their mental awareness.</p>
        <p>Mercury is named for the messenger god that ruled over currency flow, trade, and merchants, so Gemini’s purpose is often tied to expediting communications and democratizing access to information and resources. Those with the archetype of the Twins prominent in their birth charts will gain enormous satisfaction when being able to move freely, with many active outlets for their restless nature. Naturally talkative, these folks thrive in conversation and may be great teachers or lecturers, with endless sources of information to draw from.</p>
        <h3>Gemini at Work</h3>
        <p>Gemini’s keen mind and curiosity make them uniquely suited for professions where they are called on to sort, analyze, and perform multifaceted functions. Their careers need to be mentally stimulating enough to occupy their kinetic intelligence and keep them busy enough to channel their restless energies. This sign’s wit and sociability will likely be their strong suit, making jobs where they can communicate, teach, and facilitate understanding between people the best. This could manifest in many professions, especially those where the analysis and translation of details is a key feature.</p>
        <p>Like all the air signs, Gemini needs novelty, activity, movement, and space, so will not be content for long in the same location, unless of course, that location is a library full of information to study and absorb! Mercury, and the signs it rules are connected to transportation, so Gemini jobs may involve travel and operating vehicles that get us from point A to point B.<br>The Twins have the opposite problem that most people have, in that they rarely get caught in a rut and need to be motivated. If anything, their workweek needs to have some structure, routine, and downtime scheduled in it to remind these swift-footed folks to ground and recharge.<br>Since Gemini is ruled by Mercury, the planet of language and communication, a natural vocational fit could be found in language translation. With a strong likelihood that the Gemini native is multi-lingual naturally, they would have great satisfaction in facilitating understanding. Other versions of this talent could also be fulfilled in studying linguistics, as well as speech therapy.</p>
        <p>Writing in all its forms is a natural fit for the Twins, as authors, journalists, and playwrights. They also delight in refining manuscripts, making editorial and proofreading work another natural fit.</p>
        <p>Geminis often have a keen interest in communications technology and can be found producing many forms of media, like film, television, and online news platforms. Mercurial folks are innately social and entertaining, which draws them to organize and even perform at artistic events themselves.<br>Chances are, your local bookstore is owned by a Gemini, who delights in sourcing and distributing the latest publications. It may even be a way to fulfill a personal addiction by being surrounded by so many books! Publishing books and magazines is another form this interest could take as well.</p>
        <p>Since natives from this sign are great multi-taskers, they may enjoy being a receptionist for a large firm by keeping the schedule straight, taking messages, and connecting incoming phone calls efficiently. Another similar version of this role could be as a personal assistant to a prominent person. Folks from this sign will know how to prioritize and source what is needed by being able to commit much to memory on the fly.</p>
        <p>Motion and speed are thrilling for Gemini natives, who may make excellent bike couriers or delivery persons. They will also likely excel at being friendly and chatty bus or taxi drivers, or even pilots, and will take pride in finding the fastest routes for any journey while entertaining you along the way.</p>
        <p>Lastly, being a “jack-of-all-trades” is often a theme in the lives of folks from the sign, so it wouldn’t be surprising to learn that they aspire to follow many of the vocations on the list, perhaps even a few at a time!</p>
        <h2>Gemini Compatibility</h2>
        <p>In astrology, when it comes to compatibility, it’s important to take more than the sun sign into consideration, as other planetary cross-connections are key in telling the whole story in all kinds of relationships. That being said, Gemini natives will tend to blend best with air signs and fire signs; and may need to work harder on relationships with water signs and earth signs.</p>
        <h3>Fire signs</h3>
        <p>Gemini will typically find a complementary connection with fire signs, as they will understand each other’s active, spontaneous natures. Air feeds fire, stoking it to grow and become more alive, so impulsive Aries will likely appreciate Gemini’s busy and mobile energy.</p>
        <p>Leo and Gemini will make a fun-loving, sociable pair, however, Leo may want more individual attention from endlessly curious Gemini than they can give at times.</p>
        <p>The sign of the Twins brings playfulness, curiosity, and mischief to Sagittarius’ adventurous life, and the two can have a complimentary or polarizing relationship. Where Sagittarius and Gemini may clash is in exchanges between Gemini’s button-pushing tendencies, and Sagittarius’ brutal honesty. The two may egg each other on and will need to learn when enough is enough.</p>
        <h3>Air signs</h3>
        <p>Air signs are a natural fit for Gemini, as they share the same elemental expression. Venus-ruled Libra brings balance, beauty, and sociability to Gemini’s stimulating, interconnected world.</p>
        <p>Aquariusand Gemini will enjoy conversing endlessly, sharing ideas in a harmonious, although largely intellectual relationship. Aquarius’ contrarian nature may come to the surface, however, to test the validity and depth of Gemini’s novel claims.</p>
        <p>Gemini with Gemini could be fun, with the two relating easily to the other’s curious approach toward life. They may not be able to stay put together long enough to bond in a consistent manner, but this may suit their free-spirited and playful natures just fine in the end.</p>
        <h3>Water signs</h3>
        <p>Water signs bring vulnerability and emotional intelligence to help this airy and active sign to tap into their deeper wells of feeling.</p>
        <p>Cancer will be very good at caring for Gemini, which they will love, but Cancer may prefer to keep a nurturing home base while Gemini is busy connecting socially and multitasking.</p>
        <p>Pisces broadens the Twins’ receptive capacities by bringing spiritual and philosophical awareness to their lives. Pisces, however, may be too private and sensitive to endure Gemini’s hyperactive, button-pushing tendencies, and may retreat the more Gemini prods.</p>
        <p>Mars-ruled Scorpio can bring sexual magnetism to a relationship with Gemini, but the two may share very little in common in the end. Scorpio’s jealous tendencies may be triggered by Gemini’s evasive and non-committal nature, making this is a potentially volatile match.</p>
        <h3>Earth signs</h3>
        <p>Though earth signs can potentially stabilize and ground Gemini’s dispersive energies, they may be the hardest for those born under the sign of the Twins to relate to. Capricorn, the authoritative cardinal earth sign, will be a pragmatic partner for Gemini to depend on but would need Gemini to be consistent and serious to earn their trust.</p>
        <p>Taurus, although dependable and loving, may be a bit too stubborn and rooted to roll with Gemini’s ever-adapting plans.</p>
        <p>Virgo and Gemini can make a surprisingly good, if unlikely pair, both bonded by a shared Mercury rulership. Both signs, however, are prone to nervousness and anxiety, that the other will tend to exacerbate. Virgo needs their environment orderly to help calm their nerves, while Gemini may want to change their environment on impulse to channel their nervous energy, creating tension for both parties involved.</p>
        <h2>Gemini Health</h2>
        <h3>Constitution</h3>
        <p>In classical medical astrology, there were four temperaments that were connected to four vital fluids and four essential constitution types. As an air sign, Gemini is associated with the sanguine temperament, which was thought to be hot and moist, and connected to the production of blood.<br>The sanguine constitution was considered to be naturally healthy and resilient, being connected to the youthful phase of life, and the spring season. Sanguine folks typically have a cheery disposition, lean body shapes, and are naturally energetic. Apart from imbalances related to restlessness and anxiety, this constitution type may not experience many health challenges until their later years. At this time, issues related to blood pressure, or blood stagnation may arise when the naturally high sanguine metabolism starts to slow down.</p>
        <h3>Body Parts</h3>
        <p>In astrological medicine, the entire zodiac was mapped out on the human body, with symmetrical, dual Gemini ruling over the shoulders, arms, and hands. This connects the Gemini archetype to their dexterous and facile natures. This area of the body is emphasized as being uniquely mobile and able, but also sensitive to overwork and injury. Internally, Gemini rules over the lungs, another dual, symmetrical system that interestingly enough receives and expels air in our vital breathing process.</p>
        <p>Those with the sign of the Twins prominent in their birth charts will need to care for their lung health by protecting themselves from lung infections and irritations. A focus on deep breathing to stay calm will be a huge asset to them, as Mercury’s signs tend to be prone to nervousness and anxiety. This nervousness can lead to digestive upsets, so eating vegetables like carrots, parsley, and fennel will promote gut health and digestive elimination.</p>
        <h2>Herbal Allies</h2>
        <p><strong>Lavender</strong>&nbsp;is a prime Gemini herbal ally. It grows in warm, dry environments and is itself a dry plant, which can help balance any excess moisture in the sanguine constitution. Its soothing aromatic fragrance is calming, and its oils are used in aromatherapy to cure this sign’s anxiety and relieve cramping and tension. It has an opening and clearing effect on the body, warming the head, calming fears and worries, and encouraging sleep.</p>
        <p><strong>Fennel</strong>&nbsp;is related to carrots and its stalks and seeds are usually used for their carminative, digestive support and gas clearing qualities. Fennel bears a sweet aromatic fragrance and when cooked with other foods, it helps to make them more digestible. Its fine green stalks resemble the bronchioles of the lungs and branches of the nervous system. This morphological clue lets us know that it is helpful to clear congestion, blockages, and stagnation in the breathing passages of this sign’s sensitive lungs.</p>
        <p><strong>Parsley</strong>&nbsp;is another fine green Mercury plant whose delicate branching leaves resemble the interconnectivity of the body. Parsley is thought to be moderately hot and dry, warming up cold, boggy tissue conditions. It also warms the stomach, liver, and spleen, and is a known diuretic, meaning it helps promote urination to clear water retention. It is also carminative, helping to clear digestive bloating and gas in the anxious Gemini digestive system.</p>
        <h2>Esoteric Gemini</h2>
        <h3>The Three Decans of Gemini</h3>
        <p>Each of the twelve zodiac signs represents a thirty-degree slice of a 360-degree band of constellations, circling the earth. The thirty degrees of each sign can be further subdivided into three ten-degree decans, or faces, each with its own planetary sub-ruler placed around the zodiac in Chaldean order.</p>
        <p>These decans can be used for timing magical rituals when seeking to evoke and harness Mercury’s planetary power. In studying the Gemini personality, we can use the faces of Gemini to fine-tune the flavor and nuance of planets or points placed within these decanic degrees.</p>
        <h3>First Decan of Gemini: Jupiter</h3>
        <p>Degrees 0 through 9 of Gemini are ruled by Jupiter. This is the “detriment” of the benevolent guru planet, making those with planets in the first decan very expansive and creative in their language use, but also highlights some potential struggles with intellectual focus and discipline.</p>
        <p>Personality-wise, the first decan of Gemini can be more analytical and inclined toward gathering and sharing information than the other faces of Gemini. This makes them potentially great storytellers and teachers, but can also amplify their tendency to be overly focused on accumulating information and knowledge. This tendency may shine best in literary and lecturing work, where the endless stream of information can be channeled.</p>
        <h3>Second Decan of Gemini: Mars</h3>
        <p>Degrees 10 through 19 of Gemini are ruled by Mars, making those born with planets here more inclined toward social impulsivity and confrontation. This is where we may see the more disruptive and antagonizing side of the Gemini nature present, where their great knowledge and intelligence is used to goad others into debates. It can even simply be expressed as a way to keep the Gemini mischievously amused when misdirected. Those born with prominent planets or points in this decan may need to find healthy ways to channel their especially active and restless natures.</p>
        <h3>Third Decan of Gemini: Sun</h3>
        <p>Degrees 20 through 29 of Gemini are ruled by the sun, the star of vitality, radiance, and confidence. Here, the sun’s influence potentially warms up and amplifies the Twins’ naturally playful, active, and sociable nature. Those with prominent planets or points in the third decan of Gemini may be more publicly visible, with natural gifts for building and leading their community.</p>
        <p>Where the first decan of Gemini may be truth-seeking, and the second may be more competitive, the third decan of Gemini may be more inclined to take the spotlight, as an entertainer or public speaker.</p>
        <h2>Gemini Tarot Cards</h2>
        <h3>Major Arcana: The Lovers</h3>
        <p>The Tarot card that correlates to Gemini is number 6: The Lovers. Showing a pair of people in partnership, or connecting in love and attraction, this card carries echoes of the Twins’ sense of joined purpose and duality.<br>The Lovers card appears to help us examine the choices we are making, as they relate to holding a sense of self, and the other, in harmony. We may be weighing the pros and cons of collaboration, with our sense of autonomy and independence. The Lovers card reminds us of the interdependent nature of life, and the relational facet that is alive in us all.</p>
        <h3>Minor Arcana</h3>
        <p><strong>8, 9, and 10 of Swords</strong><br>In the Minor Arcana of the Tarot, the Suit of Swords is associated with the element of air. Here, we see the three decans of Gemini assigned to the 8, 9, and 10 of Swords cards, associated with the management of intelligence and rational, discerning thought. These cards depict an important passage when working to harness the power of the mind, by developing mastery with a keen sense of perception.</p>
        <p><strong>8 of Swords: Jupiter in Gemini</strong><br>The 8 of Swords corresponds to the first decan, or face of Gemini. It carries the sub-signature of Jupiter and was referred to in the Book of Thoth as the card of “Interference.” This card appears when we are experiencing a hindrance or blockage in our thought processes. We may feel hemmed in or nailed down and mentally immobilized by theories and constructs that “interfere” with our ability to see the issue clearly.</p>
        <p>The “Interference” card highlights a “lack of persistence in matters of the intellect and the will constantly being thwarted by accidental interference.” (Book of Thoth)</p>
        <p><strong>9 of Swords: Mars in Gemini</strong><br>The 9 of Swords corresponds to the second decan, or face of Gemini. It carries the confrontational sub-signature of Mars and was referred to in the Book of Thoth as the card of “Cruelty.” This card appears when we are facing fears and mental anguish, or are dealing with the effects of inflicting or receiving verbal wounds.</p>
        <p>The “Cruelty” card symbolizes that “consciousness has fallen into a realm unenlightened by reason… the world of the unconscious, primitive instincts.” (Book of Thoth)</p>
        <p><strong>10 of Swords: Sun in Gemini</strong><br>The 10 of Swords corresponds to the third decan, or face of Gemini. It carries the sub signature of the sun and was referred to in the Book of Thoth as the card of “Ruin.” This card appears when some process or work has come to an irreversible end. It is a reminder of the disconnect and loss that can occur when we become too aloof and remote from our emotional dimensions. By not connecting to our intuition, we may have overcommitted our energies, and are now crashing under the weight of being mentally overextended.</p>
        <p>The “Ruin” card depicts the results of “reason divorced from reality” and is potentially “the ruin of the intellect, and even of all mental and moral qualities.” (Book of Thoth)</p>
    </div>
</div>

</body>
</html>
