<%--
  Created by IntelliJ IDEA.
  User: elmirabajgulova
  Date: 31.10.2021
  Time: 00:20
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <meta name="viewport" content="with=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/styleHome.css">
    <link rel="stylesheet" href="css/styleZodiacSignsPages.css">
</head>
<body>
<%@include file="/WEB-INF/top_nav.jsp" %>
<h1>Libra</h1>
<div class="grid__content">
    <div class="editorial-article__feed">
        <h2>Libra Traits &amp; Overview</h2>
        <div class="zs-meta border-grey border-rad-4 grid-1c grid-sm-2c grid-lg-3c grid-c-gap-3 p-2 mb-3">
            <div class="meta-item"><span class="tag">Libra Dates: </span><span class="tag--bold white">September 23 – October 22</span></div>
            <div class="meta-item"><span class="tag">Symbol: </span><span class="tag--bold white">The Scales</span></div>
            <div class="meta-item"><span class="tag">Mode + Element: </span><span class="tag--bold white">Cardinal Air</span></div>
            <div class="meta-item"><span class="tag">Ruling Planet: </span><span class="tag--bold white">Venus</span></div>
            <div class="meta-item"><span class="tag">House:</span><span class="tag--bold white"> Seventh</span></div>
            <div class="meta-item"><span class="tag">Mantra: </span><span class="tag--bold white">I Relate</span></div>
            <div class="meta-item"><span class="tag">Body Parts: </span><span class="tag--bold white">Lower Back &amp; Kidneys</span></div>
            <div class="meta-item"><span class="tag">Colors:</span><span class="tag--bold white"> Ivory, Pink, &amp; Light Blue</span></div>
            <div class="meta-item"><span class="tag">Tarot Card: </span><span class="tag--bold white">Justice</span></div>
        </div>
        <p>Libra is the seventh sign of the zodiac, and it’s at this point in the zodiac that we start to see a shift. While the first six signs of the zodiac focus on the individual, the last six focus on the individual’s contact with others and with the world. The Libra zodiac sign is first and foremost focused on others and how they relate to them. We can call this the sign of Partnership with a capital ‘P’ because these folks do not want to be alone!</p>
        <p>For a Libra, everything is better if it’s done as a pair. Libras are good when paired up, too, since they epitomize balance, harmony, and a sense of fair play. While they are true team players at work, their favorite partnership is at home: marriage. Libras feel most complete when they are coupled up with their lover, forever.</p>
        <h2>Libra Symbolism + Myth</h2>
        <p>The Libra zodiac symbol is the Scales, named for the stellar constellation this sign corresponded to by the astrologers of the old world. The astrological symbol of the Scales is associated with the goddess Themis, who ruled over justice and the law.</p>
        <p>She was said to be the daughter of Uranus and Gaia, and has connections to Venus and Aphrodite in Greek and Roman myth. When Themis was placed in the heavens as a stellar constellation, she originally spanned two zodiac signs, with what we call Virgo comprising her body, and her scales of justice forming the sign ﬁ.</p>
        <h2>Libra Element, Mode, and Season</h2>
        <h3>Fall</h3>
        <p>In the western tropical zodiac, Libra season begins at the Autumn Equinox, representing the “fall” in the Northern Hemisphere into the phase of the year when solar light will begin to diminish toward the Winter Solstice. Libra season begins on September 23 and ends on October 22. The Libra archetype is one of balance, equanimity, and equality, which is symbolized in the day of Autumn Equinox holding an equal measure of daylight, and nightfall.</p>
        <h3><strong>&nbsp;Cardinal Mode</strong></h3>
        <p>Libra is the third of the four cardinal signs of the zodiac, who all hold an elemental, initiatory energy that marks the beginning of the four seasons. Libra begins the Autumn, the source of the Scales’ affinity for taking leadership in diplomacy and social justice.</p>
        <h3><strong>&nbsp;Air Element</strong></h3>
        <p>Libra’s element is air a light, dispersive element, thought by ancient astrologers to be an expression of matter that represents formlessness, adaptability, and dissolution. Libra’s affinity for ease in supporting social connections and exploring the world with grace and poise are akin to the active, flowing air element.</p>
        <p></p>
        <p></p>
        <h2>Libra Planetary Rulership</h2>
        <h3>Domicile of Venus</h3>
        <p>In astrology, Venus is the planetary ruler of both Libra and Taurus. Libra was thought to be the day, or diurnal home of Venus, while Venus found a nocturnal home in earthy and abundant Taurus.</p>
        <p>In Libra, Venus has full affinity and potency in the harmonious archetype of this sign, being able to be as peaceful, diplomatic, and loving as a planetary force as she likes to be. Venus in Libra is found in the charts of elegant, graceful, and sociable people, that have a natural affinity for negotiating and expressing an artistic flair.</p>
        <h3>&nbsp;Exaltation of Saturn</h3>
        <p>In classical astrology, Saturn, the planet of duty and discipline, is thought to be exalted in Libra, whose fair, equanimous, and peaceable qualities blend well with Saturn’s stoic, discerning nature. This can present in the lives of those with Saturn in Libra in their birth charts as people who tend to be balanced and measured when it comes to expressing the Saturnian qualities of perseverance and good judgement. The theme of taking a calm, moderating role, and acting as a law-abiding authority may emerge in their lives.<strong>&lt;/</strong></p>
        <h3>Detriment of Mars</h3>
        <p>Libra is in polarity with the cardinal fire sign Aries. Ruled by Mars, Aries likes to confront and conquer, where Venus-ruled Libra likes to connect and keep the peace. Mars, when in the opposite sign of his preferred home, is said to be in detriment, or at a sort of disadvantage in this sign.</p>
        <p>Instead of having his typical weapons and armor at his disposal, imagine the planetary god of war and conflict in beautiful, refined surroundings. Mars would have to make do and compensate, presenting in the lives of those born with Mars in Libra the theme of needing to work against an overly compromising and conciliatory nature to express necessary anger at times.</p>
        <p>Mars in Libra natives may have difficulty with confrontation, preferring to avoid it and solve disputes in more diplomatic ways. This could have mixed results, depending on the circumstances. The warrior planet in the sign of the scales of justice could also indicate a person who fights for social causes, where they discover how to tap into their passions through advocating for others who are disempowered by society’s inequalities.</p>
        <h3>Fall of the sun</h3>
        <p>In the Thema Mundi, the ancient birth chart of the world, Cancer was rising, positioning Libra on the subterranean angle of the chart. This is the place where the sun is anti-culminating, the opposite of the sun’s exaltation in Aries. As a result, the sun is said to be in its “fall” In Libra, where it’s solar power and potency is in a lower, symbolically diminished state.</p>
        <p>Those born with the sun in Libra may have to work on putting themselves first in life and guard against letting others “outshine” them in relationships. Though naturally peaceful and compromising, those with their sun in this sign will need to care for their vitality and make sure not to spread their energies too thin when helping others.</p>
        <h2>&nbsp;Libra House Rulership</h2>
        <h3>The seventh house</h3>
        <p>In the modern astrology system of the Twelve Letter Alphabet, each zodiac sign rules one of the twelve houses in the birth chart. This innovation was created by psychological astrologers to match sign affinities to related house topics.</p>
        <p>Libra was assigned the seventh house of relationships, since its balanced, relational energy was similar to the way the seventh house in the birth chart indicates how we form partnerships. Since Libra is ruled by Venus, this modern astrology system invites a Venusian sub-signature to the significations of the seventh house.</p>
        <h3>The fifth house</h3>
        <p>In classical astrology, Libra’s planetary ruler Venus was said to find her “joy” in the fifth house of “good fortune,” which includes sex, beauty, the arts, and life’s pleasures. This is related to Venus classically being considered one of the more helpful, or “benefic” planets in astrology, responsible for gifts, luck, and inspiring artistic abilities.</p>
        <p>Since the fifth house has a connection to romance, children, and anything fortunate that can come our way in life, Venus is able to “joyfully” express her more welcome offerings here. Placed in the house of “good fortune,” Venus is lucky and gets an extra boost.</p>
        <h2>Libra Characteristics</h2>
        <h3>Personality</h3>
        <p>Libra’s archetypal traits are derived from its active, masculine, or yang qualities, making this sign oriented toward engagement with the outer world. Alive in both a Libra woman or Libra man, those born with the planet of love as their rising, sun, or moon sign have an equanimous energy in their core personality.</p>
        <p>As a cardinal air sign, Libra holds the qualities of social initiation and leadership. This makes those with Libra prominent in their charts great at pioneering social projects and gatherings, and naturals at unifying their team, family, or community.</p>
        <p>Natives from this sign can be thought of as “the diplomats” of the zodiac, acting as active mediators and negotiators in any crisis or challenge. Being ruled by the planet of pleasure and attraction, Libra is usually quick to forgive and eager to smooth out differences so that everyone can get back to enjoying the finer aspects of life.</p>
        <h3>Strengths</h3>
        <p>Libra’s great strengths can be found in their ability to embody Venus’ loving, healing, and balancing traits. These folks will likely have the ability to put others first for the sake of everyone’s comfort and well-being. They are great communicators and listeners, fairly weighing all sides of an argument and another’s point of view.</p>
        <p>Those born under the sign of the scales are very inclusive and can be sensitive when others feel alienated. These folks will work to bring anyone disenfranchised back into the fold. There is a natural orientation toward seeking justice and fairness in society, through the law or spoken agreements.</p>
        <p>Libras are likely to not hold grudges, as it can take a lot to rouse and sustain their anger. Being very Venusian, they typically assume the best intentions in others and give most people many chances to redeem themselves.<br>In addition to these folks’ great relational strengths, there are also their keen aesthetic sensibilities to consider. Not only will this make sun sign Librans very creative, it will make them attuned to the subtleties of atmosphere and harmonious environments. They are naturally curious about how the aesthetics of our adornments and surroundings can set the tone for our well-being and social interactions. Keeping the peace and maintaining poise, grace, and charm are strengths that can be relied on from these natives.</p>
        <h3>Weaknesses</h3>
        <p>Some sources of weakness or potential blind spots in the Libra archetype are the flip side of all of their great strengths. Librans have the opposite challenge that their polar Aries counterparts have. Where Aries is challenged to make their fierce, individually focused natures more relational, Libra is at times challenged to adapt their naturally conciliatory and differential natures to be more self-focused.</p>
        <p>Since the sun is in its “fall” in Libra, it symbolizes a potential pitfall in these natives taking form in not elevating, radiating, or valuing themselves enough at times. Often, for the sake of peacekeeping, they will not express their anger or discomfort, but if they are not careful, this can lead to suppressed emotions that can solidify into resentment.</p>
        <p>Later on, this resentment may come out in unusual ways, as Libra’s Venusian tendency to focus only on the good and pleasant will put their more uncomfortable feelings off of their radar.</p>
        <p>Librans may soothe their resentments by hiding in pleasures and indulgences, rather than put someone on the spot with their grievances. Another way that Libra’s blind spots can manifest is in their generosity leading them to overcommit, as they hate to say no and let anyone down. This can lead to their solar reserves getting depleted and spread too thin. Again, they must permit themselves to indulge in a little therapeutic “selfishness” at times for their own well-being.</p>
        <p>The classic Libra indecisiveness, while rooted in an ability to weigh all sides, can thwart this sign’s ability to make choices. In wanting to be inclusive, they find it difficult to discriminate, yet there will be times when they need to commit to a path and accept this will sacrifice other options. Libra’s love of beauty and refinement may have to be measured with soulfulness, and earthiness, allowing them to play in the muck of life so that they do not come across as aloof or snobby.</p>
        <p>Libran children will be well nurtured if they are reminded that they are worthy of love as they are, and do not have to give their friends gifts to “pay them back” for their love and support.</p>
        <p></p>
        <p></p>
        <h2>Libra Life Purpose and Career</h2>
        <h3>Mantra and Purpose</h3>
        <p>The invitation to connect comes forward in the Libra mantra: <strong>I relate.</strong> Libra’s sense of purpose is all about making social and creative connections. Libras are the diplomats, moving forward into society to uphold love, justice, beauty, and truth for all.</p>
        <p>We all have Libra somewhere in our birth chart, so we can look to the house that Libra rules to find the specific area of life we approach in a balanced way, or where we need to call in the Scales persuasive Venusian energy for mastery.</p>
        <p>Libran people tend to be drawn to any pursuit where they are initiating a social or artistic movement of some kind, that is inclusive and accessible to a diverse population. Law, diplomacy, philanthropy, and artistry, all provide Libra an outlet for their aesthetic and egalitarian tendencies.</p>
        <h3>&nbsp;Libra at Work</h3>
        <p>Libra’s natural relational abilities make them uniquely suited for professions where they need to work with others, and to advocate for the less fortunate. Their careers need to have some dynamic of mending, repairing, beautifying, or negotiating to be fulfilling. This could manifest in many professions, but likely will not be found in staid, solo-type jobs that require this sign to work in isolation.</p>
        <p>Like all the air signs, Libra needs novelty, activity, movement, and space, so will not be content for long in the same location, unless of course, that location is a beautiful place, full of interesting people! If they are required to do isolated, routine-type work, they can remedy this by decorating their workspace with art and beauty, and by infusing their atmosphere with music and fragrance to promote inspiration and calm.</p>
        <p>Since Libra is ruled by Venus, the planet of luxury and beauty, a natural career fit could potentially be found in the many facets of the artistic or beauty industries. Any way that a Libra can beautify and improve the lives and surroundings of others will likely be most fulfilling.<br>As art appreciators and artists themselves, Libras know that beauty can inspire people, and they enjoy expressing ideas through many mediums. You can find many of them behind the camera in photography or filmmaking. They could also be great illustrators, painters, or interior designers.</p>
        <p>Image-conscious Libras can be found in fashion design, either as the creators, or the models of beautiful clothing. Natives from this sign will also make wonderful hairstylists or make-up artists, taking pleasure in supporting the well-being of their clients. In these fields, the opportunity to be a supportive listener and counselor will likely come up when they collaborate with their clients to express their own inner beauty and truth.<br>Those born under the sign of the scales will be drawn to work in justice and the law. Libra is the exaltation of Saturn, the planet of sound judgement, so Librans may make good lawyers and judges, being able to weigh all factors with objectivity and balance.</p>
        <p>Venus-ruled Libra loves to facilitate understanding, and so can be well-suited to mediating, or negotiating roles. Their sweetness, calmness, and poise inspire trust and helps those who are seeking a resolution feel more at ease, respected, and understood.</p>
        <p>With the planet of love as their guide, partnership dynamics will be of interest to Libra, making them excellent marriage and relationship counselors. Their mediating and listening skills will be a key asset to help lovers sort out their differences.</p>
        <p>Since social justice and society as a whole is a prime Libran concern, we often find those born under the sign of the Scales involved in the world of politics. They take to social leadership naturally and would make impressive diplomats or ambassadors when representing the affairs of their community, nation, on the world stage.</p>
        <p>In general, Libra as an archetype supports those who are suited for management roles, since they are likely to have well-adapted interpersonal and leadership skills. You may find Libra managing companies, large and small, or working in the human resources department of large firms. Libra’s management and conversational skills will make them natural in sales of all kinds, as ambassadors of products or services they believe in.</p>
        <h2>Libra Compatibility</h2>
        <p>When exploring overall compatibility in astrology, it’s important to take more than the sun sign into consideration, as the rising sign, moon, and other planetary cross-connections will tell the whole story in relationships. That being said, Libra natives will tend to blend best with fire signs and air signs; and may need to work harder on relationships with water signs and earth signs.</p>
        <h3>&nbsp;Fire signs</h3>
        <p>Libra will typically find a complementary connection with fire signs, as they will understand each other’s active, spontaneous natures. Air feeds fire, stoking it to grow and become more alive, so passionateLeo will likely appreciate Libra’s flair for beauty and love of parties.</p>
        <p>Adventurous Sagittarius and sociable Libra will likely play well together and enjoy the beauty and variety that the world has to offer.</p>
        <p>Ruled by Venus, Libra brings softness, democracy, and peacefulness to Mars-ruled Aries, and they potentially have an opposites attract connection together that can be magnetic, or polarizing. Aries teaches Libra to put themselves first, while Libra teaches Aries some tact and the benefits of compromise.</p>
        <h3>&nbsp;Air signs</h3>
        <p>Air signs are a natural fit for Libra, as they share the same elemental expression. Venus-ruled Libra brings balance, beauty, and sociability to Gemini’s stimulating, interconnected world.</p>
        <p>Libra and Aquarius will enjoy conversing endlessly, sharing ideas on issues of social justice. Due to its Saturn’s influence, Aquarius may at times be more cool and remote and will have to remember to show affection to romantic Libra.</p>
        <p>Libra with Libra is a wonderful match, yet their passion may be directed toward creating a social project of some kind, be that a shared philanthropic goal, or opening a socially conscious art gallery. Their life will be very public together, making appearances at fundraisers and artistic events.</p>
        <h3>Water signs</h3>
        <p>Water signs bring vulnerability and emotional intelligence to help airy, peacekeeping Libra to tap into their deeper wells of feeling.<br>Cancer will be very good at caring for Libra, which they will love, but Cancer and Libra may come to an impasse on how to spend their time together. Cancer loves to stay home and intimate gatherings, while Libra loves public life.</p>
        <p>Pisces broadens Libra’s receptive capacities by bringing spiritual and philosophical awareness to their lives. Pisces will want to encourage emotional depth, while Libra may want to keep things light and cheery, causing a disconnect in the focus between them.</p>
        <p>Mars-ruled Scorpio can bring sexual magnetism to a relationship with Libra, but the two may share very little in common in the end. Scorpio’s brooding intensity may feel too heavy for Libra to bear, and their core natures may be too opposite to truly meld.</p>
        <h3>&nbsp;Earth signs</h3>
        <p>Though earth signs can potentially stabilize and ground Libra’s dispersive energies, they may at times be the hardest for those born under the sign of the scales to relate to.</p>
        <p>Capricorn, the authoritative cardinal earth sign, will be a pragmatic partner for Libra to depend on, but their union may shift away from romance to business in the end.</p>
        <p>Virgo and Libra share an affinity for refinement and harmony, yet Virgo may get too strict or nervous when Libra wants to social network. Libra, however, may be able to help Virgo to be less self-critical by coaxing them into having more fun.</p>
        <p>Taurus and Libra share the rulership of Venus, which brings them together when enjoying and appreciating life’s pleasures. They are both peaceful, and generally content, but will move at such different speeds that it will be hard for them to sync up their plans.</p>
        <h2>Libra Health</h2>
        <h3>Constitution</h3>
        <p>In medical astrology, there were four temperaments that were connected to four vital fluids and four essential constitution types. Libra is associated with the sanguine temperament, which was thought to be hot and moist, and connected to the blood. The sanguine constitution was considered to be naturally healthy and resilient, being connected to the youthful phase of life, and the Spring season.</p>
        <p>Sanguine folks typically have a cheery disposition, lean body shapes, and are naturally energetic. Apart from Libran imbalances related to impurities in their food and drink, or depleted energy from overwork, this constitution type may not experience many health challenges until their later years. At this time, issues related to blood pressure or blood stagnation may arise when the naturally high sanguine metabolism starts to slow down.</p>
        <h3>Body Parts</h3>
        <p>In classical astrological medicine, the entire zodiac was mapped out on the human body, with Libra ruling over the lower back. Internally, Libra rulership extends to the kidneys and the adrenal glands, which are linked to healthy energetic and eliminatory functions.</p>
        <p>Emotionally, Librans may “carry” the concerns of others in their mediating and peacekeeping efforts, which can materialize somatically in lower back pain and tension. Being born under the “fall” of the sun, these folks need to protect their solar vitality, which means not overcommitting and dissipating their energy reserves. This kind of strain and depletion can drain their adrenal glands and put stress on their kidney’s eliminatory functions.</p>
        <p>Those born with Libra rising, especially, will need to manage their energy and maintain balance in their lives.</p>
        <h2>Herbal Allies</h2>
        <p><strong>Marshmallow Root&nbsp;</strong>is a classic herbal that is associated with Libra’s planetary ruler, Venus. It is mucilaginous and demulcent, meaning that it is soothing and moistening to internal tissues. It is especially supportive of the urinary tract and the kidneys, a very important body system for Libra.<br>Marshmallow root helps support the eliminatory and filtering functions of the kidneys and repairs any irritations. It also can help lubricate blockages and is useful in helping to ease out kidney stones, or impurities in the urinary tract. Moistening and refreshing, Marshmallow root can help heal and restore an overworked and dehydrated system.</p>
        <p><strong>Mugwort</strong>&nbsp;has many healing powers, including assistance with women’s menstrual cycles; another important Venus association. Mugwort tea and tincture has a warming quality to help increase circulation and soothe abdominal cramping.</p>
        <p>Its analgesic qualities make mugwort oil helpful to soothe sore muscles and pain, which is the reason why it was placed in the sandals of Roman soldiers as well as in the shoes of travelers on long pilgrimages in the Middle Ages. It has long been considered a magical plant, worn for protection to ward off evil spirits as well as inducing vivid dreams for spiritual insight. In Chinese medicine, Mugwort is used in moxibustion to clear energetic blockages in the body’s meridians.</p>
        <p><strong>Damask Rose</strong>, with its beautiful color, elegant bloom, and sweet fragrance, is a prime Venusian plant. It has many uses, from inspiring affection in the form of a bouquet to soothing and restoring dry, irritated skin in beauty remedies.</p>
        <p>In Indian medicinal practice, foods with rose petals and rose water are thought to be especially nourishing for restoring an emaciated body and to comfort a sad heart. In herbalism, rose tea and extract are used to calm mood swings, restore imbalances in the menstrual cycle, and to heal and repair the circulatory or “venous” system.</p>
        <h2>Esoteric Libra</h2>
        <h3>&nbsp;The Three Decans of Libra</h3>
        <p>Each of the twelve zodiac signs represents a thirty-degree slice of a 360-degree band of constellations, circling the earth. The thirty degrees of each sign can be further subdivided into three ten-degree decans, or faces, each with its own planetary sub-ruler placed around the zodiac in Chaldean order.</p>
        <p>These faces can be used for timing magical rituals when seeking to evoke and harness Venus’ planetary power. In studying the Libra personality, we can use the faces of Libra to fine-tune the flavor and nuance of planets or points placed within these decanic degrees.</p>
        <h3>First Decan of Libra: Moon</h3>
        <p>Degrees 0 through 9 of Libra are ruled by the moon. This blends the sensitive and receptive qualities of the moon with this sign’s sociable nature and gives the first decan of Libra a lunar sub-signature. Those born with planets or points in these degrees of Libra may be especially nurturing, protective, and even shyer folks.</p>
        <h3>Second Decan&nbsp;of Libra: Saturn</h3>
        <p>Degrees 10 through 19 of Libra are ruled by Saturn.This is the exaltation of the stern planet of discipline and judgement, making those born with planets or points in this second decan more serious than their other Libran counterparts. Those born with planets or points in the degrees of this sign may be drawn to being judges or lawyers, as Saturn’s discerning nature blends well with Libra’s Venusian equanimity.</p>
        <h3>&nbsp;Third Decan of Libra: Jupiter</h3>
        <p>Degrees 20 through 29 of Libra are ruled by Jupiter, the planet of expansion and higher truth. Jupiter’s influence here tends to expand Libra’s social justice leanings into epic proportions. These Libras may be on a philosophical quest to bring diverse people together through social programs or inclusive politics. Those born under the third decan of this sign serve justice, much the same as the second decan, but they may take a more philanthropic approach to realizing these ideals.</p>
        <h2>Libra Tarot Cards</h2>
        <h3>Major Arcana: Justice</h3>
        <p>The Tarot card that correlates to Libra is number 11:Justice.This card depicts a noble, Libra-type character, a calm and balanced judge-king archetype, seated between two pillars that echo the equilibrium of the Scales.</p>
        <p>The justice card tends to appear to help us meditate on choices we are making, similar to the manner of the Gemini card, the Lovers. Here, the judge-king holds the elements of discernment; in the left hand, the scales that weigh out the pros and cons, and in the right hand, the sword, the Tarot implement of the intellect pointing towards the heavens for divine guidance.</p>
        <p>Minor Arcana<br><strong>2,3, and 4 of Swords</strong><br>In the Minor Arcana of the Tarot, the Suit of Swords is associated with the element of air. Here, we see the three decans of Libra assigned to the 2, 3, and 4 of Swords, cards associated with the implementation of ideas and knowledge. The Swords symbolize the discerning and intellectual facilities that we have at our disposal, as well as the need to keep these sharp and honed to cut through to understanding with precision, and objectivity.</p>
        <p><strong>2 of Swords: Moon in Libra</strong><br>The 2 of Wands corresponds to the first decan or face of Libra. It carries the sub-signature of the moon, and was referred to in the Book of Thoth as the card of “Peace.” This card appears when we are turning inward with lunar receptivity to contemplate our choices and hone our intuition. By developing inner sight, we can harmonize our emotional and intellectual forces.</p>
        <p>The “Peace” card explores how “intellectual manifestation…abides above the onslaught of disruption.” (Book of Thoth)</p>
        <p><strong>3 of Swords: Saturn in Libra</strong><br>The 3 of Swords corresponds to the second decan or face of Libra. It carries the sub-signature of Saturn and was referred to in the Book of Thoth as the card of “Sorrow.” This card depicts a thrice pierced heart, and usually signifies emotional pain, or “lovesickness.” Since the number three is a dynamic card, it is not the story of being stuck in the pain, but in an evolving situation we can work through with sober, Saturnian clarity.<br>The “Sorrow” card is dark and heavy; it is, so to speak, the womb of Chaos. There is an intense lurking passion to create…” (Book of Thoth)</p>
        <p><strong>4 of Swords: Jupiter in Libra</strong><br>The 4 of Wands corresponds to the third decan or face of Libra. It carries the sub-signature of Jupiter and was referred to in the Book of Thoth as the card of “Truce.” This card appears when we are in a state of forced rest or immobilization. This forced rest opens an opportunity to surrender, and to restore our mental clarity.</p>
        <p>The “Truce” card “represents a refuge from mental chaos.” (Book of Thoth)</p>
    </div>
</div>
</body>
</html>
