<%--
  Created by IntelliJ IDEA.
  User: elmirabajgulova
  Date: 31.10.2021
  Time: 00:20
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <meta name="viewport" content="with=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/styleHome.css">
    <link rel="stylesheet" href="css/styleZodiacSignsPages.css">
</head>
<body>
<section class="sub-header">
    <%@include file="/WEB-INF/top_nav.jsp" %>
    <h1>Pisces</h1>

</section>
<h1>Pisces</h1>
<div class="grid__content">
    <div class="editorial-article__feed">
        <h2>Pisces Traits &amp; Overview</h2>
        <div class="zs-meta border-grey border-rad-4 grid-1c grid-sm-2c grid-lg-3c grid-c-gap-3 p-2 mb-3">
            <div class="meta-item"><span class="tag">Pisces Dates: </span><span class="tag--bold white">February 19 – March 20</span></div>
            <div class="meta-item"><span class="tag">Symbol: </span><span class="tag--bold white">The Two Fishes</span></div>
            <div class="meta-item"><span class="tag">Mode + Element: </span><span class="tag--bold white">Mutable&nbsp;Water</span></div>
            <div class="meta-item"><span class="tag">Ruling Planet: </span><span class="tag--bold white">Jupiter Neptune</span></div>
            <div class="meta-item"><span class="tag">House:</span><span class="tag--bold white"> Twelfth</span></div>
            <div class="meta-item"><span class="tag">Mantra: </span><span class="tag--bold white">I Believe</span></div>
            <div class="meta-item"><span class="tag">Body Parts:</span><span class="tag--bold white"> The Feet, Lymphatics, Liver</span></div>
            <div class="meta-item"><span class="tag">Colors:</span><span class="tag--bold white"> Purple White</span></div>
            <div class="meta-item"><span class="tag">Tarot Card: </span><span class="tag--bold white">The Moon</span></div>
        </div>
        <p>Pisces is the twelfth sign of the zodiac, and it is also the final sign in the zodiacal cycle. Hence, this sign brings together many of the characteristics of the eleven signs that have come before it. Pisces, however, are happiest keeping many of these qualities under wraps. These folks are selfless, spiritual, and very focused on their inner journey.</p>
        <p>They also place great weight on what they are feeling. Yes, feelings define the Pisces zodiac sign, and it’s not uncommon for them to feel their own burdens (and joys) as well as those of others. The intuition of the Pisces-born is highly evolved. Many people associate Pisces with dreams and secrets, and it’s a fair association, since those born under this sign feel comfortable in an illusory world.</p>
        <h2>Pisces Symbolism + Myth</h2>
        <p>The constellation known as Pisces has been associated with many divine figures in history, such as Poseidon/Neptune, Christ, Vishnu, and the Sumerian goddess Inanna. Pisces is the Latin word for “fish,” and in Greek mythology, this constellation represents the koi fish that saved Aphrodite and her son Eros from the sea monster Typhon.</p>
        <p>As a reward, the two fishes were placed in the heavens to shine for all of eternity. Venus, the Roman version of Aphrodite, is said to have an exalted position in Pisces, an affinity that echoes back to her gratitude for the fishes’ hospitality and help.</p>
        <h2>Pisces Element, Mode, and Season</h2>
        <h3>Late Winter</h3>
        <p>Pisces season in the western tropical zodiac begins on February 19, commencing the final phase of Winter in the Northern Hemisphere. This is the time of year when the chill of winter is beginning to yield to the oncoming warmth of Spring, and the days are continuing to increase in light. The underlying seasonal sense that growth and renewal are soon returning to the world is mirrored in the reflective and inwardly creative imaginings of the Piscean archetype.</p>
        <h3>Mutable Mode</h3>
        <p>Pisces is the fourth and final of the mutable signs in the zodiac wheel, who all hold an energy of change, liminality, and adaptation at the end of one season, and the beginning of the next. Pisces begins the last phase of winter, when the cold season is less established, lending to the fluid and changeable sign qualities of Pisces.</p>
        <h3>Water Element</h3>
        <p>Pisces’s element is water, the second heaviest element, thought by ancient astrologers to be the fluid, adaptive, yet a tangible form of matter. Water represents the moistening and cohering principle that binds and connects all forms of nature.</p>
        <p>Without it, nothing that takes a material form could “stick” together. Water fertilizes earth so that nature and creativity can incubate and bloom. Pisces’ creativity, intuition, imagination, and strong inter-relational talents are all akin to the connectivity of the water element.<br><br></p>
        <p></p>
        <h2>Pisces Planetary Rulership</h2>
        <h3>Domicile of Jupiter</h3>
        <p>In classical astrology, Jupiter is the planetary ruler of both Sagittarius and Pisces. Sagittarius was thought to be the day, or diurnal home of Jupiter, with Jupiter finding a second nocturnal home in sensitive and soulful Pisces. Jupiter has a full affinity with the imaginative and spiritual tendencies of this sign, but because it is in its nocturnal home, these themes take on a more interior and meditative expression.</p>
        <p>This placement presents a more thoughtful, reflective, and gentle version of Jupiter’s bold planetary energy. Pisces is potentially the archetype of a more private and mysterious seeker than the ebullient, outgoing Sagittarius. Those born with Jupiter in the sign of the Two Fishes tend to have a strong belief in the unseen forces of the universe and are often mystic seekers and teachers.</p>
        <h3>Detriment of Mercury</h3>
        <p>Pisces is in polarity with the mutable earth sign Virgo. Ruled by Jupiter, Pisces likes to seek, expand, and dissolve boundaries, where Virgo, ruled by Mercury, likes to organize the material world, focus on fine details, and seek perfection. When in the opposite sign of its preferred home, Mercury is said to be in detriment, or at a sort of disadvantage in Pisces.</p>
        <p>Imagine the planet of clear communication and information having to live in Jupiter’s boundless, philosophical world. Mercury may get lost, going “off-road” on adventures and storytelling tangents, and would find it difficult to communicate and translate its ideas.</p>
        <p>The result is Mercury having to compensate and translate big Jupiterian philosophical ideas into day-to-day conversations. This could appear as a poetic and epic use of language, and a quest for truth in meaning in all intellectual endeavors.</p>
        <p>It could also mean that those born with this placement may struggle with focusing on the day-to-day and may often daydream or lose track of time. They may have to work harder on creating intellectual structure and getting to the point. And while this planet-sign combination could present challenges and ways that these natives need to learn at their own pace, it could produce poets and songwriters as well.</p>
        <p><strong>Exaltation of Venus</strong><br>Since Venus is exalted in the opposite sign Pisces, she is said to be in her fall in Virgo. While not in her domicile, Venus is still very powerfully placed in Pisces as an esteemed guest of honor. In Jupiter’s nocturnal sign, she has access to unique resources that help her deliver some of her most positive gifts and expressions.</p>
        <p>Venus’ powers of love, attraction, beauty, and art blend well with Jupiter’s spiritual and affirming energies, giving natives with this placement some extra luck or ease in these matters. It can produce very sweet, sensitive, and loving people, who sacrifice themselves for the good of others. Natives with this placement may also have strong creative talents, taking their art to transcendent, inspiring levels.</p>
        <h3>Modern Ruler: Neptune</h3>
        <p>The circumstances of Neptune’s discovery are as transcendent and mysterious as this planet’s significations. Inspired by disturbances in Uranus’ orbit, Neptune’s founders followed theoretical calculations, and a sort of scientific “faith” in its existence.</p>
        <p>It turns out it had been observed for centuries before but was mistaken for a blue fixed star. The affirmation of Neptune’s existence seems to have unfolded when the world’s perceptions and inventions caught up with a dawning reality of how expansive our universe truly is.</p>
        <p>The illusory states that Neptune is connected to can even be connected to the way it casts an illusion on astronomers until they understood what they were seeing. The awe-inspiring and innovative themes surrounding Neptune’s discovery lend themselves to how Neptune earned its significations and connection as a modern sub-ruler to imaginative Pisces.</p>
        <h2>Pisces House Rulership</h2>
        <h3>The Twelfth House</h3>
        <p>In the modern astrology system of the Twelfth Letter Alphabet, each zodiac sign rules one of the twelve houses in the birth chart. This innovation was created by psychological astrologers to match sign affinities to related house topics.</p>
        <p>Pisces was assigned the twelfth house of isolation, confinement, and retreat since Pisces’ deep, reflective, and interior territory aligned with the concerns of this house. Since Pisces is ruled by hopeful Jupiter and transcendent Neptune, this system invites these philosophical and spiritual planetary sub-signatures to the twelfth house.</p>
        <h3>The Eleventh House</h3>
        <p>In classical astrology, Pisces’ planetary ruler, Jupiter, was said to find its “joy ” in the eleventh house of “good spirit” in the birth chart. This house, associated with friends, alliances, hopes, and gifts is a natural, affirming, and happy place for Jupiter to be in.</p>
        <p>Since Jupiter likes to expand and affirm belief and faith, this house speaks to the opportunities that are available to us when we feel we belong to a loving community. With a connection to the Piscean planetary ruler, these communities could be social, but also spiritual, providing encouragement, validation, and support. The eleventh house is associated with alliances we form, and gifts we receive in our public or social roles, perhaps as an extension of our career activities.</p>
        <h2>Pisces Characteristics</h2>
        <h3>Personality</h3>
        <p>Pisces’ personality traits are derived from its receptive, feminine, or yin qualities, making this sign oriented toward contemplation and engagement with inner awareness. Alive in both a Pisces woman or Pisces man, those born with the Fishes as their rising, sun, or moon sign have a mystical, intuitive, and transcendental dynamic in the core of their personality, an echo of the seasonal awakening in late winter.</p>
        <p>As a mutable sign, Pisces holds adaptive, fluid, and shape-shifting qualities. Those with the sign of the Two Fishes prominent in their charts are sensitive seekers who have the potential to bring a soulful, healing energy to their relationships and communities.</p>
        <h3>Strengths</h3>
        <p>The primary Pisces’ strengths can be found in their tender, sympathetic, and receptive natures. Naturally compassionate and empathic, Pisces are wired to offer spiritual and artistic gifts to the world. These are the poets, musicians, painters, and intuitive counselors in our communities.</p>
        <p>With Jupiter’s influence on the faith, belief, and sense of higher purpose, Pisceans can be counted on to offer help and healing support to anyone who is in need. These natives tend to drift through life on their schedule and follow an inner sense that life is unfolding as it should.</p>
        <p>Idealistic and imaginative, those born under the Two Fishes’ sign have an otherworldly quality to them and seem to retain a sense of innocence and wonder their whole lives. These natives often believe in the good of others and will likely give the benefit of the doubt.</p>
        <p>When they fall in love, Pisceans do so completely and will give much of themselves to their friends and partners to selflessly nurture a connection. Pisces natives seem to be born with an open conduit to the other side, and those with prominent Piscean chart placements are often mystics, mediums, and psychics.</p>
        <p>While the rest of us may outgrow the playful reveries of our childhood, there is a part of the Pisces personality that never becomes fully practical or attached to material possessions. They often retreat into a meditative solitude to recharge and contemplate, a practice that is especially important to these sensitive souls. With few attachments, their mutable natures are ready to move and adapt to new surroundings or ideas, making it hard for them to get bored or stuck in a rut.</p>
        <p>As the twelfth and final sign of the zodiac, the Piscean archetype is that of the old soul who may be living its last incarnation before ascending to the heavens.</p>
        <h3>Weaknesses</h3>
        <p>Some potential weaknesses in the Pisces archetype are rooted in their great strengths. Though natives from this sign are tender and sympathetic, they may take certain comments too much to heart and get easily wounded emotionally. Often creative and artistic, Pisceans may struggle with how to materialize their pursuits into a tangible, functional livelihood. Being naturally adaptive and changeable can be an asset, but it can also make it hard for these natives to follow through or stick with tedious details.<br>Following their sense of time and often getting sidetracked, those born under the sign of the Two Fishes need to somehow find a way to be mindful and respectful of others’ time. Those born under Jupiter’s benevolent influence like to believe in the good of others, but they must to be discerning and discriminating.</p>
        <p>Selflessness and self-sacrifice are beautiful gifts that Pisceans offer, but this can lead them to be too needy, vulnerable, and codependent in love relationships. It may be a sad reality to accept, but these natives need to realize that others may take too much advantage if they cannot build their resilience, structure, and autonomy.</p>
        <p>When it comes to offering their gifts to the world, boundaries are of prime importance to preserve the Piscean’s energy. Like all water signs, Pisces is vulnerable to absorbing toxic energies, so if they are offering healing or counseling work, they need to have cleansing practices.</p>
        <p>Breathing exercises, saunas, smudging, and protective aura visualizations are all ways these natives can maintain psychic health. Enjoying solitude as well as retreating from time to time to recharge are important practices for Pisces as well, however, this needs to be kept in balance, as there can be a danger in withdrawing for too long.</p>
        <p>These natives may begin to feel fearful of re-emerging and can get lost in escapism, self-medication, and avoidance. It will be important for Pisceans to seek support and counseling for themselves if they feel overwhelmed by the weight of the world’s emotional pain, as well as addressing their own emotional needs.</p>
        <p>Piscean children will be well-nurtured if they are supported in their creative talents, and are encouraged to balance their sweet, giving natures with healthy boundaries. Play at times can be rough and tumble, so these young ones need guidance on how to let the insensitivity of others roll off their backs.<br></p>
        <p></p>
        <h2>Pisces Life Purpose and Career</h2>
        <h3>Mantra and Purpose</h3>
        <p>The voice of empathy, idealism, and mysticism comes forward in the Pisces mantra:&nbsp;<strong>I believe.</strong>&nbsp;Those born under the sign of the Two Fishes find purpose in exploring the unknown, by being of service, and in unique creative expression. Operating in the mutable mode, Pisces adapt and share their healing gifts with their communities, and channel their transcendental ideas into their creative projects.</p>
        <p>With one foot in this world and one foot in the next, Pisces seeks to bridge the realm of the spiritual with everyday mundane realities. They are here to remind us that everything is sacred and that we all hold a spark of the divine within.</p>
        <p>We all have Pisces somewhere in our birth chart, so we can look to the house that the Two Fishes rule to find the specific area of our life we approach in an idealistic, intuitive way, or where we need to call in mystery and creativity to master.</p>
        <h3>Pisces at Work</h3>
        <p>Pisces’ expansive, adaptive, and imaginative nature makes them uniquely suited for jobs where they can heal and support, or be creative and imaginative. This could take form in many professions and roles, but will likely not be found in jobs that are high paced, risky, or stressful.<br>These natives may need to cultivate a safe, private work environment, where they can connect, dream, and follow their intuition. Routine or structure don’t come natural to Pisces natives, so they can borrow the skills of their opposite sign Virgo, to learn how to create a schedule and a sense of material order. That being said, Pisceans are still very productive if left to their own devices, as they are often following a big picture or plan that others don’t yet perceive.</p>
        <p>Those born with the sign of the Two Fishes prominent in their birth charts may not fit into many conventional jobs and may have to use their powers of adaptation to create new professions for themselves that do not yet exist.<br>The compassion and healing talents of Pisces, as well as the twelfth house connection to institutions, can lead these natives to roles as physicians and nurses in hospitals. And they may even also tend to those who are isolated in prisons and mental health facilities. These natives may also do work in rehab, assisting people with healing on a soul level from trauma and addiction.</p>
        <p>Pisceans are natural therapists and counselors and may be suited for psychiatry and psychology roles. In this field, these natives can use their receptive and listening skills to support growth and positive life strategies.<br>With an interest in spirituality and faith, Pisces can be drawn to leadership roles in religious communities. Here, we may see them as chaplains or pastors at service, or in quiet retreat as monks or nuns. These natives may explore many facets of religious devotion, and are interested in the universal messages behind the various world belief systems.<br>Mystic by nature, these natives are curious about the occult and may go outside of society’s norms to practice spiritual devotion. They may have alternative belief systems or may work as psychics, mediums, or clairvoyants.</p>
        <p>Wellness professions of all kinds would be well suited to Pisces, and we may find these natives teaching yoga, nutrition, and meditation to their local communities. They may prefer seeing people on a one to one basis, where they can offer personalized care and practices that suit the unique needs of their clients.</p>
        <p>Pisceans may take to water-based professions like their fish archetype as sailors, divers, swimmers, and lifeguards. They may also enjoy roles in marine biology, or as oceanographers, with environmental protection in mind.</p>
        <p>Those with strong Two Fishes placements in their charts can be found in creative professions of all kinds. With the modern connection to illusory Neptune, many of these folks are working in the film industry, either in front of or behind the camera. Pisces are often natural musicians, poets, fantasy writers, and artists, and explore universal messages with their various mediums.</p>
        <h2>Pisces Compatibility</h2>
        <p>When exploring overall compatibility in astrology, it’s important to consider more than the sun sign, as the rising sign, moon, and other planetary alignments and aspects will tell the whole story in relationships. That being said, Pisces natives will tend to blend best with water signs and earth signs; and may need to work harder on relationships with fire signs and air signs.</p>
        <h3>Fire signs</h3>
        <p>Sensitive and private Pisces may find the volatile and impulsive fire signs the most challenging to relate to. Fire signs have a directness and intensity that these gentle natives may find overwhelming.</p>
        <p>For example, being adjacent signs on the zodiac wheel, Aries and Pisces share little in common. In many ways, they are quite opposite, but not in a complimentary manner. Mars-ruled Aries is assertive and individualistic, where Jupiter-ruled Pisces is reflective and self-sacrificing. They might have lessons to teach each other, but may fundamentally be too different to truly meld.</p>
        <p>Sagittarius and Pisces share a Jupiter rulership, which can help them find affinities and relate. Both are mystic, idealistic seekers, but they have very different ways of exploring these themes. Sagittarius likes to roam, where Pisces needs to retreat, so they may not agree on how to spend time together. Even more so, their signs form a square aspect to each other in the zodiac, which can hint at friction.</p>
        <p>Leo and Pisces also do not share anything modally or elementally in common. It’s as if they have trouble “seeing” and understanding the other’s different nature. Leo’s self-centered passions may clash too much with Pisces’ soulful and universal ideas of love. Leo may feel forgotten or neglected when Pisces retreats into solitude, making it challenging for these two to find a mutual rhythm.</p>
        <h3>Air signs</h3>
        <p>Swift, speedy, and social, air signs could at first be fun and refreshing in Pisces’ insular and private world, but ultimately these natives may find the air signs too talkative and frenetic to fully relax with.</p>
        <p>Gemini and Pisces form a square aspect to each other on the zodiac wheel, so their very different natures may tend to work at cross purposes. Though they share a mutable mode, they are different in every other way. Gemini is restless, talkative, and is endlessly fascinated by facts and information, while Pisces is reflective, slow to speak, and is focused on universal truths. They may find little common ground.</p>
        <p>Libra and Pisces have some similarities. Both tend to be peaceable and seek calm and balance in their lives. Libra is more outgoing, and Pisces is more private, so they may not share the same space very often. Libra also tries to keep the conversation light and on the surface, while Pisces wants to go deep, making it hard for them to merge long term.</p>
        <p>Aquarius with Pisces are adjacent to each other on the zodiac wheel and share no common element, mode, or planetary ruler. Aquarius is dry and aloof, while Pisces is sensitive and sentimental, so they speak very different love languages. It may not be a satisfying match long term.</p>
        <h3>Water Signs</h3>
        <p>Water signs are a lovely match to Pisces sensitivity and emotional intelligence with the greatest affinity. They speak a similar soul language and share a psychic, creative, and intuitive current between them that transcends words.</p>
        <p>Cancer with Pisces is a sweet, sensitive, and caring match. Both are interested in healing service work and will love sharing secluded privacy. They make a good team and agree on how to create a harmonious home and life. They understand and empathize with each other’s deep moods, offering empathetic support to one another.</p>
        <p>Pisces and Scorpio share a love for the mystical and will likely explore spiritual and philosophical ideas to the relationship. This is a complementary pairing that is innately intuitive, creative, and otherworldly. They share a love for mystery and the inner workings of the mind and soul. Scorpio is the more daring of the two, inspiring Pisces out of its comfort zone.</p>
        <p>Pisces with Pisces potentially have the most affinity and understanding between them, however, they may be so much alike that they get lost in a world of their own making. They may be creative collaborators and explore spiritual practices together, but they will need to remember to make time for coming out of their meditative solitude and enjoy activities that keep them grounded.</p>
        <h3>Earth signs</h3>
        <p>Earth signs bring a complementary and elemental affinity to a relationship with Pisces since practical, structured earth and emotive water blend well; helping Pisces be more practical and grounded.</p>
        <p>Pisces and Capricorn are a good fit, with Capricorn offering patience and practicality to the Two Fishes dreamy world. Pisces reminds Capricorn of its mystical side, and Capricorn helps Pisces materialize its unique ideas. They are an inspiring, complementary pair, and have many beneficial resources to share.</p>
        <p>Pisces and Virgo are opposite signs in the zodiac wheel, which can create a complimentary or polarizing pair. Virgo offers structure and attention to detail to Pisces’ dreamy life, and Pisces helps Virgo to relax and just be. Each has a little something that the other needs, so together they could fill the whole picture, however, their differences may try the others’ patience at times.</p>
        <p>Pisces with Taurus is a lovely, pleasure-seeking match. Both enjoy taking their time together and exploring the sensory indulgences the world has to offer. Taurus helps Pisces ground into their bodies and supports their emotional needs patiently. Pisces helps Taurus to stay in touch with life’s mysteries and to not become too materialistic.</p>
        <h2>Pisces Health</h2>
        <h3>Constitution</h3>
        <p>In classical astrological medicine, four temperaments were connected to four vital fluids and four essential constitutions. Pisces is a water sign, and so is associated with the phlegmatic temperament, which was understood to be cold and moist. The phlegmatic temperament was thought to be connected to moisture and fats in the body and the production of phlegm, which lubricates tissues and protects these from infection. Phlegm, however, can be the source of imbalance for the phlegmatic constitution, often overproduced when Pisces falls ill or becomes inactive.</p>
        <p>This represents a tendency for the phlegmatic constitution to become somewhat chilled and bogged down physically and emotionally. Natives from this sign can become too clingy and sentimental in their moods, and overly retentive of water and other fluids in their bodies. Their tissues can become boggy, lax, and clogged with toxic substances and emotions, building up too much and not being adequately cleaned out.</p>
        <p>Pisces’ constitution has another layer that makes it unique, which comes from Jupiter’s traditional rulership over this sign. Jupiter is thought to be a hot and moist planet, which may in some ways help heat the coolness in the Piscean constitution. It does, however, bring extra moisture to the body, which can present as a build-up of gasses and congestion.</p>
        <p>Pisces natives have potential extra resiliency but may need to keep their bodies moving and circulating. It will be important for them to avoid mucus-forming foods, and to support adequate sweating and elimination.</p>
        <h3>Body Parts</h3>
        <p>In classical astrological medicine, the entire zodiac was mapped out on the human body, with Pisces ruling over the feet, and internally, the liver and lymphatic system. Their feet may be rather long, sensitive, and well-developed, with flexible finger-like toes. Pisces’ feet may be vulnerable to cold, joint pain, and disorders like arthritis and gout.</p>
        <p>The liver, being Jupiter’s organ, is also in need of protection and care. Similar to Sagittarius, Piscean natives will benefit from bitter foods and herbs that stimulate the digestive bile and help the liver cleanse their blood of toxins and hormonal byproducts.</p>
        <p>The lymphatic system is also a key area for these natives to support, as excess toxins, mucus, and stagnant fluids can block this cleansing system from circulating freely. The principle of osmosis seems to be an active force for the Piscean body, as they tend to absorb chemical and emotional impurities from their environments.</p>
        <p>They can also be prone to catching colds and viruses, and to take on the depression and frustrations of those in their lives. Whole unprocessed foods, immune-boosting remedies, and cleansing practices will help Pisceans protect their bodies and auras from disease.</p>
        <h2>Herbal Allies</h2>
        <p><strong>Lemon balm</strong>&nbsp;is a Pisces herbal ally, with a calming, aromatherapeutic fragrance and qualities that clear the liver and promote digestion. Being very Jupiterian, it tends to grow abundantly, and its tea and tinctures help calm the nervous system and stimulate bile to help promote fat digestion and liver function. With its anxiety soothing and uplifting properties, it can help comfort sentimental and sensitive Pisceans.</p>
        <p><strong>Wood Betony</strong>&nbsp;is also connected to Jupiter and has many unique benefits. Traditionally, it was used in herbal remedies for arthritis and gout, the latter being a disorder that Piscean feet can be vulnerable to. It also supports liver health and can be used to heal and clear the respiratory, digestive, and nervous systems. Wood betony can also be used to treat anxiety, gallstones, heartburn, high blood pressure, migraine, and neuralgia.</p>
        <p><strong>Sage</strong>&nbsp;has many culinary and medicinal uses that are especially supportive of Pisces. It is considered another Jupiterian plant and was called by the Romans “the holy herb.” Sage is of great use to the phlegmatic constitution, as it can help dry up the excess moisture and mucus these types can be prone to.</p>
        <p>It can stanch any excessive menstrual flow and can clear up the respiratory tract infections when treating colds. Sage also has an uplifting and clarifying quality and has been used to fight depression, mental fog, and Alzheimer’s symptoms.</p>
        <h2>Esoteric Pisces</h2>
        <h3>The Three Decans of Pisces</h3>
        <p>Each of the twelve zodiac signs represents a thirty-degree slice of a 360-degree band of constellations circling the earth. The thirty degrees of each sign can be further subdivided into 3 ten-degree decans or faces, each with its planetary sub-ruler placed around the zodiac in Chaldean order.</p>
        <p>These faces can be used for timing magical rituals when seeking to evoke and harness Jupiter’s planetary power. In studying the Piscean personality, we can use the faces of the Two Fishes to fine-tune the flavor and nuance of planets or points placed within these decanic degrees.</p>
        <h3>First Decan of Pisces: Saturn</h3>
        <p>Degrees 0 through 9 of Pisces are ruled by stern Saturn. This may heighten discipline, discernment, and boundary setting for those with planets or points in this face. Here, we may find some of the more grounded, serious, and old soul Pisceans compared to the other decans.</p>
        <h3>Second Decan of Pisces: Jupiter</h3>
        <p>Degrees 10 through 19 of Pisces are ruled by Jupiter. This is a powerful placement for Jupiter since Pisces is this benevolent planets’ nocturnal domicile. This decan heightens the Jupiterian powers, making those with planets and points in this face especially spiritual, mystical, and self-sacrificing. These natives are more likely to be religious teachers or mentors of some kind.</p>
        <h3>Third Decan of Pisces: Mars</h3>
        <p>Degrees 20 through 29 of Pisces are ruled by assertive and driven Mars. This can be a bit of an unusual combination, since Mars is a warrior planet, and Pisces is soulful and sensitive. This decan can have a theme of the spiritual warrior, where those with planets or points here are seen to take up charitable causes or to help the less fortunate. There also may be a suppression of anger, and an aversion to confrontation.</p>
        <h2>Pisces Tarot Cards</h2>
        <h3>Major Arcana: The Moon</h3>
        <p>The Tarot card that correlates to Pisces is number 18: The Moon. Regardless of its name, this card has been assigned Piscean qualities to its significations, carrying with it some Jupiterian and Neptunian sub-signatures.</p>
        <p>The mysterious and nocturnal realm that the Moon card depicts is the world of the Pisces archetype, which appears when we are feeling overwhelmed with emotions and are confused about what choice to make next. This card warns of the illusory quality of dreams, delusions, and ideals that can cloud our clarity at the moment. It also reminds us that when we are lost in a storm of feeling, we need to reconnect with our core and our authentic nature to navigate through an alternate reality.</p>
        <p>The Moon teaches us how to join the mystic with the tangible and accept that the two are one so that we do not become destabilized by fears, phobias, or old trauma signatures. Working with and accepting that reality is multifaceted by nature will help us release a need to control the outcome, or project our unrealistic desires onto our circumstances. It’s a rather mysterious card that is not always immediately positive but can help us find clarity and a path toward authenticity.</p>
        <h3>Minor Arcana</h3>
        <p><strong>8, 9, and 10 of Cups</strong><br>In the Minor Arcana of the Tarot, the Suit of Cups is associated with the element of water. Here, we see the three decans of Pisces assigned to the 8, 9, and 10 of Cups, cards associated with arriving at the end of an emotive, intuitive, and relational cycle. These Cup cards help us to recognize our feelings and instincts as we go deeper into the nuances of these to attain psychic mastery and fulfillment.</p>
        <p><strong>8 of Cups: Saturn in Pisces&nbsp;</strong><br>The 8 of Cups corresponds to the first decan or face of Pisces. It carries the reclusive sub-signature of Saturn and was referred to in the Book of Thoth as the card of “Indolence.”</p>
        <p>This card depicts a dejected figure appearing to abandon a scene of accumulation and investment. It points to a mood of disillusionment, when something creative or relational that we were working toward did not bring the happiness that we had hoped. There may be a need to withdraw and reflect, or there may be a temptation to avoid a problematic emotional situation, and simply escape.</p>
        <p>The “Indolence” card hints at a crisis of stagnation, symbolizing “Pisces is calm but stagnant water; and Saturn deadens it completely…” (Book of Thoth)</p>
        <p><strong>9 of Cups: Jupiter in Pisces</strong><br>The 9 of Cups corresponds to the second decan or face of Pisces. It carries the powerful and benevolent sub-signature of Jupiter in its home sign and was referred to in the Book of Thoth as the card of “Happiness.”<br>This card is more stable and prosperous than the previous card, and perhaps represents the resolution of number 8’s disillusionment. It depicts contentment, satisfaction, and can symbolize a wish coming true. It also echoes the joy and gifts that Jupiter can provide by inviting us to indulge in pleasures and creativity.</p>
        <p>The number 9 is numerologically dynamic and reminds us of the transient nature of our good fortune, and that we need to be ready to adapt if circumstances change. Therefore, it is important to be in the moment and enjoy fortune while it lasts.</p>
        <p>The “Happiness” card is “the pageant of the culmination and perfection of the original force of Water… (Book of Thoth)</p>
        <p><strong>10 of Cups: Mars in Pisces</strong><br>The 10 of Cups card corresponds to the third decan or face of Pisces. It carries the potent and assertive sub-signature of Mars and was referred to in the Book of Thoth as the card of “Satiety.”</p>
        <p>The number 10 card represents harmony, satisfaction, and bliss in relationships. It depicts the ultimate expression of this, in the loving, supportive family unit. This card symbolizes fulfillment, wholeness, and contentment that can be arrived at after working and evolving to find peace and emotional balance. We can now trust our well-developed intuition with confidence when moving forward.</p>
        <p>The “Satiety” card depicts the Pisces influence as “peaceful and spiritualized…” (Book of Thoth)</p>
        <p></p>
    </div>
</div>
</body>
</html>
