<%--
  Created by IntelliJ IDEA.
  User: elmirabajgulova
  Date: 31.10.2021
  Time: 00:21
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <meta name="viewport" content="with=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/styleHome.css">
    <link rel="stylesheet" href="css/styleZodiacSignsPages.css">
</head>
<body>
<h1>Sagittarius</h1>
<%@include file="/WEB-INF/top_nav.jsp" %>
<div class="grid__content">
    <div class="editorial-article__feed">
        <h2>Sagittarius Traits &amp; Overview</h2>
        <div class="zs-meta border-grey border-rad-4 grid-1c grid-sm-2c grid-lg-3c grid-c-gap-3 p-2 mb-3">
            <div class="meta-item"><span class="tag">Sagittarius Dates: </span><span class="tag--bold white">November 22 to December 21</span></div>
            <div class="meta-item"><span class="tag">Symbol: </span><span class="tag--bold white">The Centaur /&nbsp;Archer</span></div>
            <div class="meta-item"><span class="tag">Mode + Element: </span><span class="tag--bold white">Mutable Fire</span></div>
            <div class="meta-item"><span class="tag">Ruling Planet: </span><span class="tag--bold white">Jupiter</span></div>
            <div class="meta-item"><span class="tag">House:</span><span class="tag--bold white"> Ninth</span></div>
            <div class="meta-item"><span class="tag">Mantra: </span><span class="tag--bold white">I See</span></div>
            <div class="meta-item"><span class="tag">Body Parts: </span><span class="tag--bold white">Hips, Thighs, &amp; Liver</span></div>
            <div class="meta-item"><span class="tag">Colors:</span><span class="tag--bold white"> Maroon &amp; Navy blue</span></div>
            <div class="meta-item"><span class="tag">Tarot Card: </span><span class="tag--bold white">Temperance</span></div>
        </div>
        <p>Sagittarius, the ninth sign of the zodiac, is the home of the wanderers of the zodiac. It’s not a mindless ramble for these folks, either. Sags are truth-seekers, and the best way for them to do this is to hit the road, talk to others and get some answers.</p>
        <p>Knowledge is key to these folks since it fuels their broad-minded approach to life. Those born with a Sagittarius zodiac sign are keenly interested in philosophy and religion, and they find that these disciplines aid their internal quest. At the end of the day, what Sagittarius wants most is to know the meaning of life, and to accomplish this while feeling free and easy.</p>
        <h2>Sagittarius Symbolism + Myth</h2>
        <p>The Sagittarius zodiac symbol of the Centaur is based on the Greek mythological association with Chiron, the great teacher of music, medicine, hunting, and prophecy. Chiron healed the hero Achilles and mentored him in archery and many other great arts when he cared for him as a child. Achilles later grew to be victorious in the Trojan War, likely having learned to be brave and clever while under the tutelage of this benevolent centaur.<br>Sagittarius’ connection to travel, higher knowledge, and truth-seeking stem from the centaur race’s questing attributes, yet mostly from Chiron, who was the kindest, most generous and friendly to humans of them all. Being half-human and half-beast, the centaur/archer holds both an intelligent civilized side, and also an untamed, bestial nature, embodying a balance of primal instinct and wisdom.</p>
        <h2>Sagittarius Element, Mode, and Season</h2>
        <p>In the western tropical zodiac, Sagittarius season begins on November 22, commencing at the end of the Autumn in the Northern Hemisphere. It’s a time of year when the days have begun to get shorter, and the night begins to dominate. There is a feeling of change in the air as the last warm days of the fall begin to wane, and the hints of the oncoming cold, insular season of winter are beginning to take hold of the weather.</p>
        <h3>Mutable Mode</h3>
        <p>Sagittarius is the third of the four mutable signs of the zodiac, who all hold an elemental energy of change and adaptation at the transitional end of the four seasons. Sagittarius’ fiery and mutable presence begins to clear the stage for the next seasonal performance and helps describe Sagittarius’ restless, change-seeking, and adventurous nature.</p>
        <h3>Fire Element</h3>
        <p>Sagittarius’ element is fire, the lightest, brightest element, thought by ancient astrologers to be akin to the divine light of the stars and the vital, life-giving rays of the sun. Sag’s affinity for enthusiasm, truth-seeking, authenticity, and at times brutal honesty, is kindled in the fire element.</p>
        <p></p>
        <p></p>
        <h2>Sagittarius Planetary Rulership</h2>
        <h3>Domicile of Jupiter</h3>
        <p>In classical astrology, Jupiter was assigned rulership of both Pisces and Sagittarius. Sagittarius was thought to be the diurnal/day home of Jupiter, an adaptive fire sign that allows Jupiter to be as expansive, affirming, and joyful as it likes to be when placed there.</p>
        <p>Jupiter is the biggest planet in our solar system, reflecting the most amount of light from the sun, reason why it was called the “greater benefic” and was recognized as having the greatest power to bestow luck and good fortune of all the seven visible planets.</p>
        <p>This planetary rulership connection adds another layer to the natural qualities of Sagittarius, being the source of the sign’s affinity for optimism, friendliness, and enthusiasm. Those who are born with their sun placed in Sagittarius are big thinkers, truth-seekers, and love to engage in philosophical inquiries and debates. Those born with Jupiter in its fiery home of Sagittarius tend to have a strong baseline of optimism to fall back on and may have luck when following their highest beliefs and values.</p>
        <h3>Detriment of Mercury</h3>
        <p>Sagittarius is in polarity with the mutable air sign Gemini. Sagittarius likes to affirm, expand, and explore universal truths, where Gemini loves to analyze, preferring to focus on gathering small, fascinating details, using mischief to tease, prod, and disrupt. As a result, Mercury and its “mercurial” ways were traditionally thought to be in detriment, or at a bit of a disadvantage when placed opposite from its home in Sagittarius’ bold, brave, and unbounded world.</p>
        <p>It’s a placement that the planet of communications and language would have to compensate for to be in, finding creative ways to think and get important messages across. The result is often a tangential way of speaking and writing since those with this placement take the long way around when expressing themselves.</p>
        <p>With Jupiter’s influence, however, the focus of thought, speech, and learning is on understanding the unifying truths of life. And while Mercury in this sign seems to take a long time to get to the point, there is always a grand idea and a big-picture understanding in mind.</p>
        <p>Mercury in Sagittarius may challenge those born with this placement to edit and focus their awareness on one subject more deeply at a time, as they prefer to follow their curiosity to learn a little bit about a lot of topics.</p>
        <h2>Sagittarius House Rulership</h2>
        <h3>The Ninth House</h3>
        <p>In the modern astrology system of the Twelve Letter Alphabet, each zodiac sign rules one of the twelve houses in the birth chart. This innovation was created by psychological astrologers to match sign affinities to related house topics.</p>
        <p>Sagittarius was assigned the ninth house of foreign travel, higher learning, and spirituality, since it’s questing, adventurous, and curious nature has an affinity for these topics. Since Sagittarius is ruled by Jupiter, this modern astrology system invites an ebullient, expansive sub-signature to the significance of the ninth house.</p>
        <h3>The Eleventh House</h3>
        <p>In classical astrology, Sag’s planetary ruler, Jupiter, was said to find its “joy ” in the eleventh house of “good spirit” in the birth chart. This house, associated with friends, alliances, hopes, and gifts is a natural, affirming, and happy place for Jupiter to be.</p>
        <p>Since Jupiter likes to expand and dissolve boundaries, this house speaks to the opportunities that are available to us when we feel connected to a community and receive encouragement, validation, and support. The eleventh house is associated with alliances we form and gifts we receive in our public or social roles, perhaps as an extension of our career activities.&nbsp;&nbsp;<strong>&nbsp;</strong></p>
        <h2>Sagittarius Characteristics</h2>
        <h3>Personality</h3>
        <p>Sagittarius’ traits are derived from its active, masculine, or yang qualities, making this sign oriented toward assertive engagement with the outer world. Alive in both a Sagittarius woman or Sagittarius man, those born with the centaur as their rising, sun, or moon sign have enthusiastic energy in their core personality; like the joyous, benevolent qualities of Jupiter.<br>As a mutable sign, the Centaur holds the power to be a change-maker, giving those with prominent Sagittarius in their charts a natural affinity for adaptation, exploring the world, as well as teaching and practicing diverse forms of spiritual devotion and philosophy. Ruled by expansive Jupiter, Sagittarius natives can be thought of as the “seekers” of the zodiac who like to expand their minds by seeking out new perspectives and experiences.</p>
        <h3>Strengths</h3>
        <p>The primary strength of Sagittarius is their optimism. Being born with a bold, jovial disposition, Sagittarius natives usually find it easy to feel happy, enthusiastic, and to see the bright side of life. Being influenced by Jupiter’s affirming and confident nature, Sagittarians rarely succumb to self-doubt and are usually able to propel themselves forward in life, believing that everything will work out for the best.</p>
        <p>The Centaur’s thirst for travel and adventure takes on an epic significance, where they see their lives unfolding like the plot of a mythopoetic tale, always carrying them to the right place, at the right time. Since their lives are likely to be filled with fascinating experiences, they are typically wonderful storytellers and great teachers, weaving universal messages of truth and inspiration into their lessons and tales.</p>
        <p>Personal integrity is very dear to Sagittarians, and they will have a difficult time following the status quo or suffering what they feel to be false or inauthentic roles, ideas, or laws. When a Sagittarius feels moved by a cause, they’ll express what’s in their minds and hearts with great zeal, and conviction.</p>
        <p>Like their fire sign neighbors, you will always know where you stand with a Sagittarius, but since they aspire to a sense of higher philosophy and greater truth, they rarely hold a grudge or have time to be petty.</p>
        <p>Sagittarians are very unlikely to be possessive or materialistic since their lives prioritize being able to change, move, and adapt easily. Though they can be non-committal, they are also rarely jealous, extending the same freedoms to others that would also love to enjoy themselves.</p>
        <h3>Weaknesses</h3>
        <p>Some sources of weakness for Sagittarius are rooted in their great strengths. Being a mutable fire sign, Sagittarius will passionately state their opinions or principles in the moment, yet reserve the right to always change their mind, stating just as passionately their new views later on. This can be disorienting for others who were sure they knew their Sag colleague’s position on a matter, giving them a reputation for being unpredictable, or at times unreliable.</p>
        <p>Due to their adventurous spirit, and love of change and travel, Sags are famously non-committal when it comes to plans, as they also reserve the right to change their agendas with their moods. When trying to get a Sagittarius lover to commit to a long-term relationship, people need to manage their expectations, as this fire sign loves to live in the moment and can sometimes break the hearts of those they leave behind.</p>
        <p>The Archer’s optimism is generally positive, and even infectious, but they can become so enamored with their ideals that they become very ungrounded and unrealistic, finding regular life and its limitations to be inconvenient as well as disappointing. Sagittarius children, especially, will benefit from guidance on how to add healthy structure and commitment to their lives and friendships, so that they grow up with a sense of support when they need it most.</p>
        <p>In classical astrology, Jupiter is associated with wise teachers and kings, giving natives from this sign a bold, authoritative way of speaking. This can verge on condescension, however, if they are not respectful of those they are communicating with, giving the other party the feeling of being spoken down to, or arrogantly dismissed. Like all fire signs, Sagittarius will have to manage their impulsivity, impatience, and short temper, which can present as the Centaur’s famous “brutal honesty”.</p>
        <p></p>
        <p></p>
        <h2>Sagittarius Life Purpose and Career</h2>
        <h3>Mantra and Purpose</h3>
        <p>The voice of optimism, enthusiasm, and thirst for adventure comes forward in the Sagittarius mantra: <strong>I see</strong>. The Archer’s sense of purpose is all about seeking the universal truths of life, and this sign will go to the very ends of the earth to “see” and experience all that life has to offer for themselves.<br>We all have Sagittarius somewhere in our <a href="https://www.astrology.com/birth-chart/">birth chart</a>, so we can look to the house this sign rules to find the specific area of life we approach in an expansive, optimistic way, or where we need to call in the Centaur’s optimistic energy for mastery.</p>
        <p>Sagittarius people tend to be drawn to any pursuit where they can grow on a spiritual level and teach others to do the same. Traveling, motivating, public speaking, sharing knowledge, adventure, and enlightenment will provide Sagittarians an outlet for their adaptable, fiery energy.</p>
        <h3>Sagittarius at Work</h3>
        <p>Sagittarius’ sense of free-spirited optimism and adventure makes them uniquely suited for professions where they are trailblazers of some kind, creating their own roles and opportunities in the world so they can earn a living with their diverse and eclectic interests. Their careers need to be challenging and dynamic enough to fulfill their adaptive natures. Sagittarius’ warmth and idealism will likely be their strong suit, so jobs in which they can teach, inspire, and work for a higher cause or purpose will be best.</p>
        <p>This could manifest in many professions, but likely will not be found in staid, routine-type jobs that require laboring over finicky details or analysis. Like all the fire signs, Sagittarius needs challenge, movement, and space, so will not be content for long in the same location unless of course, that location is in an exotic place! If they do have a sedentary aspect to their work, they need to counterbalance this with vacations, movement practices like yoga, and enjoying multi-cultural events and activities.<br>Since Sagittarius is ruled by Jupiter, the planet of optimism, higher truths, and expansion, a natural vocational fit could potentially be found in activism. Any way that a Sag native can take an active role in teaching and inspiring positive change, growth, and a sense of collective unity will likely be most fulfilling.</p>
        <p>Teaching is another profession, with Jupiter, the ruler of Sagittarius, being connected to higher learning and wisdom. This could be any subject that the native feels connected to and passionate about and could be at a university level, sharing philosophy, multi-cultural, and even religious studies.</p>
        <p>Since Sagittarians lean toward activism and preserving integrity, and are often great advocates of the underdog, any facet of law could be fulfilling. Sagittarians can have great empathy for human struggle, often having to carve an unconventional path themselves in life. Jupiter is associated with justice and higher values, often guiding these folks toward realizing these ideals.</p>
        <p>In classical astrology, Jupiter is connected to spirituality and spiritual teachers, also being associated with “gurus” in Vedic astrology, so being a spiritual leader of some kind would be an appealing, natural fit for Sagittarians. This could be within any belief system the native is connected to, placing them in leadership roles in community churches, at the local yoga studio, or even in coaching.</p>
        <p>Sagittarians tend to have a natural curiosity for, and a knack for languages, so jobs in writing, storytelling, or even translation would be appropriate for the articulate and well-studied Centaur.</p>
        <p>With a love of travel and adventure, Sagittarians could make excellent tour guides, where they can combine their social gifts for storytelling, higher knowledge of local culture, and love for nature in a dynamic and fun role.<br>As with all fire signs, Sagittarians have athletic leanings, so working in the fields of sport and movement may be appealing. Though Centaurs love to be active, they may not be particularly status-seeking, ambitious, or competitive; and may participate in sport for the joy and camaraderie and can make great team coaches, or even practitioners of sports medicine.</p>
        <h2>Sagittarius Compatibility</h2>
        <p>When exploring overall compatibility in astrology, it’s important to take more than the sun sign into consideration, as the rising sign, moon, and other planetary cross-connections will tell the whole story in relationships. That being said, Sagittarius natives will tend to blend best with fire signs and air signs; and may need to work harder on relationships with water signs and earth signs.</p>
        <h3>Fire signs</h3>
        <p>Sagittarius will typically find great affinity in other fire signs, as they will understand each other’s impulsive, spontaneous nature. Aries can handle the Archer’s heat and brutal honesty and is independent enough to not feel left behind when Sagittarius’ life takes them out of town. The two will be active and lively together.</p>
        <p>Sag with Leo can be a wonderful, inspiring, creative duo, but Leo may need more attention and assurance than free-spirited Archer can sometimes provide. Sagittarius with Sagittarius can be a great match, with affinity, understanding, and long-distance arrangements.</p>
        <h3>Air signs</h3>
        <p>Air signs bring a natural complementary energy to Sagittarius, as air feeds fire, stoking it to grow and become more alive. Aquarius and Libra bring intelligence and curiosity to Sagittarius’ inspired and adventurous world.<br>Gemini, ruled by Mercury, brings playfulness, curiosity, and mischief to Sag’s adventurous life; and the two can have a complimentary or polarizing relationship. Sagittarius can teach Gemini to keep their eye on the bigger picture, and not get too fixated on small details, and Gemini can challenge Sagittarius’ idealism by keeping them from getting too grandiose.</p>
        <h3>Water signs</h3>
        <p>Water signs may have the biggest challenge when relating to this sign, even though they may bring emotional intelligence to help cool and counterbalance Sagittarius’ bold, enthusiastic, and wandering tendencies.<br>Cancer will be very good at caring for Sagittarius, which they will love, but Cancer may prefer to stay at home while Sagittarius roams the globe. Pisces will potentially share some spiritual and philosophical affinities with Sagittarius, with both signs being classically ruled by expansive Jupiter, yet may be too sensitive and private to fully appreciate the Archer’s brutal honesty.</p>
        <p>Scorpio can bring sexual potency to a relationship with Sagittarius, but with Scorpio’s jealous tendencies, this is a potentially volatile match for the free-spirited Archer, who prefers to live in the moment.</p>
        <h3>Earth signs</h3>
        <p>Earth signs can potentially stabilize Sag’s zealous nature, with Capricorn, the authoritative cardinal earth sign, having the fortitude to stand their ground in the face of Sag’s hubris.</p>
        <p>Taurus, although dependable and loving, may be a bit too stubborn and rooted to roll with Sagittarius’ ever-changing plans.<br>Virgo may be too demure and focused on doing things perfectly to enjoy Sag’s wild, untamed tendencies.</p>
        <p>In general, when Sagittarius joins forces with earth signs in work, they can cover a lot of ground together, with earth signs offering the practical realism to help Sag natives follow through on their inspirational ideas.</p>
        <h2>Sagittarius Health</h2>
        <h3>Constitution</h3>
        <p>In classical medical astrology, there were four temperaments, that were connected to four vital fluids, and four essential constitution types. As a fire sign, Sagittarius is associated with a more moderate version of the choleric temperament, which was thought to be hot and dry, and connected the production of digestive bile.</p>
        <p>Since Sagittarius is ruled by Jupiter, this gives Sagittarians an additional mix of the sanguine constitution, which is warm and moist, and prone to dissipation of energy and digestive gasses. Those born with Sagittarius rising, especially, may present the fiery physicality of an athletic body, who may tend to run hot physically and emotionally, making them vulnerable to restlessness, dehydration, and overheating.</p>
        <h3>Body Parts</h3>
        <p>In classical astrology medicine, the entire zodiac was mapped out on the human body, with Sagittarius ruling over the hips and thighs, and internally, the liver. As a result, those with Sagittarius may have strong legs but may need to protect themselves from strain or overuse of thigh muscles, bones, and hip flexors.</p>
        <p>The liver is a very Jupiterian organ, being large and expansive, and ever regenerating, much like its planetary ruler, so it is a special organ of focus for this sign. It’s important that liver care is incorporated into the Centaur’s diet so that it does not become overburdened or toxic.</p>
        <p>Sagittarius natives need to keep their diets and exercise in balance with their love of celebrating life with good food and drink. They can keep their systems cool and stress levels low with calming, relaxing practices, fiber-rich fruits and vegetables, and good hydration.</p>
        <h2>Herbal Allies</h2>
        <p><strong>Dandelion root&nbsp;</strong>is a prime Sagittarius herbal ally, with its primary benefits being helpful, supportive, and healing for the liver. Loaded with antioxidants and anti-inflammatory properties, it is protective against cellular damage caused by free radicals in the system. Dandelion root supports digestion, reduces water retention, and helps cleanse excess fats from the liver. It can be moderately cooling and drying, helping to calm excess heat and moisture in the stomach and liver, as well as in the Sagittarian body system that tends to overheat.</p>
        <p><strong>Lemon balm&nbsp;</strong>is another Sagittarius ally, with a calming fragrance and qualities that clear the liver and promote digestion. Being a Jupiterian herb, it tends to grow abundantly, and its tea and tinctures help calm the nervous system and stimulate the bile to help promote fat digestion and liver function.</p>
        <p>It was said by classical physicians to “purge” melancholy, a state of dryness and coldness in the body that leads to stiffness and depression, so it can be used to emphasize warm and relaxed qualities where these are deficient.<br><strong>Yellow dock&nbsp;</strong>is an example of another Jupiterian plant, whose leaves can be eaten in salads and carry much of the same minerals and vitamins as spinach. Yellow dock was said to be cooling, drying, and strengthening to the liver by Culpepper, who recommended its tea to cleanse and cure boils and infections of the sinuses and respiratory tract. Yellow dock contains constituents that have a stimulating and laxative effect on the bowels, which helps to ease constipation and to flush out an overburdened liver.</p>
        <h2>Esoteric Sagittarius</h2>
        <h3>The Three Decans of Sagittarius</h3>
        <p>Each of the twelve zodiac signs represents a thirty-degree slice of a 360-degree band of constellations, circling the earth. The thirty degrees of each sign can be further subdivided into three ten-degree decans, or faces, each with its own planetary sub-ruler placed around the zodiac in Chaldean order.</p>
        <p>These faces can be used for timing magical rituals when seeking to evoke and harness Jupiter’s planetary power. In studying the Sagittarius personality, we can use the faces of Sagittarius to fine-tune the flavor and nuance of planets or points placed within these decanic degrees.</p>
        <h3>First Decan of Sagittarius: Mercury</h3>
        <p>Degrees 0 through 9 of Sagittarius are ruled by Mercury. This is the detriment of the messenger planet, making those with planets in the first decan very expansive and creative in their language use, but also highlights some potential struggles with intellectual focus and discipline.</p>
        <p>In terms of personality, the first decan of Sagittarius can be more analytical and inclined toward gathering and sharing information than the other decans of Sagittarius. This makes them potentially great orators, storytellers, and teachers, but can also amplify their tendency to be overly enthusiastic and verbose when speaking. This gift may shine best in the classroom, or in roles of spiritual inspiration and motivation.</p>
        <h3>Second Decan of Sagittarius: Moon</h3>
        <p>Degrees 10 through 19 of Sagittarius are ruled by the moon, making those born with planets here more inclined toward emotional enthusiasm and impulsivity. The nurturing and caring qualities of the moon blend with the passionate and inspirational tendencies of Sagittarius to bring forward very bold expressive feelings as well as demonstrations of these. The changeable qualities of the moon blend with Sagittarius’ mutable fire, creating a potential for mood swings in those with planets in this decan.</p>
        <h3>Third Decan of Sagittarius: Saturn</h3>
        <p>Degrees 20 through 29 of Sagittarius are ruled by Saturn, the planet of duty, determination, and perseverance. Saturn’s influence here potentially focuses and stabilizes the impulsive tendencies of Sagittarius and can make those born with planets in the third decan of Sagittarius more sober, realistic, and patient.</p>
        <p>Sagittarius typically likes to say “yes” to life and experience, but Saturn’s serious and pragmatic influence tempers these Sagittarian tendencies, making them more able to set boundaries and conditions on their activities and explorations.</p>
        <h2>Sagittarius Tarot Cards</h2>
        <h3>Major Arcana: Temperance</h3>
        <p>The Tarot card that correlates to Sagittarius is number 14: Temperance. This card depicts a calm and focused angelic character, masterfully balancing a flow between two chalices. The angel of Temperance has one foot on land, and one foot in the water, showing a harmonious blend between stability and fluidity that lays between intuition and the ability to materialize.<br>The Temperance card speaks to the temperate nature and mindset that can help harness Sagittarius’ naturally expansive and enthusiastic spiritual belief and exploration, helping to hone the insights gained into something sustainable and attainable in the material world.</p>
        <h3>Minor Arcana</h3>
        <p><strong>8, 9, and 10 of Wands</strong><br>In the Minor Arcana of the Tarot, >the Suit of Wands is associated with the element of fire. Here we see the three decans of Sagittarius assigned to the 8, 9, and 10 of wands, cards associated with the management of inspiration and creative energy. These cards depict an important passage in harnessing the power of fire by developing spiritual awareness, mastery, and faith in our highest ideals.</p>
        <p><strong>8 of Wands: Mercury in Sagittarius</strong><br>The 8 of Wands corresponds to the first decan or face of Sagittarius. It carries the sub-signature of Mercury and was referred to in the Book of Thoth as the card of “Swiftness”. This card appears when we are becoming restless and are trying to bring a project or pursuit to a swift end. It reminds us of the importance of thorough completion, before inviting in the new.</p>
        <p>The “Swiftness” card also represents “the subtilizing of the fiery energy and the phenomena of speech, light, and electricity.” (Book of Thoth)</p>
        <p><strong>9 of Wands: Moon in Sagittarius</strong><br>The 9 of Wands corresponds to the second decan or face of Sagittarius. It carries the sub-signature of the moon and was referred to in the Book of Thoth as the card of “Strength.” This card appears to remind us to not react emotionally or subjectively to our current challenges and problems; when becoming lost in our feelings may cloud our judgment.</p>
        <p>The “Strength” card also explores “the fullest development of the (life) force in its relation with the forces above it and the phenomenon of change as stability.” (Book of Thoth)</p>
        <p><strong>10 of Wands: Saturn in Sagittarius</strong><br>The 10 of Wands corresponds to the third decan or face of Sagittarius. It carries the sub signature of Saturn and was referred to in the Book of Thoth as the card of “Oppression.” This dynamic card appears when we are taking on more than we can sustain or manage; and reminds us to be disciplined in relation to our current responsibilities.</p>
        <p>The “Oppression” card explores fire in its most potentially destructive aspect, “if its power becomes detached from its spiritual sources, it has become a blind (life) force” without moderating influences.” It also explores the dichotomy between sign and planet, and the challenge of harmonizing these; “Sagittarius is spiritual, swift, light, elusive, and luminous, and Saturn is material, slow, heavy, obstinate, and obscure.” (Book of Thoth)</p>
    </div>
</div>
</body>
</html>
