<%--
  Created by IntelliJ IDEA.
  User: elmirabajgulova
  Date: 31.10.2021
  Time: 00:21
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <meta name="viewport" content="with=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/styleHome.css">
    <link rel="stylesheet" href="css/styleZodiacSignsPages.css">
</head>
<body>
<section class="sub-header">
    <%@include file="/WEB-INF/top_nav.jsp" %>
    <h1>Scorpio</h1>

</section>
<h1>Scorpio</h1>
<div class="grid__content">
    <div class="editorial-article__feed">
        <h2>Scorpio Traits &amp; Overview</h2>
        <div class="zs-meta border-grey border-rad-4 grid-1c grid-sm-2c grid-lg-3c grid-c-gap-3 p-2 mb-3">
            <div class="meta-item"><span class="tag">Scorpio Dates: </span><span class="tag--bold white">October 23 – November 21</span></div>
            <div class="meta-item"><span class="tag">Symbol: </span><span class="tag--bold white">The Scorpion</span></div>
            <div class="meta-item"><span class="tag">Mode + Element: </span><span class="tag--bold white">Fixed Water</span></div>
            <div class="meta-item"><span class="tag">Ruling Planet: </span><span class="tag--bold white">Mars &amp; Pluto</span></div>
            <div class="meta-item"><span class="tag">House:</span><span class="tag--bold white"> Eighth</span></div>
            <div class="meta-item"><span class="tag">Mantra: </span><span class="tag--bold white">I Transform</span></div>
            <div class="meta-item"><span class="tag">Body Parts:</span><span class="tag--bold white"> The Genitals &amp; the Bowels</span></div>
            <div class="meta-item"><span class="tag">Colors:</span><span class="tag--bold white"> Red &amp; Black</span></div>
            <div class="meta-item"><span class="tag">Tarot Card: </span><span class="tag--bold white">Death</span></div>
        </div>
        <p>Scorpio is the eighth sign of the zodiac, and that shouldn’t be taken lightly—nor should Scorpios! Those born under this sign are dead serious in their mission to learn about others. There’s no fluff or chatter for Scorpios, either; these folks will zero-in on the essential questions, gleaning the secrets that lie within.</p>
        <p>The Scorpio zodiac sign concerns itself with beginnings and endings, and is unafraid of either. They also travel in a world that is black and white and has little use for gray. The curiosity of Scorpios is immeasurable, which may be why they are such adept investigators.<br>The folks with a Scorpio horoscope sign love to probe and know how to get to the bottom of things. The fact that they have a keen sense of intuition certainly helps.</p>
        <h2>Scorpio Symbolism + Myth</h2>
        <p>The constellation known as Scorpio goes back to Babylonian times, where it was called “the creature with the burning sting.” Scorpio contains the red star Antares, which means “the rival of Mars,” and is also called “the heart of the Scorpion.” This potent fixed star is observed in various astrological and magical practices as having an intense Mars-like quality.</p>
        <p>In Greek mythology, the Scorpion is associated with the death of Orion. There are many versions of this tale, but the one connected to Scorpio tells of a boastful hunter Orion, who bragged that he could kill all of the animals in the wild kingdom.</p>
        <p>The earth goddess Gaia objected and sent a Scorpion to stop Orion. He confronted, and fought the Scorpion, but died when the great beast stung him in the head. The Scorpion was placed in the heavens as a reward from Gaia for his service, and Zeus placed Orion there as well to commend his valiant fight.</p>
        <h2>Scorpio Element, Mode, and Season</h2>
        <h3>Mid-autumn</h3>
        <p>Scorpio season in the western tropical zodiac begins on October 23, commencing the middle of the autumn in the Northern Hemisphere. This is the time of year when the sun’s heat and light are beginning to wane, with the darkness of night beginning to outweigh the daylight hours.</p>
        <p>From this point, the days continue to decrease in length toward the Winter Solstice. It is during Scorpio’s time that many world cultures observe themes of death and rebirth, in holidays like Halloween, Samhain, All Saints Day, and El Día de Los Muertos. Scorpio’s connection with inward reflection, the shadows, and transformation is mirrored in the mystery and melancholy of the Autumn season.</p>
        <h3>Fixed Mode</h3>
        <p>Scorpio is the third of the four fixed signs of the zodiac, who all hold the elemental energy of endurance and stability in the center phase of the four seasons. Scorpio begins the middle of Autumn, when the season is most “fixed” and established, lending to the deep, tenacious, and obsessive tendencies of Scorpio.</p>
        <h3>Water Element</h3>
        <p>Scorpio’s personality traits are related to its element, which is water, the second heaviest element, thought by ancient astrologers to be the fluid, adaptive, yet a tangible form of matter. Water represents the moistening and cohering principle that binds and connects all forms of nature.<br>Without it, nothing that takes a material form could “stick” together. Water fertilizes earth so that nature and creativity can incubate and bloom. Scorpio’s creativity, intuition, imagination, and strong investigative powers are all akin to the consolidating connectivity of the water element.</p>
        <p></p>
        <p></p>
        <h2>Scorpio Planetary Rulership</h2>
        <h3>Domicile of Mars</h3>
        <p>In classical astrology, Mars is the planetary ruler of both Aries and Scorpio. Aries was thought to be the day, or diurnal home of Mars, with Mars finding a second nocturnal home in brooding and secretive Scorpio.</p>
        <p>In Scorpio, Mars has full affinity and potency in the warrior-like tendencies of this sign, but because it is in its nocturnal home, these powers take on a more secretive and covert expression. This placement presents in a slower, cooler, and more calculated use of anger and drive.</p>
        <p>Scorpio is more patient, and emotionally and psychologically nuanced than brash and brazen Aries. Those born with Mars in Scorpio can be more tactical and observant to wield behind the scenes of power. The motto “revenge is a dish best served cold” suits this tenacious and fixated archetype.</p>
        <h3>Modern Ruler: Pluto</h3>
        <p>The planet Pluto, named for the god of the underworld, was discovered during a pivotal time in modern history. Found by astronomer Clyde Tombaugh in 1930, Pluto appeared out of the darkness through theories of a trans-Neptunian planet. At the time, many powerful Plutonian synchronicities were happening in the world, like massive world wars, the exploration of depth psychology, and the splitting of the atom. The latter discovery saddled humanity with the responsibility and ability to unleash mass destruction never seen before.</p>
        <p>Astrologers of the modern era assigned Pluto as a co-ruler of Scorpio, since it’s dark themes of power, destruction, and inner discovery were similar to the themes this mysterious archetype explores. Combined with the assertive power of Mars, Scorpio’s Plutonian sub-signature makes this archetype uniquely suited to confront and transform personal and collective trauma.</p>
        <h3>Detriment of Venus</h3>
        <p>Scorpio is in polarity with the fixed earth sign Taurus. Ruled by Mars, Scorpio likes to confront and conquer, where Taurus, ruled by Venus, likes to connect and keep the peace. Venus, when in the opposite sign of her preferred home, is said to be in detriment, or at a sort of disadvantage in Scorpio.</p>
        <p>Imagine the planetary goddess of love, luxury, and attraction having to stay in a secret military bunker, with only weapons and war trophies as the resources to make a life. With this sign placement, she would have to compensate, with Venus in Scorpio natives often being private, secretive, and perhaps mistrustful in love. They may have frequent conflicts in following their passions and may be overwhelmed by their desires and emotional attachments.</p>
        <p>Those born with this placement have a do or die attitude when it comes to love, either going all-in or becoming vengeful if they are scorned. Love, affection, and connection may either be somewhat fraught for these natives, or very potent, exciting, and outside the norms of society. The passion and friction that this placement produces may be channeled into the artistic pursuits of these creative individuals.</p>
        <h3>Fall of the moon</h3>
        <p>Since the moon is said to be exalted in Taurus, it is in its fall in the opposite sign of Scorpio. While not as challenging to integrate as a detriment, the fall shows the emotional “pitfalls” that those with this placement may fall into. Here, the moon’s nurturing and receptive qualities are concentrated and intensified in this fixed water sign.</p>
        <p>The moon in Mars’ nocturnal sign can heighten the powers of intuition and concentration, but can also exacerbate dark moods. Those with this placement often have a potent, all-encompassing emotional life, that is deep and shadowy. These natives could face many inner demons and are also acutely aware of the psychic imbalances of others in their sphere.<br>On the positive side, the moon in Scorpio is often found in the charts of uniquely creative and intuitive people who make great investigators, psychologists, or psychic counselors. People with this placement may need to do a lot of their healing and soul-tending to keep their psychic boundaries clear when working and living with others.</p>
        <h2>Scorpio House Rulership</h2>
        <h3>The Eighth House</h3>
        <p>In the modern astrology system of the Twelfth Letter Alphabet, each zodiac sign rules one of the twelve houses in the birth chart. This innovation was created by psychological astrologers to match sign affinities to related house topics.</p>
        <p>Scorpio was assigned the eighth house of endings, death, and inheritances since Scorpio’s dark territory seemed aligned with the concerns of this house. Since Scorpio is ruled by assertive Mars, and potent Pluto, it invites these transformative planetary sub-signatures to the eighth house.</p>
        <h3>The Sixth House</h3>
        <p>In traditional astrology, Scorpio’s planetary ruler Mars was said to find his “joy” in the sixth house of “bad fortune,” health, and service of the birth chart. This is related to Mars classically being considered one of the more difficult, or “malefic” planets in astrology, responsible for conflicts, violence, and injuries in the life of these natives when badly placed.<br>Since the sixth house has a connection to health challenges and hard luck, Mars can “joyfully” express its more unwelcome offerings here, or at least has a leg up on being “extra-Marsy” and powerful.</p>
        <h2>Scorpio Characteristics</h2>
        <h3>Personality</h3>
        <p>Scorpio’s archetypal traits are derived from its receptive, feminine, or yin qualities, making this sign oriented toward contemplation and engagement with inner awareness. Alive in both a Scorpio woman or Scorpio man,< those born with the Scorpion as their rising, sun, or moon sign have a mysterious, intuitive, and power-wielding dynamic in the core of their personality, an echo of the shadowy Autumn season.</p>
        <p>As a fixed sign, Scorpio holds the qualities of being a sustainer, being able to apply profound powers of concentration to projects, and discovering hidden truths. As a result, those with the sign of the Scorpion prominent in their charts tend to be magnetic, highly sensitive, intuitive, creative, and secretive at times.</p>
        <h3>Strengths</h3>
        <p>The primary Scorpio strengths can be found in their devoted, determined, and observant natures. They are hard workers, often artistic, and deeply committed to study and research. You can count on the Scorpion to see whatever they have committed to through to the end.</p>
        <p>Scorpios tend to be receptive and patient, letting others play their cards and show their intentions first to better understand the emotional and psychological dynamics of their relationships. Magnetic and mysterious, Scorpio is drawn toward dark, taboo, or occult subjects, and are curious about the hidden facets of life that others may shy away from.<br>The Scorpion tends to be fearless in the dark, avoided, and mysterious inner depths of the psyche, and potent realities of life like death and transformation. While Scorpio is often misunderstood and feared as an archetype, those born under this sign are very sensitive, empathetic, and can be quite compassionate.</p>
        <p>They passionately bond themselves, heart and soul, to those they care for. Once they feel they can trust, they are quite loyal to the friends and lovers that make it into their inner circle. Scorpio understands innately what it feels like to be the weirdo or the outsider, and they have a natural connection to the underdog or those who are deemed untouchable in society.</p>
        <p>Because of this, they are uniquely poised to be of great service to those in our society that suffer the most, like the homeless, the mentally ill, and people who have been outcast for divergent spiritual beliefs or lifestyles.<br>Anyone with preferences that challenge conventional sexual, spiritual, and social ideas are potentially the Scorpion’s greatest allies and sources of affinity and acceptance. Scorpio can take emotional intelligence, understanding, and healing to the darkest circumstances, and may have had to overcome some healing or transformative experience of their own in their lives. Their fearless understanding of trauma, and survival, makes these folks the strongest psychic and spiritual warriors.</p>
        <h3>Weaknesses</h3>
        <p>Some potential weaknesses in the Scorpio archetype are rooted in their great strengths. Though they are determined and devoted to their work, they can become so rigid, fixated, and obsessed that it can be difficult to adapt to changes or to let go of an idea that is no longer useful.</p>
        <p>Those born under the sign of the Scorpion are receptive and patient, but they can be suspicious and slow to trust. Others may be forthcoming about their vulnerabilities, but if Scorpios are feeling insecure, they can use what others have revealed to be emotionally manipulative and controlling. Like the other fixed signs, they can be slow to forgive, and those that cross the Scorpion may feel their vengeful sting.</p>
        <p>Being naturally drawn to taboo and occult subjects can have the Scorpion inordinately focused on the dark side of life, giving them a pessimistic and nihilistic worldview. They may start seeking darker motives everywhere, which can lead to isolation and paranoia. It can then be hard to relax, trust, and enjoy life’s simple pleasures to stay in balance.</p>
        <p>Naturally sensitive and passionate, those born under the sign of the Scorpion give themselves heart and soul when seeking love and sexual connection, but if this isn’t reciprocated with the same intensity, they can become needy and obsessive with their lovers.</p>
        <p>Because of their co-relation with planet Pluto, Scorpios are often drawn to go beyond the fringes of society to seek thrill and adventure, yet this can easily lead the Scorpion into danger and self-destruction. Like a moth to a flame, they are lured toward intensity, but this may not always be in their best interest.</p>
        <p>Like all water signs, Scorpio is vulnerable to absorbing toxic energies, so if they are offering healing or counseling work, they need to have cleansing practices. Breathing exercises, saunas, smudging, and protective aura visualizations are all ways the Scorpio native can maintain psychic health.<br>Scorpios may need to seek and maintain healing of their own before they engage in service work. Moon in Scorpio natives, especially, may have to work through dark moods and depression at times in their lives.<br>Scorpio children will be well-nurtured if they are accepted unconditionally, and not shamed for having unique interests or big life questions. Acceptance at home may help offset a teenage Scorpio’s rebellion, and challenging artistic pursuits or martial arts may keep these fearless natives positively occupied.<br></p>
        <p></p>
        <p></p>

        <h2>Scorpio Life Purpose and Career</h2>
        <h3>Mantra and Purpose</h3>
        <p>The voice of depth, mystery, and intuition comes forward in the Scorpio mantra:<strong> I transform.</strong> The Scorpion’s sense of purpose is all about plumbing life’s shadows to uncover hidden truth and to attain power. Operating in fixed mode, Scorpios direct their intense laser focus into their work, projects, and relationships. These take on an all-encompassing mythic proportion, as those born under the sign of the Scorpion live their lives actively exploring the unseen depths of the soul.</p>
        <p>We all have Scorpio somewhere in our birth chart, so we can look to the house that this sign rules to find the specific area of our life we approach in a driven and intuitive way, or where we need to call in penetrating magnetism and mastery.</p>
        <h3>Scorpio at Work</h3>
        <p>Scorpio’s focused and determined nature makes them uniquely suited for professions where they are needed either to solve a problem or mystery, or to make a discovery. This could take form in many professions and roles, but will likely not be found in jobs that are overly multi-faceted and distracting. While they are intelligent enough to multi-task, they prefer not to, and do their best work when they are left to manage themselves and concentrate.</p>
        <p>Once on a trail, they will keep digging and uncovering until they get to the root of what they want to know. While content to work independently, they can be important team players, as they have an innate understanding of human nature and psychology. And while they don’t make a big show of it in the workplace, they are usually wielding power and authority behind the scenes.</p>
        <p>The Scorpion is a nocturnal creature, and so we may find these folks working through the quiet hours of the night making great progress while the world is asleep.</p>
        <p>Scorpios are likely to have a talent for research. With their keen focus and knack for recognizing patterns, they will work well in many fields like medicine, science, and mental health. They may even design or conduct experiments, collecting and evaluating their discoveries and observations.<br>All behind the scenes or after-hours work are well suited to Scorpio, making them naturals at investigative work. These natives will be drawn to being private investigators, detectives, and even secret service or espionage agents.</p>
        <p>Mars-ruled Scorpios are similar to Aries natives in that they may be suited for many facets of the military or martial arts. These fields take them fearlessly into the most physically and psychologically challenging scenarios, which they excel at by overcoming limitations.<br>With the Plutonian sub-rulership, we may find many Scorpios drawn to dark, underground work, perhaps as miners or geologists. Those born under the sign of the Scorpion may also be drawn toward professions handling the dead, as cemetery workers, morticians, or funeral home directors.</p>
        <p>With strong mystic talents, Scorpios study the occult, and may themselves be leaders in this mysterious world. This unique skill could take many forms, such as astrologers, psychics, tarot readers, or spiritual teachers.<br>As a water sign, Scorpio has potent healing powers and may take various roles in medicine and mental health. We may find these natives becoming our steadiest surgeons, our brightest psychologists, and most precise pharmacists. Scorpio natives would also be suited for roles as hospice workers, death doulas, or grief counselors, bravely attending to those in their darkest hours.</p>
        <p>Those born under the sign of the Scorpion have deep, creative souls. They are often musical and artistic, and may explore themes of power and potency in their work. These natives may also make excellent music therapists, understanding how to wield the transformative vibrations of sound.</p>
        <h2>Scorpio Compatibility</h2>
        <p>When exploring overall astrological compatibility, it’s important to consider more than the sun sign, as the rising sign, moon and other planetary connections will tell the whole story in all kinds of relationships. That being said, Scorpio natives will tend to blend best with water signs and earth signs; and may need to work harder on relationships with fire signs and air signs.</p>
        <h3>Fire signs</h3>
        <p>Sensitive and private Scorpio may find the volatile and impulsive fire signs the most challenging to relate to.<br>Although Scorpio and Aries share the Mars rulership, and therefore some affinity when it comes to power, they have such a different way of wielding it that it may be hard for these signs to relate. Aries is confrontational, while Scorpio is covert, so they may struggle for control and little ability to compromise.</p>
        <p>Sagittarius and Scorpio share nothing when it comes to their elements or modalities, being adjacent signs. They are like neighbors that have no reason to talk to each other except for the fact that they share a fence. Sagittarius is boldly optimistic, while Scorpio sees the skeletons in everyone’s closet, making their values and beliefs too different to harmonize for the long term.</p>
        <p>Leo and Scorpio are both fixed signs and form a challenging square angle to each other in the zodiac wheel. Both are equally as passionate and jealous as they are stubborn, which can either ignite sexual tension or devolve into power struggles. They may, however, have an interesting creative chemistry that can help their potent personalities blend.</p>
        <h3>Air signs</h3>
        <p>Air signs are social, speedy, and swift, which could be a breath of fresh air in Scorpio’s dark and insular world, but intimately Scorpio may find the air signs a bit too breezy and changeable to truly trust long term.</p>
        <p>Gemini and Scorpio do not share much in common, except for their shared love of button-pushing. Gemini knows how others tick, and Scorpio likes to pull the levers behind the curtain. They may appreciate each other’s mischief and mental capacities but will need to be careful to not turn this tendency on each other too often.</p>
        <p>Libra and Scorpio are opposite in many ways. Venus-ruled Libra loves to keep the peace and wants to see the world through rose-colored glasses. Mars-ruled Scorpio is wired for confrontation and has x-ray vision when it comes to the secrets others are trying to hide. The result is a clash in world views that may be too different to reconcile.</p>
        <p>Aquarius with Scorpio is a unique match, that has the potential to go very right, or very wrong. There will be little moderation between them. Both are stubborn fixed signs and share a love for debates and bubble bursting. Aquarius can be very abstract and conceptual, where Scorpio relies on instinct and feel, making this a tough combination when it comes to elemental nature.</p>
        <h3>Water Signs</h3>
        <p>Water signs match Scorpio’s sensitivity and emotional intelligence with the greatest affinity. There seems to be a psychic, creative, and intuitive current running between them that transcends words.</p>
        <p>Scorpio with Cancer is a good fit, with both signs being private, sensitive, and lovers of solitude. Scorpio may open shy Cancer up to sexual expression, and they may form a deep bond of emotional trust. Cancer nurtures Scorpio, and Scorpio is protective of Cancer, so they potentially understand what the other needs.</p>
        <p>Pisces and Scorpio share a love for the mystical and will likely explore spiritual and philosophical ideas together. This is a complementary pairing that is innately intuitive, creative, and otherworldly. They will enjoy their privacy and retreat together, with Scorpio supporting Pisces’ imaginative wanderings.</p>
        <p>Scorpio with Scorpio can be a potent, sexually magnetic pairing. They are both fearless and enjoy exploring life’s mysteries together. They may need to watch out for being too much alike, as they may experience the same vulnerabilities and dark moods at the same time. The positive side of this is that they will have empathy for each other, which can help them bond and trust.</p>
        <h3>Earth signs</h3>
        <p>Earth signs bring a complementary, elemental affinity to a relationship with Scorpio since practical, structured earth and emotive water blend well.<br>Scorpio and Capricorn work, and play well together. They are individual and powerful enough in their own right to respect one another, and neither are intimidated by the other’s power. Capricorn builds and organizes, while Scorpio investigates and explores, and together, their focuses and talents merge well in love as well as business.</p>
        <p>Virgo< and Scorpio are a potentially strong match, especially when it comes to love compatibility. They will appreciate each other’s attention to detail, and love for perfection. They may have overlapping interests in health and medicine and enjoy collaborating creatively. Scorpio brings some thrill and mystery into Virgo’s orderly world, which may be refreshing and intriguing to Virgo.</p>
        <p>Scorpio and Taurus are polar opposite signs, which can be a magnetic connection or a polarizing standoff. Venus-ruled Taurus loves pleasure and comfort, while Mars-ruled Scorpio thrives on challenge and thrill. Both signs are fixed, so they are likely to be equally slow to compromise. They may either balance each other out, or be too different to last long term.</p>
        <h2>Scorpio Health</h2>
        <h3>Constitution</h3>
        <p class="has-text-align-left">In classical astrological medicine, four temperaments were connected to four vital fluids and four essential constitutions. Scorpio is a water sign, and so is associated with the phlegmatic temperament, which was understood to be cold and moist.</p>
        <p>The phlegmatic temperament was thought to be connected to moisture and fats in the body and the production of phlegm, which lubricates tissues and protects these from infection. Phlegm, however, can be the source of imbalance for the phlegmatic constitution, often being overproduced when Scorpios fall ill, or if they become inactive or overnourished. This represents a tendency for the phlegmatic constitution to become somewhat chilled and stagnant, physically and emotionally.</p>
        <p>They can become too fixated and brooding in their moods, and overly retentive of water and other fluids in their bodies. Their tissues can become boggy, lax, and clogged with toxic substances and emotions, building up too much and not being adequately cleaned out.</p>
        <p>Scorpio’s constitution has another layer that makes it unique and in need of particular care, which comes from Mars’ rulership over this sign. Mars is thought to be a hot and dry planet, which may in some ways help heat and dry out the coolness and excess moisture in the Scorpio constitution. It can also point to a tendency for swelling, inflammation, or blocked heat to occur in Scorpio’s tissues if they lack circulation or become clogged with impurities.</p>
        <p>With Mars’ influence, Scorpios are often somewhat athletic and active, giving them good powers of recuperation. It will be important for them to focus on whole, unprocessed foods, and activities that keep them warm and stimulated.</p>
        <h3>Body Parts</h3>
        <p>In classical astrological medicine, the entire zodiac was mapped out on the human body, with ruling over the genitals, reproductive organs, and the bowels. These vital “root” areas of the body represent the organs that need the most protection and care in the Scorpio native. Being innately connected to sexual expression, the genitals are highly sensitized and can become easily damaged, inflamed, or prone to infection.</p>
        <p>The reproductive organs are intrinsically linked, and can also be prone to swellings, blockages, and disruptions if the Scorpio native is feeling stressed, emotionally imbalanced, or not properly nourished. The bowels, and most specifically the colon, is a sensitive organ in the Scorpionic constitution, as this organ absorbs most of our water and nutrients back into the body in the digestive process. To some extent, the prostate is also connected to Scorpio and should be cared for as well.</p>
        <p>As a result, those with strong Scorpio placements in their chart need to guard their emotional, physical, and psychic health to protect the balance of these vulnerable organs. Sugary and allergy-producing foods promote mucus and should be avoided to keep the Scorpio body clear of stagnation, inflammation, and blockages.</p>
        <h2>Herbal Allies</h2>
        <p><strong>Mugwort</strong>&nbsp;is a prime Scorpio plant ally in the sense that it offers the medicine of antipathy to help restore balance. Mugwort is ruled by Venus, whose signs are opposite to Mars in the zodiac, which is a clue that it will have a balancing and remedial property to Mars-ruled bodies and functions.</p>
        <p>Mugwort is drying and warming, which helps to balance the cool and damp phlegmatic constitution. It also has an affinity for the reproductive organs, helping tone and clear any blockages in the uterus so that the menstrual cycle can be regular. It also has pain-relieving and anti-inflammatory properties, which will balance the vulnerabilities of the Mars-ruled body.</p>
        <p><strong>Nettles</strong>&nbsp;are an important Mars plant that helps with blood cleansing, easing allergy symptoms, and inflammation. The sting of nettle leaves can soothe rheumatoid arthritis pain in the joints, which the phlegmatic constitution can be prone to. It’s stingers stimulate the joint swelling and congestion to break up and clear, as it invites blood flow into these areas.<br>Nettles have many vitamins and minerals, which help support blood building and immunity, all important facets of Mars’ function in the body. Nettles also have some supportive and clearing properties that can help the prostate gland.</p>
        <p><strong>Blackberry</strong>&nbsp;is another Mars plant that can be a helpful Scorpionic ally. It grows in a very aggressive, invasive Mars fashion, and is covered with sharp, sword-like prickles. Blackberry root is an astringent which is very helpful to balance the phlegmatic constitution since it can tighten and tone lax and boggy digestive tissues. It can also dry up excess moisture and mucus, and is helpful if someone is running the risk of dehydration from being ill with diarrhea for too long.</p>
        <h2>Esoteric Scorpio</h2>
        <h3>The Three Decans of Scorpio</h3>
        <p>Each of the twelve zodiac signs represents a thirty-degree slice of a 360-degree band of constellations, circling the earth. The thirty degrees of each sign can be further subdivided into three ten-degree decans or faces, each with its planetary sub-ruler placed around the zodiac in Chaldean order.<br>These faces can be used for timing magical rituals when seeking to evoke and harness Mars’ planetary power. In studying the Scorpio personality, we can use the faces of the Scorpion to fine-tune the flavor and nuance of planets or points placed within these decanic degrees.</p>
        <h3>First Decan of Scorpio: Mars</h3>
        <p>Degrees 0 through 9 of Scorpio are ruled by Mars, which is at home in this sign, boosting the magical strength of this decan. This amplifies the power and potency of Mars, giving those with planets or points in this decan a Martial boost that they can tap into. This is the most Scorpionic of all the three decans, making these natives the most mysterious, tenacious, and driven of all.</p>
        <h3>Second Decan of Scorpio: The sun</h3>
        <p>Degrees 10 through 19 of Scorpio are ruled by the sun. This may heighten the social and outward expressing qualities of those with planets or points in this face. These natives may take roles of leadership and authority, and may not be as shy of the spotlight as those with placements in the other decans. Exploring the ego may be of interest, and here, we may find our Scorpionic psychologists or psychiatrists.</p>
        <h3>Third Decan of Scorpio: Venus</h3>
        <p>Degrees 20 through 29 of Scorpio are ruled by affectionate and artistic Venus. This, however, is a bit of an uneasy combination for the planet of love, since Venus is in her classical detriment in the sign of Scorpio.<br>This decan may heighten the artistic ability and expression of those born with planets or placements here, but it may also add a layer of complication in matters of love. The native may be passionate about pursuing romantic and sexual connection, but they may have some relational conflicts that they need to tend to at times.</p>
        <h2>Scorpio Tarot Cards</h2>
        <h3>Major Arcana: Death</h3>
        <p>The Tarot card that correlates to Scorpio is number 13: Death. This card can seem rather ominous, but rarely is a portent of actual death. The Death card points to the transformative phase in the circle of life that Scorpio as an archetype is most aligned with exploring.</p>
        <p>Number 13 of the major arcana illustrates the principle of death and letting go so that what is past its due date can return to the earth, and become the compost that fertilizes new growth. We can observe and feel this phenomenon happening in nature and also on an internal, soul level.<br>This card appears to remind us of this process so that we don’t become fearful of change and growth. Once we recognize “death” as a time of surrendering to an important part of the creative and evolutionary cycle, we can begin to trust and flow with it.</p>
        <p>We may need to allow ourselves the time to withdraw and grieve, and be with our sense of loss before we are ready to truly move forward and renew. Death is not the end, but only a passage through a world of mystery and shadow that allows us to embrace the fullness of life.</p>
        <h3>Minor Arcana</h3>
        <p><strong>5, 6, and 7 of Cups</strong><br>In the Minor Arcana of the Tarot, the Suit of Cups is associated with the element of water. Here, we see the three decans of Scorpio assigned to the 5, 6, and 7 of Cups, cards associated with working through an emotive, intuitive, and relational cycle. These Cup cards help us recognize the highs and lows of our sensory capacities, so that we may feel our way toward better self-understanding and emotional mastery.</p>
        <p><strong>5 of Cups: Mars in Scorpio</strong><br>The 5 of Cups corresponds to the first decan or face of Scorpio. It carries the potent and assertive sub-signature of Mars and was referred to in the Book of Thoth as the card of “Disappointment.”</p>
        <p>This card depicts a lonely figure standing among spilled and empty cups. It appears when we are questioning our emotional awareness, and are perhaps grieving the loss of intimacy and abundance that the previous cup cards portrayed. It’s a card of contemplation and emotional dissatisfaction.<br>The “Disappointment” card hints that all is not lost in this dark mood as “influences do not show actual decay, only the beginning of destruction; hence, the anticipated pleasure is frustrated…” (Book of Thoth)</p>
        <p><strong>6 of Cups: Sun in Scorpio</strong><br>The 6 of Cups corresponds to the second decan or face of Scorpio. It carries the bold and expressive sub-signature of the sun and was referred to in the Book of Thoth as the card of “Pleasure.”</p>
        <p>This card is more stable than the previous card and depicts a happier, more fruitful scene. Here, the cups are full of life and promise, and all appear to be well. This card depicts a heartfelt emotional pleasure, that warms us and encourages us.</p>
        <p>The “Pleasure” card “implies well-being, a harmony of natural forces without effort or strain, ease, satisfaction…” (Book of Thoth)</p>
        <p><strong>7 of Cups: Venus in Scorpio</strong><br>The 7 of Cups  card corresponds to the third decan or face of Scorpio. It carries the romantic and luxury-seeking sub-signature of Venus and was referred to in the Book of Thoth as the card of “Debauch.”</p>
        <p>The number 7 is dynamic and hints that emotional forces have been tipped out of the stability and balance of the previous card. Here, we see many cups full of exotic and magical treasures. It has a chaotic and confusing element and warns what can happen when pleasure turns into excess and debauchery. This may be a result of indulgence, addiction, and emotional imbalance.</p>
        <p>The “Debauch” card depicts “external splendor and internal corruption.” (Book of Thoth)</p>
    </div>
</div>
</body>
</html>
