<%--
  Created by IntelliJ IDEA.
  User: elmirabajgulova
  Date: 31.10.2021
  Time: 00:21
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <meta name="viewport" content="with=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/styleHome.css">
    <link rel="stylesheet" href="css/styleZodiacSignsPages.css">
</head>
<body>
<%@include file="/WEB-INF/top_nav.jsp" %>
<h1>Virgo</h1>
<div class="grid__content">
    <div class="editorial-article__feed">
        <h2>Virgo&nbsp;Traits &amp; Overview</h2>
        <div class="zs-meta border-grey border-rad-4 grid-1c grid-sm-2c grid-lg-3c grid-c-gap-3 p-2 mb-3">
            <div class="meta-item"><span class="tag">Virgo Dates: </span><span class="tag--bold white">August 23 – September 22</span></div>
            <div class="meta-item"><span class="tag">Symbol: </span><span class="tag--bold white">The Virgin</span></div>
            <div class="meta-item"><span class="tag">Mode + Element: </span><span class="tag--bold white">Mutable&nbsp;Earth</span></div>
            <div class="meta-item"><span class="tag">Ruling Planet: </span><span class="tag--bold white">Mercury</span></div>
            <div class="meta-item"><span class="tag">House: </span><span class="tag--bold white">Sixth</span></div>
            <div class="meta-item"><span class="tag">Mantra: </span><span class="tag--bold white">I Analyze</span></div>
            <div class="meta-item"><span class="tag">Body Parts: </span><span class="tag--bold white">The digestive system</span></div>
            <div class="meta-item"><span class="tag">Colors: </span><span class="tag">Tan &amp; Warm yellow</span></div>
            <div class="meta-item"><span class="tag">Tarot Card: </span><span class="tag--bold white">The Hermit</span></div>
        </div>
        <p>Virgo is the sixth sign of the zodiac, to be exact, and that’s the way Virgos like it: exacting. Those born under this horoscope sign are forever the butt of jokes for being so picky and critical (and they can be), but their ‘attention to detail’ is for a reason: to help others. Virgos, more than any other zodiac sign, were born to serve, and it gives them great joy. They are also tailor-made for the job, since common Virgo traits are being industrious, methodical, and efficient. The sense of duty borne by these folks is considerable, and it ensures that they will always work for the greater good.</p>
        <h2>Virgo Symbolism + Myth</h2>
        <p>The stellar constellation of Virgo has origins in Babylonian society, where it was associated with the goddess Shala, who was depicted holding an ear of grain. To the Babylonians, this goddess ruled over fertility and the harvest, connecting Virgo to some of its earliest archetypal associations.</p>
        <p>This connection to the harvest continues into Greek mythology, where Virgo was connected with the goddess Demeter, who ruled over the bounty of the earth and agriculture as well. Virgo is also connected to Ceres through early Roman culture, where she was the ruler of the same agricultural themes.<br>To this day, Virgo has held this connection with planting, growing, harvesting food, and herbal medicine. In the Middle Ages, Virgo’s virginal symbolism was observed by association with The Virgin Mary.</p>
        <h2>Virgo Element, Mode, and Season</h2>
        <h3>Late Summer</h3>
        <p>In the western tropical zodiac, Virgo season begins on August 23, commencing the final phase of Summer in the Northern Hemisphere. This is the time of year when the sun’s heat and light are beginning to mellow, with the days beginning to shorten toward the Fall Equinox. Virgo season is when nature’s abundance and fertility become ready for gathering and harvesting, lending to the earthy, tending, and organizational qualities of the Virgo archetype.</p>
        <h3>Mutable Mode</h3>
        <p>Virgo is the second of the four mutable signs of the zodiac, who all hold an elemental energy of change at the end of the four seasons. Virgo season is the end of Summer, where the heat of the season is beginning to mix and surrender to the coolness of the upcoming Autumn. This mixed and varied seasonal quality is the root of Virgo’s mutable, adaptive, and changeable nature as an archetype.</p>
        <h3>Earth Element</h3>
        <p>Virgo’s element is earth, the heaviest and most solid element, thought by ancient astrologers to be the densest form of matter. Earth represents the very structure that all of nature is built with and upon, and without it nothing could take a material form. Virgo’s affinity for being efficient, skilled, and resourceful are all akin to the structure and tangibility of the earth element.</p>
        <p></p>
        <p></p>
        <h2>Virgo Planetary Rulership</h2>
        <h3>Domicile of Mercury</h3>
        <p>In classical astrology, Mercury was assigned rulership of both Gemini and Virgo. Virgo was thought to be the nocturnal/night home of Mercury, a conscientious and detailed-focused earth sign that allows Mercury to express and enact its most swift and facile functions. Among these are analysis, communication, the ability to discern and discriminate, and fine, manual dexterity.</p>
        <p>Those born with Mercury in Virgo will likely find that many of these abilities come naturally and easily to them. Mercury in Virgo folks typically have a keen, perceptive mind. They are also very receptive, considerate, and tuned into their heightened nervous system responses to help them navigate their choices and actions.</p>
        <h3>Detriment of Jupiter</h3>
        <p>Virgo is in polarity with the mutable water sign Pisces. Classically ruled by Jupiter, Pisces likes to explore expansive emotional and spiritual territory. Being innately intuitive and comfortable with vulnerability, Jupiter-ruled Pisces is a contrast to Mercury-ruled Virgo, who needs to organize, analyze, and discern what is useful.</p>
        <p>Imagine Jupiter, the bold, boundless planet of opportunity and philosophy confined to the efficient and perfectly arranged world of the virgin, who likes things just so. Jupiter in Mercury’s sign would have to somewhat compensate for this “detriment,” which may simply mean that natives born with this placement may tend to amplify their attention to detail, or their optimistic and philosophical side may feel constricted under difficult standards.</p>
        <p>These standards may or may not be of their own making but may challenge those born with this placement to balance perfection with a need to stay open to exploring and expanding into opportunities.</p>
        <h3>Fall of Venus</h3>
        <p>Venus was said to be exalted in Pisces by classical astrologers, where she is able to uniquely and auspiciously express her poetic, artistic, and pleasure-seeking qualities. When in the opposite sign of Virgo, Venus was said to be in her fall, which may not pose as strong of an adaptive challenge as a detriment might, yet still puts the planetary force somewhat out of its comfort zone.</p>
        <p>Venus wants to love, connect, and attract, but Virgo, being a somewhat cool and dry earth sign, may be too shy and composed as an archetype to allow Venus’ energy to flow freely. This could present in these natives as the need to take a long time to warm up to and trust those that they love. It can also take form as a tendency to place high expectations for consideration and perfection on those they are in relationships with.</p>
        <p>Those with this placement may need to let their guard down and be more accepting of others’ “flaws” to let love, which is sometimes messy, into their lives. Natives with Venus in Virgo benefit from not being too self-critical and by being more loving of themselves. The good news here is that Venus’ creative forces blend with the Virgin’s manual dexterity to often produce great artisans and craftspersons.</p>
        <h2>Virgo House Rulership</h2>
        <h3>The Sixth House</h3>
        <p>In the modern astrology system of the Twelve Letter Alphabet, each zodiac sign rules one of the twelve houses in the birth chart. This innovation was created by psychological astrologers to match sign affinities to related house topics.</p>
        <p>Virgo was assigned the sixth house of health, service, and day-to-day work routines, since Virgo’s earthy and hygienic pursuits are aligned with the concerns of this house. Since Virgo is ruled by the planet of communications, it invites an analytical Mercury sub-signature to the sixth house.</p>
        <h3>The First House</h3>
        <p>In traditional astrology, Virgo’s planetary ruler, Mercury, was said to find its “joy ” in the first house of self and identity in the birth chart. This house, associated with our bodies and sense of purpose, symbolizes a merging of spirit and matter to form a unique being in the world.</p>
        <p>In classical astrology, the degree of the rising sign was found inside the first whole sign house, dividing it into a portion that was above the horizon, and a portion that was below it at the moment of our birth. This is connected to the Hermetic alchemical axiom “as above, so below,” a phenomenon we observe and practice in the magical arts.</p>
        <p>Magic and its mysteries are given to us by the god Hermes, who is associated with Mercury, making this planet able to wield special potency as a bridge between the heavens and earth from the first house.</p>
        <h2>Virgo Characteristics</h2>
        <h3>Personality</h3>
        <p>Virgo’s personality traits are derived from its receptive, feminine, or yin qualities, making this sign oriented toward contemplation and engagement with inner awareness. Alive in both, a Virgo woman or Virgo man, those born with the Virgin as their rising, sun, or moon sign have a diligent, adaptable, and observant energy in the core of their personality, an echo of the preparedness and utility of late summer/early fall activities.</p>
        <p>As a mutable sign, Virgo holds the qualities of being an alchemical “synthesizer,” able to find relationships between seemingly disparate and disjointed factors to transform these into a meaningful, useful harmony.<br>Those with the sign of the Virgin prominent in their charts are great at dedicating themselves to projects and relationships that need some care, healing and tending, to restore them back to health, purity, and natural function.</p>
        <h3>Strengths</h3>
        <p>The primary Virgo strengths can be found in their mental agility, adaptability, and skillful, meticulous nature. Diligent and observant, these folks think clearly, learn quickly, and gain enormous satisfaction in serving, healing, and helping to bring order, perfection, and practicality to their world.</p>
        <p>Cool and conscientious, they are typically able to carefully discern between what is skillful and useful, and what is not. Too busy working on improving themselves and the world around them, they are often humble and modest and are usually too earthy and sensible to become arrogant and self-aggrandizing.</p>
        <p>Virgoan powers of communication are powerful and they value developing a functional emotional vocabulary to help themselves and others to be understood. Hard-working and efficient, they are happy to be at the service of friends and family, not in a self-diminishing way, but in a way that is innately considerate and compassionate. Diligent, dexterous, and facile, those born under the sign of the Virgin are blessed with artistic and technical abilities, empowered with Mercury’s signature highly functioning fine motor skills.</p>
        <p>The sign of the Virgin is innately connected to the earth and nature, and here we may find some of the world’s great animal lovers and environmental conservationists. The Virgoan archetype reminds us of our dependency on Mother Nature, and the need for our relationship with her to be healthy and reciprocal. These values are often upheld in Virgoan natives who seek to restore bodies, minds, and ecologies back to their purified and intended natural states.</p>
        <h3>Weaknesses</h3>
        <p>Some potential weaknesses in Virgo’s approach to life are rooted in their great strengths. Though intelligent and mentally dexterous, this highly functional mind can easily become overactive, leading to worry, anxiety, and insomnia. What they think up may become more real than what is actually happening, making it important for these natives to stay grounded in their bodies, breath, and the moment.</p>
        <p>The Virgin’s talent for service and healing can get out of hand if they are overidentifying with being useful to others. They may be keeping themselves busy to avoid uncomfortable feelings and need to remember that it’s okay to “just be” at times, and to balance service with some healthy self-care and “healthy selfishness.”</p>
        <p>Virgo’s naturally discerning nature can become disproportionate if they are feeling unbalanced, leading them to notice flaws and inefficiencies in themselves and others, more than they notice what is actually good. With this tendency they may hold themselves and others to impossibly high standards of perfection, sometimes causing more stress than anyone needs.<br>Naturally modest and humble, Virgin natives may become too much so, succumbing to self-doubt and worry that they will never be good enough and that their work will never be worthy of presenting to the world. This may paralyze them from taking risks, sometimes leading to a surprising streak of avoidance and procrastination that normally productive Virgos can fall prey to.</p>
        <p>Those born under the sign of the Virgin care deeply about bodily health and protection of the environment, however, they can become inordinately focused on toxins, hygiene, and catching possible diseases. Virgo natives must be careful to not give into obsessive and compulsive rituals, as well as going down the rabbit hole of self-diagnosis. The stress that this causes will only lead to the ill health that they fear.</p>
        <p>Virgo children will be well-nurtured if they are encouraged to get their hands dirty and make a mess, to be allowed to make mistakes, and yet be loved unconditionally. Naturally self-critical and self-aware, they may be too sensitive to overly stern criticisms and need to know their self-worth is not connected to how well they perform.<br></p>
        <p></p>
        <p></p>
        <h2>Virgo Life Purpose and Career</h2>
        <h3>Mantra and Purpose</h3>
        <p>The voice of clarity, precision, and utilization comes forward in the Virgo mantra:&nbsp;<strong>I analyze.</strong>&nbsp;The Virgin’s sense of purpose is all about organizing and dissemination of material resources, so that our lives can flow and operate efficiently and optimally. It is also important to them to be helpful and useful in some way, linking to their alternate mantra:&nbsp;<strong>I serve.</strong></p>
        <p>The Virgoan’s innate alignment to health preservation and dutiful service is a pillar to their communities and relationships. They attend to the essential details of life that may go unnoticed until they are not functioning properly. We all have Virgo somewhere in our birth chart, so we can look to the house that the sign of the Virgin rules to find the specific area of our life we approach in an organized, contentious, and efficient way, or where we need to call in Virgoan sensibility for material mastery.</p>
        <p>Virgo people tend to be drawn to any pursuit where they can sort, repair, and attend to a practical or bodily need. Technical and craftsperson roles are well-suited to this mutable archetype, as well as health care, herbalism, and anywhere precise attention is needed.</p>
        <h3>Virgo at Work</h3>
        <p>Virgo’s conscientious and reflective nature makes them uniquely suited for professions where they are needed to analyze data and focus on the details of a project or service. Though earthy and dependable, they are also mutable, so their careers do need to have some dynamic of developing and implementing change and protocols that lead to better efficiency.<br>At the same time, their sense of timing and order is very important to them, so routine jobs that involve regularity and consistency help them feel focused and grounded on the task at hand. Workplaces where they help organize or can be part of a well-administered team with clear, discernable roles, will help them make effective use of their talents.</p>
        <p>Virgos will likely find dirty, cluttered, and untidy workspaces to be a stifling and distracting hazard, so they may work to help create well-attended work and living spaces for others. These folks will certainly need to cultivate this sort of harmonious environment for themselves to feel calm and satisfied.<br>With keen Mercurial minds, those born under the sign of the Virgin may take to roles in analysis and statistics naturally. They may be involved in designing the formulas for collecting numbers, and also designing the systems that sift and examine the meaning and implications of raw data. This can take form in bookkeeping and accountancy roles as well.<br>Ruled by Mercury, Virgo has a knack for words and language, and may enjoy careers in translation, linguistics, and speech therapy. They also will likely be quite literary, so will make good writers, copy editors, and fact-checkers, as no detail will go unnoticed by them.</p>
        <p>With a strong probability that those born under the sign of the Virgin will make great teachers and mentors, they could be found sharing technical skills of all kinds. This could be in many forms, from computer programming to trades and craftsperson professions. Virgos will likely have a clear, useful, and organized way of disseminating knowledge, and will demand perfection from their students.</p>
        <p>The Virgin’s natural critical and discerning facilities will find a home in the world of professional critique. Being interested in nutrition and food quality, they could make excellent food safety inspectors as well as fine dining critics. They may also turn their keen senses and refined tastes to critique the world of fashion, art, literature, and music. To earn their thumbs up will be a great accomplishment!</p>
        <p>Facile and dexterous, Virgos have many talents. They are often accomplished makers, crafters, and artisans themselves, producing works of enormous beauty and detail. Their creations may have a twist of ingenuity, or utility, as functional art.</p>
        <p>Health is of traditional and personal importance to the Virgo native, who likely had to learn to care for their own delicate digestion and nervous system first. The skills and insights they gain along the way will make them suited to health and nutrition professions of all kinds, like herbalists, naturopaths, dieticians, and wellness practitioner roles in yoga and meditation.</p>
        <p>The powerful mental energy and ability that comes with being born in Mercury’s sign will draw the Virgo interest toward psychology and mental health. They may make good social workers, counselors, and talk therapists. They may also even combine their craft and makers skills with mental health work in the form of art therapy.</p>
        <h2>Virgo Compatibility</h2>
        <p>When exploring overall compatibility in astrology, it’s important to take more than the sun sign into consideration, as the rising sign, moon, and other planetary cross-connections will tell the whole story in relationships. That being said, Virgo natives will tend to blend best with water signs and earth signs; and may need to work harder on relationships with fire signs and air signs.</p>
        <h3>Fire signs</h3>
        <p>With their love of perfection and need for order, Virgos may find the volatile fire signs the trickiest to relate to.</p>
        <p>Though Virgo’s nervous and somewhat reserved nature may benefit from some fiery warmth and enthusiasm, Mars-ruled Aries, especially, may be too brash, chaotic, and impatient for the considerate Virgin to truly relax with.</p>
        <p>Sagittarius and Virgo share a mutable mode, but their signs form a square aspect with each other, highlighting friction and challenges between them. All of the structure and order that Virgo takes grounding comfort in, Sagittarius enjoys testing and upturning, just for fun. Even more so, Sagittarius can be notoriously non-committal; which Virgo will find hard to trust.</p>
        <p>Leo and Virgo have nothing elementally and modally in common, being adjacent signs on the zodiac wheel. Similar to the dynamic between Aries and Virgo, their natures and motivations are very different, with Leo often being too tempestuous and dramatic for Virgo’s taste. A saving grace may occur, however, if either of these potential lovers has planets in each other’s signs, which can bring some points of affinity into their relationship.</p>
        <h3>Air signs</h3>
        <p>Air signs are swift, speedy, and social, which can be a potential match for talkative Virgo, but with the Virgin being a stickler for perfection and order, they may find air signs too breezy and changeable to sync their lives with.<br>Gemini shares a Mercury rulership with Virgo, which could make for a very chatty and analytical connection. The tricky part is in how they work with change; Virgo may find it unsettling, where Gemini may feel unsettled without it, so they may disagree on what makes them feel comfortable.<br>Libra and Virgo can work well together, both being considerate and thoughtful by nature. Virgos tend to be critical of themselves or others when they are feeling imbalanced or insecure, which could feel like a bit of a downer to Libra, who strives to stay positive and upbeat. They will both have to find a way to relate to each other’s emotional style to connect long term.</p>
        <p>Aquarius with Virgo is an unlikely, but potentially interesting pair. They may connect on a shared love of ideas, analysis, and dry wit. Virgo, however, may find Aquarius too eccentric and contrarian to make plans with, and may wonder where they stand with the Water Bearer too often to feel truly secure at their side.</p>
        <h3>Water Signs</h3>
        <p>Water signs</a> bring vulnerability and emotional intelligence to a relationship with practical and orderly Virgo, which is naturally fruitful and complementary.</p>
        <p>Cancer </a>will be very good at nurturing Virgo, helping them feel safe to open up and be vulnerable. Virgo responds with attention, care, and their own brand of nurturing, which will help them make a warm and well-organized home together.</p>
        <p>Pisces</a> broadens Virgo’s receptive capacities by bringing spiritual and philosophical awareness to their lives. This is a complementary relationship, and also a case of opposites attract. Pisces can help ease the Virgin out of their need for perfection and order, and Virgo offers support and structure to Pisces soulful and creative ideas. This match could potentially be too polarizing, however, if they can’t find a way to take a page out of each other’s book.</p>
        <p>Mars-ruled Scorpio can bring sexual magnetism to a relationship with Virgo, helping them open up to sensuality and exploration. This can be a magnetic match, with Virgo not shying away from Scorpio’s dark and potent depths. The two may share a love for probing the mysteries and psychological workings of the mind, and appreciate each other’s interests in complementary ways.</p>
        <h3>Earth signs</h3>
        <p>Earth signs Taurus and Capricorn have the greatest elemental affinity with Virgo, sharing themes of stability, practicality, and efficiency between them.<br>Virgo with Virgo can meld together easily, organizing their lives and routines to hum like a finely tuned engine. They innately understand each other’s needs for order and can relax knowing they share the same attention to detail.</p>
        <p>The authoritative cardinal earth sign Capricorn shares Virgo’s love for thoroughness and perfection. These two can build a world together, with similar, yet interlocking skills in material mastery. They both gain each other’s trust and respect by having both feet on the ground, and showing they can be counted on when the going gets tough. They share a similar rhythm with their body awareness and know what the other needs.</p>
        <p>Taurus and Virgo, especially, have good love compatibility, since they share many affinities and may especially connect over their interests in body care and nature. Virgo may balance Taurus’ tendency for indulgence with herbal and health recommendations, and Taurus can patiently help ground and soothe Virgo’s somewhat anxious nature. There is much for the other to enjoy and depend on here, that they will find comfort in their union.</p>
        <h2>Virgo Health</h2>
        <h3>Constitution</h3>
        <p>In classical astrological medicine, there were four temperaments that were connected to four vital fluids and four essential constitution types. Being an earth sign, Virgo is associated with the melancholic temperament, which was understood to be cold and dry.</p>
        <p>The melancholic temperament was thought to be connected to the spleen, which filters blood and supports immunity. The melancholic constitution was also considered to be connected to a metaphorical substance in the body that ancient physicians called “black bile.”</p>
        <p>This represented a tendency for the melancholic constitution to become cold and stagnant, where toxic substances were able to build up too much and not be adequately cleaned out. This lends itself to the medical astrology idea that Virgo’s mood and constitution can become too chilled and blocked if it is not balanced by movement, circulation, and cleansing hydration.<br>Virgo’s constitution had another layer to it by this ancient medical system that comes from cold and dry Mercury’s rulership over this sign. This was said to add another melancholic layer to the Virgoan health as well, making this constitution doubly prone to dryness, tension, and tissue constriction.<br>As a result, Virgo may be one of the more delicate earth signs, who needs a lot of grounding, nourishment, heart and nerve protection, hydration, and relaxation routines to keep in optimal health. This may be why Virgo is traditionally drawn to health care, as they often are their own first patient.</p>
        <h2>Body Parts</h2>
        <p>In classical astrological medicine, the entire zodiac was mapped out on the human body, with Virgo ruling over the digestive system, intestines, and spleen. Being under Mercury’s rule, the Virgoan body shares with Gemini a connection with the nervous system that digestion is intrinsically linked to. As a result, those born with the Virgin prominent in their birth charts may have delicate digestive systems that can be easily thrown off by anxiety and the disruptions of stress.</p>
        <p>The same way that Virgo natives need to organize their lives and be useful, the digestive system mirrors this function in a bodily way. We can observe this in the processing and categorizing nutrients so that they can be distributed throughout the body. This includes emotions or the gut instinct, that begins in the enteric nervous system, linking to Virgo’s need to “digest” what they feel. How well that digestion operates depends on the balance the native can maintain between their work and inner life.</p>
        <h2>Herbal Allies</h2>
        <p><strong>Lavender</strong>&nbsp;is a prime Virgo herbal ally. It grows in warm, dry environments and is itself a warm and dry plant in its qualities, which can help the cold and tense Virgo constitution. Its soothing aromatic fragrance is calming, and its oils are used in aromatherapy to cure Virgo’s anxiety and relieve cramping and tension. It has an opening and clearing effect on the body, warming the head, calming fears and worries, and encouraging sleep.</p>
        <p><strong>Parsley</strong>&nbsp;is another fine green Mercury plant whose delicate branching leaves resemble the interconnectivity of the body. Parsley is thought to be moderately hot and dry, warming up cold, constricted tissue conditions. It also warms the stomach, liver, and spleen, and is a known diuretic, meaning it helps promote urination to clear water retention. It is also carminative, helping to clear digestive bloating and gas in the anxious Virgo digestive system.</p>
        <p><strong>Skullcap&nbsp;</strong>is an herb that is particularly helpful to those with strong Virgo placements who may be prone to worry and stress. The plant’s flower buds look like little skulls, lending a morphological clue that this plant will be helpful for the head.</p>
        <p>Skullcap is an effective sedative that calms a frenetic mind, soothes anxiety, and can help treat insomnia. It is also effective in treating nervous tension, high cholesterol, and artery hardening, all conditions that can lead to heart disease and stroke, which sensitive Virgo’s may be vulnerable to after lives of stress and chronic worry.</p>
        <h2>Esoteric Virgo</h2>
        <h3>The Three Decans of Virgo</h3>
        <p>Each of the twelve zodiac signs represents a thirty-degree slice of a 360-degree band of constellations, circling the earth. The thirty degrees of each sign can be further subdivided into three ten-degree decans, or faces, each with its own planetary sub-ruler placed around the zodiac in Chaldean order.</p>
        <p>These faces can be used for timing magical rituals when seeking to evoke and harness Mercury’s planetary power. In studying the Virgoan personality, we can use the faces of the Virgin to fine-tune the flavor and nuance of planets or points placed within these decanic degrees.</p>
        <h3>First Decan of Virgo: Sun</h3>
        <p>Degrees 0 through 9 of Virgo are ruled by the sun, making those with planets in the first decan potentially more confident and assured than what we might expect of Mercury’s nervous earth sign. There may be an extra signature of vitality for those born with planets or points in this decan, with a strong part of their ego expression presenting this sign’s attributes.</p>
        <h3>Second Decan of Virgo: Venus</h3>
        <p>Degrees 10 through 19 of Virgo are ruled by Venus. This is the “fall” of Venus, where the planet of love is somewhat nervously and tentatively placed. The Virgoan theme of being a bit shy and slow to trust in love may be more prominent for those with birth placements in this decan. The heightened talents of artistry also present strongly in natives born with planets or points in this face.</p>
        <h3>Third Decan of Virgo: Mercury</h3>
        <p>Degrees 20 through 29 of Mercury are ruled by swift and changeable Mercury. This face represents the domicile of the messenger planet, so it heightens the mental and analytical talents of those born with birth placements here. This decan is the strongest, most pure of the Virgoan signatures, amplifying the interests in language, nature, and health, but also can heighten the nervousness that often goes with this sign.</p>
        <h2>Virgo Tarot Cards</h2>
        <h3>Major Arcana: The Hermit</h3>
        <p>The Tarot card that correlates to Virgo is number 9: The Hermit. This card depicts a wandering sage, perhaps on a pilgrimage, with only a lamp and staff to guide each step of this insular journey.</p>
        <p>The Hermit card appears when we are withdrawing, perhaps retreating from our routines and lives, to go within for self-reflection. It represents a need to conserve and concentrate our energies and direct our awareness toward contemplation before we can make a new beginning or embark on a new journey. This thoughtful and reflective process allows us to abandon the external and material to reconnect with our inner guidance so that we can digest the knowledge we have gained so far, and transmute it into the wisdom of the sage.</p>
        <p>The card 9 shares the earthy, contemplative, and analytic energies of Virgo, yet it can appear as a warning that we may have overextended ourselves in talk and excessive doing. Perhaps we are calming our anxieties, or finding a sense of purpose by being busy and useful, but have lost an inner connection to what it is we believe and truly serve?</p>
        <p>This card is a reminder of what action we can take when we are at the end of a cycle, in the still point of self-discovery, before the beginning of the next.</p>
        <h3>Minor Arcana</h3>
        <p><strong>8, 9, and 10 of Pentacles</strong><br>In the Minor Arcana of the Tarot, the suit of Pentacles, also known as Coins or Disks, is associated with the element of earth. Here, we see the three decans of Virgo assigned to the 8, 9, and 10 of Pentacles, cards associated with the completion of a material cycle.</p>
        <p>When these cards show up, we may be coming to the end of a project, a goal, or another earthly labor, and are reflecting on our losses and successes. The final three pentacle cards in the minor arcana represent the sum of our relationship to materiality, and warn of the need to balance the usefulness of material gain and mastery without becoming overly materialistic.</p>
        <p><strong>8 of Pentacles: Sun in Virgo</strong><br>The 8 of Pentacles corresponds to the first decan or face of Virgo. It carries the warm and assured sub-signature of the sun and was referred to in the Book of Thoth as the card of “Prudence.”</p>
        <p>This card appears when we have dedicated ourselves to gaining new skills and are achieving some mastery over a project with our material talents. A level of concentration and dedication is required before a new level of ability, or completion can be attained. It depicts a worker “prudently” applying themselves to this goal.</p>
        <p>The “Prudence” card signifies “intelligence lovingly applied to material matters, especially those of the agriculturalist, the artificer, and the engineer…” (Book of Thoth)</p>
        <p><strong>9 of Pentacles: Venus in Virgo</strong><br>The 6 of Pentacles corresponds to the second decan or face of Virgo. This card carries the abundant and prosperous sub-signature of Venus and was referred to in the Book of Thoth as the card of “Gain.”</p>
        <p>This card depicts a maiden enjoying the Venusian fruits of her labors, feeling at one with the material world, and in harmony with nature. It is an auspicious card that encourages resting on one’s laurels, but warns that this resting should not be overly indulged in. It reminds us to also have humility and gratitude for the hard work, and good fortune that has led to this moment of achievement and security.</p>
        <p>The “Gain” card depicts “good luck attending material affairs, favor, and popularity.” (Book of Thoth)</p>
        <p><strong>10 of Pentacles: Mercury in Virgo</strong><br>The 10 of Pentacles corresponds to the third decan or face of Virgo. It carries the adaptive sub-signature of Mercury and was referred to in the Book of Thoth as the card of “Wealth.” It’s interesting to note that in classical astrology, Mercury was associated with wealth and the flow of money, which the imagery of this card supports.</p>
        <p>This card appears to show the successful completion of the cycle and teachings of the Pentacles. It shows a multi-generational family, enjoying the gains and prosperities of hard work and intelligent investment. There is a sense of abundance and an ability to give back to future generations.<br>The “Wealth” card also warns of wealth being “dissipated unless put to further use by devoting its power to objects other than mere accumulation…” (Book of Thoth)</p>
    </div>
</div>
</body>
</html>
